### PR TITLE
  github: use helpers

### PR DESCRIPTION
**Pull request by lasers**
This module here is somebody's baby. Tread lightly.
* Uses `self.py3.command_run()`.
* Sorted the placeholders.
* Updates the requests w/ name and description.
* Grouping things together. Omitting lines.

Let me know what to undo if any. Thanks.

**EDIT:** Github's `format`/`format_notifications` need a boob job cause it ain't perfect.

~~F~~ format should be... `'{repo} {issues}/{pull_requests}`.
~~NF~~ format_notifications should be... `'{repo} {issues}/{pull_requests}{notifications}`.
Idk if we need `{notifications_count}`. I'm asking you this.

Example: I cannot do this `py3status 32/45` --> `Github: 3`
Also, an `use_urgent` option to turn off `urgent`.
Unrelated: Maybe IMAP should get urgent and `use_urgent` option too.

**EDIT:**
* Now uses `self.py3.format_contains(self.format, '{here}')` too.
* ~~Not working for me. Something's off. Got `py3status ?/?all` instead.~~
* **FIXED.** `py3status 32/45`. I used `{here}` instead of `here`. :confused: 
* Python2and3 tested OK.
* Remove `Examples:` section?

### CODE REVIEW

**Comment by tobes** [comment]
Thanks looks good

---

> This module here is somebody's baby. Tread lightly.

Nothing is precious

>    Uses self.py3.command_run().

nice

>    Sorted the placeholders.

except {repo} and {repo_full}

>    Updates the requests w/ name and description.

I think it is called requests not python-requests (I don't care too much as it will die very soon) but that is what it is called in pypi

>    Grouping things together. Omitting lines.

Sometimes blank lines are nice but ok

> Let me know what to undo if any. Thanks.

looks good

> EDIT: Github's format/format_notifications need a boob job cause it ain't perfect.

I thought you meant Github not this module

> F should be... '{repo} {issues}/{pull_requests}.
> NF should be... '{repo} {issues}/{pull_requests}{notifications}.

full names makes things much more readable 

> Idk if we need {notifications_count}. I'm asking you this.

for now it stays - this module is old and pre-dates the formatter so there was no magic.

> Example: I cannot do this py3status 32/45 --> Github: 3

what do you mean here I don't understand

> Also, an use_urgent option to turn off urgent.

I think if we were to do this it should be a more general option that works on all modules/universally.  But it is a nice idea maybe add as an issue

> Unrelated: Maybe IMAP should get urgent and use_urgent option too.

perhaps it should

> Remove Examples: section?

examples are nice

**Comment by lasers** [comment]
>>Sorted the placeholders.
>
>except {repo} and {repo_full}

What do you mean here I don't understand

>>Example: I cannot do this py3status 32/45 --> Github: 3
>
>what do you mean here I don't understand

Normal `py3status 32/45`... Got a notification... `Github: 3`  _(Go away `py3status 32/45`)_

Thanks for looking. That's a nice written module. Easily my favorite. :+1:

**Comment by tobes** [comment]
>     except {repo} and {repo_full}
>
>What do you mean here I don't understand. EDIT: It is sorted okay?

{repo_full} the full name of the repository being checked.
    eg ultrabug/py3status
{repo} the short name of the repository being checked.
    eg py3status

should be 

{repo} the short name of the repository being checked.
    eg py3status
{repo_full} the full name of the repository being checked.
    eg ultrabug/py3status


> Normal py3status 32/45... Got a notification... Github: 3 (Go away py3status 32/45)

I have no ideai.What format did you use etc? I can't read your mind


> Thanks for looking. That's a nice written module. Easily one of my favorites. 👍

Thanks,  It's useful,  `static_string` was my favourite for a long time.  Not sure which is now.

**Comment by lasers** [comment]
Ah. Apologies. I will fix it right away.
```
If I sort, I get this. | If I sort, I get this.
repo                   |  {repo_full}
repo_full              |  {repo}
```
>>Normal py3status 32/45... Got a notification... Github: 3 (Go away py3status 32/45)
>
>I have no idea. What format did you use etc? I can't read your mind

Using default format as example because I don't see how I can configure it this way.

Default: If I have `py3status 32/45` and got a notification, I will see `py3status 32/45 N1`
Desired: If I have `py3status 32/45` and got a notification, I will see `Github: 1`

**Comment by tobes** [comment]
> I will fix it right away.

Yeah we want the human readable sort.


> Desired: If I have py3status 32/45 and got a notification, I will see Github: 1

I think this will work but I've not had a chance to confirm
`format = '[Github: {notification_count}|{repo} {issues}/{pull_requests}]'`

**Comment by tobes** [comment]
actually it's more like
`[[\?not_zero {notifications_count}]|{issues}/{pull_requests}]`

**Pull request merged**
