### PR TITLE
Amaury Brisou : Counter and Screenshot Modules

### PR DESCRIPTION
**Pull request by amaurybrisou**
I have added two modules, counter.py and screenshot.py, read their descriptions to figure out what they do.
Basically:
* Counter count the time and calculate the service price according to taxes and price per hour configured.
* Screenshot takes screenshot (depends on gnome-screenshot, can be modified at will). It is also able to upload the screenshot to a remote server via ssh.

### CODE REVIEW

**Comment by ultrabug** [comment]
Thanks a lot Amaury, I'll have a deeper look at them and will permit myself to comment some QA stuff and remarks on the code if needed.

**Comment by amaurybrisou** [comment]
De rien ;)

----- Mail original -----
De: "Ultrabug" <notifications@github.com>
À: "ultrabug/py3status" <py3status@noreply.github.com>
Cc: "Amaury Brisou" <amaury.brisou@gmail.com>
Envoyé: Vendredi 3 Avril 2015 16:29:53
Objet: Re: [py3status] Amaury Brisou : Counter and Screenshot Modules (#93)



Thanks a lot Amaury, I'll have a deeper look at them and will permit myself to comment some QA stuff and remarks on the code if needed.

**Comment by ultrabug** [comment]
Ok @amaurybrisou, first of all, please :
* ensure both your modules pass a flake8 check properly
* confirm that they work with both python2 and python3
* ensure that you only declare **configuration variables** as Py3status class attributes, the rest should be declared in the __init__()
* drop all unused methods (__init__ and kill on the screenshot module)

Thanks !

**Comment by ultrabug** [comment]
Timeout, I'll do it myself ;) thx again mate !

**Pull request merged**
