### PR TITLE
Bug Fix: py3 python2 unicode fixes for notify_user() and log()

### PR DESCRIPTION
**Pull request by tobes**
Both `py3.notify_user()` and `py3.log()` suffered issues when being sent a unicode string under python2.

This PR fixes the issue so that they are both much more forgiving about the strings they will accept.

### CODE REVIEW

**Comment by tobes** [comment]
Add `is_python2()` documentation

**Comment by tobes** [comment]
@ultrabug I've added documentation as requested for the `is_python_2` I have changed it from being an attribute to a method for consistency with the other bits of the documentation

**Comment by ultrabug** [comment]
Thanks a lot !

**Comment by pydsigner** [comment]
Wouldn't it be cleaner as an attribute?

**Comment by tobes** [comment]
> Wouldn't it be cleaner as an attribute?

Maybe, because the name `is_python_2` it feels like it should be a function to me.

If it is an attribute it should really be a `py3.CONSTANT` so if we had a nice name I'd be happy to change as currently there are no active users.  `py3.PYTHON_VERSION` might be ok.

I'm not too bothered either way but if you have strong feelings about this then we can do something.

**Comment by ultrabug** [comment]
We've had the debate on IRC and quickly decided to go for the method. I still don't have a strong opinion about this.

So Daniel if this is something you really think we should have as an attribute then I agree with @tobes proposal on the constant.

**Pull request merged**
