### PR TITLE
vnstat: replace deprecated --exportdb with --oneline

### PR DESCRIPTION
**Pull request by lasers**
Replace deprecated `--exportdb` with `--oneline b` (bytes). This addresses #1568.

EDIT: ..........................
`--exportdb` got deprecated. We need to fix this.
```
$ vnstat --exportdb | grep -i 'd;0'   # 'd;0' for first day, 'm;0' for first month
d;0;1541417662;334;19;58;963;1

# where  d  =  days,  0 = day number in database (0 is today), 1077314401
# date in Unix time, 559 = rx MiB, 7433 = tx MiB, 68 = rx KiB, 557  =  tx
# KiB and 1 tells that vnStat has filled this value and it is in use.

```
I went with `--oneline` because it looks like a good fix. `--json` would give us more.
```
$ vnstat --oneline
1;eno1;11/05/2018;334.06 MiB;19.94 MiB;354.00 MiB;69.77 kbit/s;Nov '18;334.06 MiB;19.94 MiB;354.00 MiB;7.25 kbit/s;334.06 MiB;19.94 MiB;354.00 MiB                               
```
```
--oneline
       Show  traffic  summary  for  selected  interface  using one line with a
       parseable format. The output contains 15 fields with ;  used  as  field
       delimiter. The 1st field contains the version information of the output
       that will be changed in future versions of vnStat if the  field  struc‐
       ture changes. The following fields in order 2) interface name, 3) time‐
       stamp for today, 4) rx for today, 5) tx for today, 6) total for  today,
       7)  average  traffic rate for today, 8) timestamp for current month, 9)
       rx for current month, 10) tx for current month, 11) total  for  current
       month,  12)  average traffic rate for today, 13) all time total rx, 14)
       all time total tx, 15) all time total traffic.  An optional mode param‐
       eter  can  be  used  to force all fields to output in bytes without the
       unit itself shown.
```
Nice, but we want `--online b` for bytes due to `coloring`.
```
$ vnstat --oneline b
1;eno1;11/05/2018;350283776;20909056;371192832;8721;Nov '18;350283776;20909056;371192832;905;350283776;20909056;371192832
```

Offtopic: `coloring` and several other configs ought to be deprecated in favor of `thresholds` and `py3.format_units()` and some more. Thanks.

### CODE REVIEW

**Comment by tobes** [comment]
The code and your comment do different things :(

It is really important that you PR initial comment covers what the code does (any why).

You have tried to sneak in a new feature with no rational

**Comment by lasers** [comment]
What new feature? Different argument = different output. This is minimal diff.

**Comment by cyrinux** [comment]
Thanks lasers 🙏 will try

**Comment by lasers** [comment]
@tobes I updated the initial comment. There are no new features. Sorry.

**Comment by cyrinux** [comment]
I confirm this works as expected. This can be merged for me.

**Comment by tobes** [comment]
> I updated the initial comment.

Thanks that is much more helpful and I get a real feel for the changes

> There are no new features.

I think the Exception is a new feature.  before we would get output even if not of any use.  So this should be mentioned in the PR imho. 

Yes we have lots of other issues with this module but this feels a good amount for this PR and I think other changes need a full overview of things and are not module specific.

**Comment by ultrabug** [comment]
One of you guys could just hit the merge button ;) done it tho #first ;)

**Pull request merged**
