### PR TITLE
wanda_the_fish: fix the screenshots

### PR DESCRIPTION
**Pull request by lasers**

### CODE REVIEW

**Comment by tobes** [comment]
@lasers congratulations on your new role.  

It would be nice if you could give descriptions for a PR especially if you create one and then merge it.  Personally I would never merge my own commits unless there was a critical bug

eg I think `@author lasers` is now in the wrong place but this should be fixed in the documentation or tests really.

**Comment by lasers** [comment]
@tobes Describing this PR.

I saw `wanda_the_fish` had two `SAMPLE_ERROR` screenshots not long after `wanda_the_fish` was merged. I fixed them and this is right after `flake8` PR got merged too... so I failed flake8 tests with `E722: bare except` exception. Fixed that too... and then saw I can just use `not` instead. What a wild ride. :-)

**Comment by tobes** [comment]
I think this module has a bug in the rendering wanda moves when it feels it shouldn't, but I'm not sure what it is supposed to do so it's not clear if it is a feature?

**Comment by lasers** [comment]
```
|<o,))))>< | step 1 <-- straight -- pushing 
| <o,))))>3| step 2 <-- flap left
|<o,))))>< | step 3 <-- straight again -- pushing
| <o,))))>>| step 4 <-- flap right
```
`{wanda}` won't move without `{motion}`, `{nomotion}`... Spaces on/off repeatedly.

**Pull request merged**
