### PR TITLE
More capabilities and documentation for Pomodoro module

### PR DESCRIPTION
**Pull request by rixx**
In the Pomodoro module, you now can end breaks earlier and pause an ongoing Pomodoro. Those actions are also documented so that one has not to guess how to use the module :)

### CODE REVIEW

**Comment by rixx** [comment]
Oh, I only just saw the merge conflicts and the updates to the pomodoro module. I'll merge it locally and update my changes accordingly

**Comment by rixx** [comment]
Merged and works with sound and everything, although I have to say that the upstream variable `display_bar` makes gibberish appear for me although my font should be able to display those kinds of unicode. Not my department though :)

**Comment by FedericoCeratto** [comment]
Am I missing something ? It was already possible to end a break at any time with the central mouse key.
Regarding pausing a Pomodoro... well, in theory it goes against the idea of pomodoros, but that's arguable :)

**Comment by rixx** [comment]
But the central mouse button would reset everything, if you'd choose to end your third break early, you'd start with your first break after the next Pomodoro.

About pausing … dunno, I sometimes like to use it for bathroom breaks but if you don't want to include it, I understand :)

**Comment by ultrabug** [comment]
@rixx : I don't use it so my opinion is of little value that's why I took the liberty to ping @FedericoCeratto 

I don't see a problem in allowing a left click to pause a running pomodoro even tho it's not really meant to be... after all, rules are meant to be bent ;)

**Comment by rixx** [comment]
Both of you just decide, I'm totally finde with having my own fork there, too ;)

**Comment by FedericoCeratto** [comment]
@rixx: oh I get it, +1 for merging then.
Maybe later that self.run could be removed to have a simple state machine based on self.status

**Comment by ultrabug** [comment]
Thanks a lot mates :)

**Pull request merged**
