### PR TITLE
[bluetooth module] hcitool is deprecated (bluez-5.44) so it is better to use the dbus library directly

### PR DESCRIPTION
**Pull request by jmdana**
hcitool is deprecated (bluez-5.44) so it is better to use the dbus library directly

### CODE REVIEW

**Comment by tobes** [comment]
@jmdana thanks for this PR.

My thoughts are,

We should continue to support hcitool if dbus is not available for existing users.

I think we should use `pydbus` rather than `dbus` currently we have a mix of both but we should really be just using one (tbh neither is perfect in my opinion) @ultrabug your view on this would be helpful.

**Comment by jmdana** [comment]
Please keep in mind that `hcitool` will disappear from all distributions so it could be just dead code in the future. It already did from Arch Linux, that's why I made this change.

About `pydbus`, well, I have never used it myself so it will have to be somebody else making the modifications I'm afraid.

Thanks for the great project.

**Comment by lasers** [comment]
@tobes My findings.
* Same author. Everything works okay here P2/P3 except for `DBusException` if `bluetooth.service` isn't running. (Arch). I'm fine w/ accepting this PR (perfect as-is) and I update BT format PR to cover new changes.
* RIP command `hcitool`. Not on Archlinux anymore. Might not be too bad if this PR can go in today (bluetooth.py broken since Feb 28) + revised BT format PR too. Maybe we revisit `python-pydbus` at other time?

Do we want a new version tag so bluetooth.py could work again in `aur/py3status` (stable version)? If yes, may not be bad idea to ask @ultrabug to review through new modules (and i3py3status, i3block, etc) along with new modules/changes?

**Comment by tobes** [comment]
@ultrabug what are your thoughts here?

* seeing as `hcitool` will be going should we support it whilst still there or just drop for dbus?

* are we happy using `dbus` rather than `pydbus` python lib here.  (I'd really like to do something similar to the requests PR #778 and add dbus helpers to py3 to help simplify modules - if we do that then we can probably support either lib)

**Comment by ultrabug** [comment]
I'm happy with this PR as it is.

If hcitool is being cleaned up, there's no reason to keep it imho, py3status users are cool enough to understand ;)

**Comment by ultrabug** [comment]
And yeah, I have no strong feelings against dbus vs pydbus tbh.

As for adding a functionality to Py3 I guess we should start having a thumb's rule like "we can add a global support for something in Py3 when at least N modules use it"

**Comment by ultrabug** [comment]
Thanks again @jmdana !

**Pull request merged**
