### PR TITLE
Arch status module

### PR DESCRIPTION
**Pull request by lost-tourist**
Adds a module which displays the number of pending updates waiting to be applied/installed on an Arch Linux installation.  As Arch is a rolling-update distribution there are frequently many updates released over any 24-hour period so it's convenient for Arch i3-users (and there are many of them!) to have an easy way to see if they should be downloading and installing updates.

### CODE REVIEW

**Comment by ultrabug** [comment]
Thanks a lot @lost-tourist, can you confirm you tested your module with both python 2 and 3 ?

**Comment by lost-tourist** [comment]
Good call.  Arch Linux defaults to Python 3 but it's possible there could be people out there who have stuck with 2 for some reason.  Anyway it wasn't quite working with Python 2 after you prompted me to test it, so there's a new commit about to come in!

**Comment by ultrabug** [comment]
okay @lost-tourist thanks, would you mind trying to make sure your code is flake8 compliant ? (see travis-ci failing there). The `yapf` tool can help you if needed.

**Comment by Andrwe** [comment]
IMHO it would be nice if this module implemented the format option and provide a placeholder for the output of pacman and AUR as users might want to change the text shown in the bar.

This way it would already comply with #98.

**Comment by ultrabug** [comment]
Thanks @Andrwe for pointing #98 out, good call.

And many thanks @lost-tourist for your module contribution :)

Friendly ping to @btall, you might be interested in this (for your home machine ofc) ;)

**Comment by btall** [comment]
Interesting, thx :)

**Pull request merged**
