### PR TITLE
Revert "timewarrior: pass action/id index"

### PR DESCRIPTION
**Pull request by tobes**
Reverts ultrabug/py3status#1517

we are in a code freeze!

### CODE REVIEW

**Comment by lasers** [comment]
Removing buttons to remove functionality that won't be helpful to users.

**Comment by tobes** [comment]
The point is we are in a code freeze - that means that we do not just merge things.  If this was a major bug fix it still should not be merged without full agreement.  Please do not merge anything at the moment.

And really you should not even merge your own PRs

**Comment by tobes** [comment]
> Removing buttons to remove functionality that won't be helpful to users.

If you feel there is a special reason why this should be accepted during the freeze, then that needs discussion on the specific issue.

**Comment by tobes** [comment]
> I wrote this module even although I don't use timew myself.

Well then maybe we should remove it (I'm serious).  Modules should have active users that care about them and understand the real life needs.

Now it may seem that I am over-reacting but it is really important to understand the processes in software development.  Yes this is a volunteer effort, and open source is a great way to learn and get experience, or support projects you use and value.  But we are trying to be a serious project as well as fun and open.  Changes need to be considered and sometimes things are painfully slow, but this is how it is.

Now that there are three people with commit access we have to be even more careful about how we work.  Doing things properly is hard and none of us are perfect but we all need to be trying to improve how we do things.  I understand the appeal of writing new modules\features but they are each a long term commitment and use our limited resources.  Many times what seems like a good solution turns out to be flawed or others see where it can be greatly improved.

We need slow reasoned progress and consolidation at times.  We need high quality PRs and thoughtful discussion.  Not change for the sake of change or new modules just because we can.  Part of the fun is trying new ideas just because we can, but it doesn't mean we need to make them all a PR.  We welcome new contributors, maybe it is there first ever PR to any project, and we should help and encourage them and give some freedoms, but when people are regularly contributing they need to live up to much better standards. 

The process is important because ultimately it has a huge impact on the quality and success of a project.

**Pull request merged**
