### PR TITLE
systemd: add possibility to check user/session systemd unit

### PR DESCRIPTION
**Pull request by cyrinux**
Hi guys,
here a quick improvement for systemd module + black linting

### CODE REVIEW

**Comment by maximbaz** [comment]
Nice and simple improvement, good job! 👍

**Comment by maximbaz** [comment]
Don't agree, first of all there is no third option so boolean just makes sense, but also nobody knows what a `SessionBus` is, however everyone knows about `--user` flag for `systemctl`, so `user` option is more discoverable :)

**Comment by lasers** [comment]
>however, everyone knows about --user flag for systemctl

I thought everyone knows about `--system` / `--session` flag for `gdbus`. :-)

Either way, I have no preference.

**Comment by maximbaz** [comment]
I'm one of those people who doesn't know about `gdbus`... :disappearing:

Thanks for the review, let's get this merged 😉

**Pull request merged**
