### PR TITLE
Prometheus query module.

### PR DESCRIPTION
**Pull request by Wilm0r**
Sorry, I moved this version into a new branch and it looks like silly github's tiny brain doesn't comprehend that and wants a new pull request for it. :-(

So this is a replacement for  Prometheus query module. #1938

### CODE REVIEW

**Comment by Wilm0r** [comment]
Note: The tests will still fail as I've not done the style updates yet, just the simplification.

**Comment by Wilm0r** [comment]
OK, updated. One check still seems to be failing without explaining what it's so grumpy about. Your tests aren't very friendly IMHO, for example there's an "@author in the wrong place" failure that only after reading more carefully actually meant "Your example heading is wrong so I didn't recognise it". And there's no separate "is there an Example: header?" check.

It'd help a lot if the failures weren't 98% repetitive boilerplate...

**Comment by ultrabug** [comment]
Hey @Wilm0r ; thanks!

Running tox shows this
```
==============================
prometheus
==============================
config params not in alphabetical order should be
            Source    Target
    --------------------------------
            server !! color
             query !! format
    query_interval !! join
            format !! query
             units !! query_interval
             color !! server
              join !! units

Attributes not in alphabetical order, should be
            Source    Target
    --------------------------------
            server !! color
             query !! format
            format !! join
             units !! query
             color !! query_interval
              join !! server
    query_interval !! units

`color` default not in docstring add (default 'ok')
`format` default not in docstring add (default '{__v:.0f}')
`join` default not in docstring add (default None)
`query` default not in docstring add (default None)
`query_interval` (default 90) does not match docstring 60
`server` default not in docstring add (default None)
`units` default not in docstring add (default None)
```

Maybe I'm too used to them but they look clear to me.

**Comment by ultrabug** [comment]
@Wilm0r to be specific, this is the diff you need to get this done

```diff
--- /tmp/prometheus.py	2020-09-06 18:12:45.415165280 +0200
+++ py3status/modules/prometheus.py	2020-09-06 18:15:36.099614200 +0200
@@ -5,21 +5,27 @@
 Displays result of a Prometheus query.
 
 Configuration parameters:
-    server: str, URL pointing at your Prometheus(-compatible) server, example:
-        http://prom.int.mydomain.net:9090
-    query: PromQL Query
-    query_interval: Re-query interval in seconds. (default 60)
+    color: Text colour. Supports py3status colour names.
+        Examples: ok, bad, #E9967A
+        (default None)
     format: Formatting of query result. Can refer to all labels from the query
         result. Query value placeholder __v.
+        (default "{__v:.0f}")
+    join: If query returned multiple rows, join them using this string. If you
+        want to show just one, update your query.
+        (default None)
+    query: PromQL Query
+        (default None)
+    query_interval: Re-query interval in seconds. (default 60)
+    server: str, URL pointing at your Prometheus(-compatible) server, example:
+        http://prom.int.mydomain.net:9090
+        (default None)
     units: Dict with py3.format_units arguments, if you want human-readable
         unit formatting. Example: {"unit": "Wh", "si": True}
         If used, __v placeholder will contain formatted output. __n and __u
         will contain number and unit separately if you want to more finely
         control formatting.
-    color: Text colour. Supports py3status colour names.
-        Examples: ok, bad, #E9967A
-    join: If query returned multiple rows, join them using this string. If you
-        want to show just one, update your query.
+        (default None)
 
 Dynamic format placeholders:
     All query result labels are available as format placeholders. The vector
@@ -47,14 +53,13 @@
 
 class Py3status:
     # available configuration parameters
-    server = None
-    query = None
+    color = None
     format = "{__v:.0f}"
-    units = None
-    color = "ok"
     join = None
-
-    query_interval = 90
+    query = None
+    query_interval = 60
+    server = None
+    units = None
 
     def prometheus(self):
         self._rows = []
```

**Comment by ultrabug** [comment]
Hey mate, tested OK here, that's great!

As I'm releasing py3status 3.29 and want your contribution in, I will merge and fix the CI myself :)

Thanks again for your patience and contribution @Wilm0r

**Comment by Wilm0r** [comment]
> Maybe I'm too used to them but they look clear to me.

Hrm, yes that looks much clearer than the parts I paid attention to (which I can't find anymore now, hmpf)

Thanks for the cleanup and merge! :-D

**Pull request merged**
