### PR TITLE
Detect players starting after py3status

### PR DESCRIPTION
**Pull request by ritze**
The mpris module catches all player which are started after the py3status instance (see Bug #595)

This fix doesn't work with all players, e.g. bomi!

### CODE REVIEW

**Comment by ritze** [comment]
I think bomi starts not fast enough and we got a race condition. We got an exception when accessing on the dbus in __add_player()_: `self._dbus.get('org.mpris.MediaPlayer2.bomi', SERVICE_BUS_URL)`

Sometimes it works with bomi. With other players like vlc this always works perfectly.

**Comment by tobes** [comment]
@raspbeguy does this fix #595 for you/

**Comment by ultrabug** [comment]
Thanks @ritze , waiting for @raspbeguy to respond

**Comment by raspbeguy** [comment]
@ultrabug @tobes really sorry for the delay, I'm very busy right now. Yes, it fixed the problem, thanks @ritze

**Comment by ultrabug** [comment]
Thanks a lot !

**Pull request merged**
