### PR TITLE
i3status missing better reporting

### PR DESCRIPTION
**Pull request by tobes**
from issue #948 this now reports a better error to the user when i3status is missing.

It is very simplistic we could do a `which i3status` to confirm but that feels overkill for now

Better logging of i3status spawning (when it has)

removed some unneeded bits from mocking

### CODE REVIEW

**Comment by ultrabug** [comment]
Thanks, I'm just asking myself if we couldn't use the `check_command` helper to make sure about i3status presence ?

Also, I'm wondering if this check could be done ONLY if i3status modules are used ?

**Comment by tobes** [comment]
>  I'm just asking myself if we couldn't use the check_command helper

In many ways this might be good.  I think it will need a bit of code movement though.  We only try to start i3status if we need to so we wouldn't check otherwise.

**Comment by ultrabug** [comment]
Okay, I'd like ACK from @Cypher1 before merging this. Cheers!

**Comment by Cypher1** [comment]
Looks good to me. Thanks

**Pull request merged**
