### PR TITLE
formatter: return falsey properly

### LINKED ISSUE #1095: Formatting returns empty when closing with a False or None placeholder
Formatting returns empty when closing with a `False` or `None` placeholder.
```diff
diff --git a/py3status/modules/static_string.py b/py3status/modules/static_string.py
index dbcec8c6..593b3740 100644
--- a/py3status/modules/static_string.py
+++ b/py3status/modules/static_string.py
@@ -18,10 +18,17 @@ class Py3status:
     # available configuration parameters
     format = 'Hello, world!'
 
+    # format = 'A, B, C // {true}'    # IS OK     | A, B, C // True
+    # format = 'A, B, C // {false}'   # IS NOT OK |
+    # format = 'A, B, C // {none}'    # IS NOT OK |
+    # format = 'A, B, C // {false} '  # IS OK     | A, B, C // False
+    # format = 'A, B, C // {none} '   # IS OK     | A, B, C // None
+
     def static_string(self):
+        new_dict = {'true': True, 'false': False, 'none': None}
         return {
             'cached_until': self.py3.CACHE_FOREVER,
-            'full_text': self.py3.safe_format(self.format),
+            'full_text': self.py3.safe_format(self.format, new_dict),
         }
```

### PR DESCRIPTION
**Pull request by lasers**
Hi. I'm not familiar with the formatter code. This closes #1095 for me.
This is likely the reason why adding something at end makes it just work.
```python
            elif (self.parent is None and
                    ((not self.next_block and enough)or self.base_block)):
                valid = True
```
Without an `if` in there, the formatter think it is a `[{placeholder}]`.

### CODE REVIEW

**Comment by tobes** [comment]
IMHO this breaks the formatter, because the original tests fail.

With #1095 I do not actually understand what the issue is that you are describing.  Maybe if I understood that then this would make more sense.

Now maybe the current behaviour of the formatter is incorrect.  Then we should have a clear discussion about  that and how to improve it.

**Comment by lasers** [comment]
Brief explanation. Apply the git patch. I included some examples. Test each as you go.
```
+    # format = 'A, B, C // {true}'    # IS OK     | A, B, C // True
+    # format = 'A, B, C // {false}'   # IS NOT OK |
+    # format = 'A, B, C // {none}'    # IS NOT OK |
+    # format = 'A, B, C // {false} '  # IS OK     | A, B, C // False
+    # format = 'A, B, C // {none} '   # IS OK     | A, B, C // None
```

Different examples.
* `'Repeat: {repeat}'` -- Expected -- `'Repeat: False'` -- Got `''`.
* `'Hi. Long string. {none}'` -- Expected -- `Hi. Long string. None` -- Got `''`.

First, I never knew about this `{false}` --> `''` and `{none}` --> `''` until I made a pull request... and failed the tests here. Color me surprised. I think few tests may be wrong (fixed now) because it prints `True` on `{true}` and just disappear on `{false}`, `{none}`.

**Comment by tobes** [comment]
> First, I never knew about this {false} --> '' and {none} --> '' until I made a pull request

That is intentional.  Now whether it is a good idea is a different issue. 

The main issue is that the formatter still lacks documentation.

**Comment by lasers** [comment]
>That is intentional. Now whether it is a good idea is a different issue.

I amended two tests in this commit. Check them out and decide.

And we can have many `{False}`, `{None}` as we want... and still get nothing.
```
diff --git a/py3status/modules/static_string.py b/py3status/modules/static_string.py
index dbcec8c6..e15b30a4 100644
--- a/py3status/modules/static_string.py
+++ b/py3status/modules/static_string.py
@@ -16,12 +16,15 @@ class Py3status:
     """
     """
     # available configuration parameters
-    format = 'Hello, world!'
+    format = ' '.join(['{false} {none}' for x in range(5)])
+    # format += ' '
+    # format += ' {true}'
 
     def static_string(self):
         return {
             'cached_until': self.py3.CACHE_FOREVER,
-            'full_text': self.py3.safe_format(self.format),
+            'full_text': self.py3.safe_format(
+                self.format, {'true': True, 'false': False, 'none': None}),
         }
```
```
$ python3 static_string.py
[]
```
```
$ python3 static_string.py    # add space
{'full_text': 'False None False None False None False None False None ', 'cached_until': -1}
```
```
$ python3 static_string.py    # add {true}
{'cached_until': -1, 'full_text': 'False None False None False None False None False None True'}
```
It's been said many times that the truth will set you free. I guess it was really true.

**Comment by ultrabug** [comment]
@tobes bump plz?

**Comment by ultrabug** [comment]
Ok for this one, `no` stuff is consistent with how yes was already handled

**Pull request merged**
