### PR TITLE
implemented format & color #98

### PR DESCRIPTION
**Pull request by Andrwe**
- implemented format option
- deprecated format_on
- added options color and color_off

### CODE REVIEW

**Comment by ultrabug** [comment]
There are other modules with format_up / down configuration which do seem in line with i3status philosophy. I'm not sure I see why forcing a single `format` option while retaining its `down` counterpart is better mate ?

Colour config LGTM tho.

**Comment by Andrwe** [comment]
I just found #98 the other day I started working on dpms to implement this improvement as I like standardized code.
I can revert the format code and just implement the color stuff if you like.

**Comment by ultrabug** [comment]
Yes @Andrwe please. Because in this case, I think the current format_on/off does not break #98.

**Comment by Andrwe** [comment]
removed format option and cleaned code

**Comment by ultrabug** [comment]
erm sorry @Andrwe but it seems that you rebased the whole thing here so look at the files changed please, it includes even your spotify module stuff etc :(

Mind fixing all this please ?

**Comment by Andrwe** [comment]
Oh, damn it, sorry I'll fix this.

**Comment by Andrwe** [comment]
I'm closing this PR in favor of #189

**Pull request closed without merging**
