### PR TITLE
py3status-command: control py3status from cli/i3

### PR DESCRIPTION
**Pull request by tobes**
As requested in #588 and #745 and also required for #481 (though requires further code)

Command line fun for all the family

```
# refresh all modules
py3status-command refresh_all

# refresh any wifi modules
py3status-command refresh wifi

# refresh wifi module instance eth0
py3status-command refresh "wifi eth0"

# refresh any wifi or whatismyip modules
py3status-command refresh wifi whatismyip

# send a click event to the whatismyip module (button 1)
py3status-command click whatismyip

# send a click event to the backlight module with button 5
py3status-command click 5 backlight
```

Calling commands from i3

```
# bind key to clicking a module
bindsym $mod+x exec py3status-command click whatismyip

# update volume_status when volume keys used
bindsym XF86AudioRaiseVolume  exec "amixer -q sset Master 5%+ unmute; py3status-command refresh volume_status"
bindsym XF86AudioLowerVolume  exec "amixer -q sset Master 5%- unmute; py3status-command refresh volume_status"
bindsym XF86AudioMute         exec "amixer -q sset Master toggle; py3status-command refresh volume_status"
```

### CODE REVIEW

**Comment by lasers** [comment]
My findings...

`py3status-command --version`... No version. Not fun for my family.

`py3status-command` is too long imho. Can we use something like `i3-msg`?
`py3status-cmd`? `py3-msg`? `py3-cmd`?

Thought: Too long for i3/config and/or users shouldn't type things out that long.
I like `py3-msg`. It reminds me of something. Can't put my finger on it.

Should we get an alias for `click --button 4`? `py3-msg scrollup`
Should we get an alias for `click --button 5`?  `py3-msg scrolldown`


Likely a known issue. Unable to specify which bar/monitor out of multiple bars/monitors. This is just me noticing an issue out of thin air. This is pretty much non-issue anyway.

Can we see if we can avoid `--button`? `py3-msg click 4 group uptime` would be much better than `py3-msg click --button 4 group uptime` and if no number, assume `1`.

Do we want `refresh` or `reload`? I asked because i3 uses `reload` so should we follow that somehow or just go with `refresh`? `reload` is memory muscle for `i3-msg`.
Now I ponder about `button_reload` vs `button_refresh`.

Thoughts about using other aliases such as leftclick, rightclick, middleclick? The cavet is that we add enough aliases to support common comfort mouse. The rest could be left to numbers.

Make it smart enough to avoid "click" if possible? Straight to module... kinda like how sending things to `i3` would pass them along to `i3-msg`. We do that for `py3status` or just `py3-msg`... Detect module name, assume `click`? 
`py3-msg reload whatismyip` (reload) and `py3-msg whatismyip` (click). 

This is good. I can dismiss bluetooth exception, scroll down groups simultaneously.... and starting both Pomodoro at same time (one on bottom, one on top), etc. All neat.

Last question: How to restart a dead module presumably from... different branches and/or switching branches... without restarting i3bar? I can't do that.

P.S. I caught myself doing `reload_all` for the last question. Muscle memory. 😨

**Comment by tobes** [comment]
> py3status-command --version... No version. Not fun for my family. Refund, please.

fixed, no refunds available.  your family is having fun!

> py3status-command is too long imho. Can we use something like i3-msg?
> py3status-cmd? py3-msg? py3-cmd?

I first had `py3status-cli`  but we could do `py3-msg`.  For now I keep `py3status-command` but I'm up for changing this.

> Should we get an alias for click --button 4? py3-msg scrollup

in theory yes but let's get the standard way sorted first.

> Likely a known issue. Unable to specify which bar/monitor out of multiple bars/monitors. This is just me noticing an issue out of thin air. This is pretty much non-issue.

By design all bars get the message and the complications involved in just sending to one are hard.  How do we know which socket is which bar? Apart from `refresh_all` this is a non-issue imho.

> Can we see if we can avoid --button? py3-msg click 4 group uptime would be much better than py3-msg click --button 4 group uptime and if no number, assume 1.

Yes this is much better.  I've changed to use this.

> Do we want refresh or reload? I asked because i3 uses reload so should we follow that somehow or just go with refresh? reload is memory muscle for i3-msg.
Now I ponder about button_reload vs button_refresh.

this mirrors current options https://py3status.readthedocs.io/en/3.5/configuration.html#special-on-click-commands

> Thoughts about using other aliases such as leftclick, rightclick, middleclick? The cavet is that we add enough aliases to support common comfort mouse. The rest could be left to numbers.

hmm, maybe at some point in the future but we use numbers (only) everywhere at the moment

> Make it smart enough to avoid "click" "reload" if possible? Straight to module... kinda like how sending things to i3 would pass them along to i3-msg. We do that for py3status or just py3-msg... Detect module name, assume click reload?
>
> py3-msg whatismyip

The thing is the module does most of the work so we cannot guarantee what it will do, so this could cause refreshing twice say.  Again maybe in the future.

> This is good. I can dismiss bluetooth exception, scroll down groups simultaneously.... and starting both Pomodoro at same time (one on bottom, one on top), etc. All neat.

You see family day out could not be better. 

> Last question: How to restart a dead module presumably from... different branches and/or switching branches... without restarting i3bar? I can't do that.

Well once the branch learns this then it will all work but basically py3status is listening for messages.  Once we have the basic functionality we can start adding new features eg hide show modules, restarting/add/remove on-the-fly etc (these all need work in core though so not yet available but we think of the future)

> P.S. I caught myself trying reload_all for the last question. Muscle memory. 😨
> (Thoughts, opinions, and feedback all mine. Dismiss them or not. W/e).

Some very good points and ideas, thanks for the review

**Comment by lasers** [comment]
>By design all bars get the message and the complications involved in just sending to one are hard. How do we know which socket is which bar? Apart from refresh_all this is a non-issue imho.

Not for `xrandr` issue, I think... https://github.com/ultrabug/py3status/pull/242. Need to figure out how to send updates to only one bar... Maybe we detect where mouse is, so we work with all bars from that monitor.

What's the chance that the users will have same module on both top/bottom bars through all three monitors? If assumed yes on high chance... then... if we get two bars, we just send to first number in the list. Idk.

**Comment by tobes** [comment]
> Not for xrandr

#242 was too long (and closed) so I didn't read it.  But not related imho.

Actually this PR paves the way for `xrandr` to be happier.  Currently `xrandr` does `killall -s USR1 py3status` which is completely insane. and refreshes all bars (which is completely unwanted) all we really need is a `repaint` that just refreshes the output.  This of course needs several things.

* `repaint` functionality added to core - trivial

* modules to be able to trigger 'commands' via `Py3` - pretty trivial

* `xrandr` to use new functionality once available - trivial

The which screen is a bar on/which bar is which etc are non-trivial issues and I don't think they buy us any real benefit.  The command does not really have a concept of specific bars.  We just shout our command to any we find and let them get on with stuff.

**Comment by ultrabug** [comment]
This is great thanks a lot :)

I think I'd prefer the command to be shorter indeed, in my fantasy world I would choose between

- py3status (well, why not use the same name ? we already have a CLI of sorts using this command)
- py3 (simple, efficient)
- py3-cmd (in line with i3)

I like the idea of aliases for click buttons, I'd like them all 👍 

I would not add a `refresh_all` option but instead stay consistent with the `refresh` one and add a reserved `all` keyword to mean *all the modules*

**Comment by tobes** [comment]
update:

we now are called `py3-cmd`

named buttons
```
    # send a click event to the whatismyip module (button 1)
    py3-cmd leftclick whatismyip

    # send a click event to the backlight module with button 5
    py3-cmd scrolldown backlight
```

`refresh_all` replaced now use `py3-cmd refresh all`

docs updated to reflect changes

**Comment by ultrabug** [comment]
Alright, this is an awesome move forward, thanks a lot!

**Comment by ultrabug** [comment]
NOTE: we'll have to figure out how to remove/recycle the old CLI commands

**Comment by johnp** [comment]
Is it expected for `py3-cmd refresh volume_status` to take longer to update the bar in comparison to `killall -USR1 py3status`? I just wanted to update my `XF86Audio(Raise|Lower)Volume` bindings and they are instant with the latter, but take about a second or so with the former.

**Comment by tobes** [comment]
`py3-cmd refresh volume_status` should be fairly speedy and uses less resources.  The problem is the startup time.  I'll see what can be done to improve things.

on my system
```
time py3-cmd click 2 volume_status

real	0m0.328s
user	0m0.256s
sys	0m0.040s
```

**Comment by johnp** [comment]
It's even worse for me:

    $ time py3-cmd refresh volume_status

    real	0m0.699s
    user	0m0.740s
    sys	0m0.000s

**Comment by lasers** [comment]
Same.
```
lasers~ $ py3-cmd refresh volume_status                                                            
                                                                                                                      
real    0m0.915s
user    0m0.887s
sys     0m0.027s
```

**Comment by tobes** [comment]
ok I'll look at what we can do to improve things.  What python versions are you running under.  I've also worked out the `--version` is broken at the moment.

**Comment by johnp** [comment]
Python 3.6.1 (Arch Linux)

**Comment by tobes** [comment]
ok so the problem is that setup utils is a pile of crap and spends all the time looking at the file system rather than just running the script.  I'll do a bit more digging around but realistically we should be able to run the script in < 100ms which is good enough.

**Pull request merged**
