### PR TITLE
[backlight] Allow slower value change after a threshold

### PR DESCRIPTION
**Pull request by maximbaz**
Until I learned about `py3-cmd` I was using my own script for changing brightness. I'm missing one feature in the py3status'es module that I had in my script:

I usually use a large `delta` value (`10`), but my screen is very bright and in the evening I want to fine-tune the brightness and use some value like `2` or `3`. With the constant `delta` it is impossible, it jumps between `10` and `1`.

This change introduces a `brightness_slow` parameter (please suggest a better name), which is a threshold, after which the value is being changed by a minimally possible value instead of the `delta` (I know the hardcoded value of `1` might change in #1077).

My favorite values:

```
backlight {
  brightness_delta = 10
  brightness_slow = 10
}
```

How this looks:

py3status_backlight

### CODE REVIEW

**Comment by lasers** [comment]
`brightness_tune` ?
`brightness_tweak` ?

Also, it may be possible to have more control (anywhere) via this method.
```
backlight {
    on_click 1 'exec ~/set-brightness.sh dec 1; exec py3-cmd refresh backlight'
    on_click 3 'exec ~/set-brightness.sh inc 1; exec py3-cmd refresh backlight'
}
```

**Comment by maximbaz** [comment]
Hm, interesting, maybe with a `_treshold` suffix, e.g. `brightness_tune_treshold`?

I see what you suggest, but I don't want to keep my script around, since py3status can change the value for me, let it do this 🙂

**Comment by tobes** [comment]
I think this is a really interesting problem and it fits in with the problems @lasers has had with modules and mouse scrolling.  I think these are related in a wierd sort of way.

Currently we do the onclick event and refresh the module and I think this ends up giving us latency issues that @lasers has been trying to fix with his is scrolling logic.  I think this is a real problem but also one we can solve in core rather than in each module but it is not that dissimilar in approach I think.

If we can solve that latency issue then I think we could maybe look at some sort of 'acceleration' I think this would be useful in things like volume control.  This is all a bit dreamy I'll admit

**Comment by maximbaz** [comment]
I like the idea to have some sort of 'acceleration', and yes I agree that it would totally fulfill what I'm doing in this PR. I haven't been following all PRs in this project, what is the current status with fixing the latency issues? Do you want to hold this PR until it is proven that acceleration can or cannot be implemented, or do you want to proceed with it?

**Comment by tobes** [comment]
The aim is to get 3.7 out in the next week or so, mainly due to the possible memory leak issue #1074.

Realistically we have a large backlog of issues/PRs that would be good to get closed/merged etc.  There is a problem around resources especially both @ultrabug and I have not had as much time as we would like.  We both have some large structural changes that we want to see in the projects code to reduce the code complexity

* reducing the number of methods modules are allowed to have to one, historically they can have as many as they want.

* separating the cli parsing from the actual running of py3status - so we can test modules via the cli something like `py3status test <module>`

* improving the docstring parsing for modules and sorting the defaults so they don't need to be done twice

* unpicking things more so we can use greenlets etc

* better/simpler integration with dbus which will help some modules be more responsive

* auto updating of user configs for deprecated stuff (if the user agrees)

* nicer click events (module commands)

So yeah in an ideal world I'd say wait, but if it's important to you then I think we should look at it as a short/medium term fix.  From my point of view, you are a long term user / contributor so I'm inclined to merge it.  I'm going to add it to the 3.7 window and I'll talk to @ultrabug I suspect he may feel the same regarding keeping our core users happy.

**Comment by lasers** [comment]
@tobes I think we should consider that latency issue non-trivial so we don't have to worry about it. I only ran into it because I was fiercely scrolling against the song with a low number. The solution was to use a nice and reasonably large delta number.

(@ all)
If we're adding this config, we could make it a bit more well-rounded by adding one more config for the opposite endpoint. `100, 99, 98, 97`... `85 (delta) 5` ... `4, 3, 2, 1`. If not, at least use a name that can reference to something beginning.

**Comment by maximbaz** [comment]
@tobes thanks for such a detailed answer 🙂 I also wanted to ask, what is the strategy with the deprecated options? At some point options become deprecated, but are they ever getting removed from the codebase, e.g. after two consequent releases? It is of course nice to see PRs merged, but I don't really want to introduce a configuration that will stay forever in the codebase, that we know is going to be deprecated soon™️ - from that point of view I'd prefer to wait.

@lasers as far as I understand it would be impossible to implement acceleration without solving latency issue first, and acceleration is something that could deprecate this feature - i.e. I could set my delta to `1`, but if I fiercely scroll / hold <kbd>BrightnessUp</kbd> keyboard button (that is issuing `py3-cmd` calls) I am still able to go reasonably fast from value `1` to value `100`. So, still an issue, using large delta is not desired in this case 🙂

I've never experienced a need for fine-tuning `97, 98, 99` brightness levels, only low levels matter to me, agree on reflecting that in the configuration name to make things clear.

**Comment by tobes** [comment]
> I also wanted to ask, what is the strategy with the deprecated options? At some point options become deprecated, but are they ever getting removed from the codebase, e.g. after two consequent releases? 

Currently there is no strategy, the user will only know if they look in the logs.  But notifying the user just causes them pain.  The proposed solution is.  We notify the user that their config needs updating due to config changes (via i3-nagbar) they can then click either `I don't care` or `fix my config`.  But for this we need to be able to fix the config.  This means we need to do a much better job of parsing the config, so we know where the setting is so that we can fix it.  We could just dump a fresh config but then they would lose any comments etc that they had which is unacceptable.

So that is what we are aiming for but till we get that we'll just carry the deprecations.  I've done some of the work but it needs another burst and is quite a hard problem to do seamlessly.  Once we have a parser that remembers where in the file it got things from then the updating the config should be fairly simple.  Once we have that then we can look at when we remove the deprications.

Another option might actually be to start to move the deprecations out of the modules themselves so that the modules become clean again even if the deprecations stay somewhere else in the code base.  But yeah we should be looking to remove them or at least from the modules.

**Comment by lasers** [comment]
>I've never experienced a need for fine-tuning 97, 98, 99 brightness levels, only low levels matter to me.

It's more about fixing things up / removing hardcoded / exposing the missing options / etc. For instance, `backlight` does not have `brightness_maximum`. Now I wonder if we should at least expose that... 
* Reason 1: Extra minute(s) on the battery life.
* Reason 2: Slightly dimmed screen, barely noticeable. Efficient.
* Reason 3: Less eyestrain?

> brightness_low_tune_threshold

Not sure if we even need `brightness_` here even if makes many nice config names in `backlight`. Maybe `mininal_tune` now and we rename others later?

* ~brightness_delta~ delta
* ~brightness_initial~ initial 
* ~brightness_minimal~ minimal
* (Possible) maximum
* ~brightness_low_tune_threshold~ minimal_tune 
* (Possible) maximum_tune

**Comment by tobes** [comment]
@ultrabug I think we should merge this and call it a day and release 3.7

My thinking is.

* 3.7 is overdue and we have been struggling to make time - things will get worse in december due to the holidays coming up.

* Most merged PRs have had time to settle in.

* This patch is fairly trivial and although maybe not the best long term solution it meets the need of a long term contributor to the project.

* I think #1137 might benefit from being in master for a while before release so it sees some action but I don't hugely object it you want to merge it now.

The other option is just to release what we have now and then just merge these into the next release as I think both @lasers and @maximbaz run master so would get the benefits straight off.

**Comment by maximbaz** [comment]
I do run the master branch, so I'm perfectly OK with merging this after the release cut-off.

**Comment by lasers** [comment]
* Address `xrandr-rotate` pull requests too because not everything got merged in... Otherwise, existing users will experience `hide_if_disconnected` bug due to active/all monitors.
* #1156 is a trivial bugfix. Can be tested easily (offline) then maybe merged too.

**Comment by ultrabug** [comment]
I agree, thanks a lot guys for the energy you put into this! 3.7 milestone is done.

To the release now!

**Comment by lasers** [comment]
xrandr first!
=

**Pull request merged**
