### PR TITLE
add mellowplayer module, fork from spotify module

### PR DESCRIPTION
**Pull request by cyrinux**
Hi,

Just a little module, forked from spotify, to display track infos from service supported by mellowplayer.
Infos depend on the service.

### CODE REVIEW

**Comment by lasers** [comment]
The (only real) change is:
```
<             self.__bus = bus.get_object('org.mpris.MediaPlayer2.spotify',
---
>             self.__bus = bus.get_object('org.mpris.MediaPlayer2.MellowPlayer',
```

This may already work in `mpris`. Nice if you could confirm this. With clicks and everything.

I think would be better to add a fix in `spotify` to support `mellowplayer` too, but at a glance, it seems that `mellowplayer` is much more than `spotify` as it also supports other streaming music sites too... and is open source.

Maybe `mpris` works okay with `spotify` too. If `mpris` works okay with `mellowplayer`,
then the real fix may be just to fix `mpris` some more as it would not always behave correctly with vlc, gmpdp, clementine... and possibly spotify/mellowplayer next.

@tobes For fun, I leak I have `newmodule-rhythmbox` branch, but may be absolutely unnecessary due to `mpris`. Anyhow, what do you want to do with this `mellowplayer` PR?

**Comment by tobes** [comment]
@lasers I think if it works with mpris then that is the way to go.  Having one really solid module is where I think we want to be.  Unfortunately mpris is quite complicated but if it works it is my preferred option.  Hopefully we can simplify it over time and get it super stable.

It is similar to the updates issue and having lots of modules becomes hard to maintain, especially if they lack users.  Mpris relies on dbus, which it seems that this module needs that too so the requirement makes no difference.

**Comment by cyrinux** [comment]
Hi,
I would prefer i global mpris module too. I have recheck, and I have no "{time}' info with service I have tested. 
- I can't get working spotify service for the moment on my archlinux, so I don't know if "time" works only only with spotify service?
- Youtube service display any informations.
If a global module is done, how do you think manage several player running in the same time?

**Comment by tobes** [comment]
details of the mpris module are here

https://py3status.readthedocs.io/en/latest/modules.html#mpris

you can specify the player(s) that an instance prioritieses, does it meet your needs?

**Comment by cyrinux** [comment]
Oh thanks @tobes, I wil try this, yes I think it is what i want (on the
paper) ;)

**Comment by cyrinux** [comment]
Hi,
Could you say me how I can help you with my mpris problem?
Started it with 

 /usr/bin/python /usr/bin/py3status --dbus-notify --gevent --debug
{"version": 1, "click_events": true, "stop_signal": 20}
[[]
then it is stuck.
If I control+c it,
 ^C,[{"name": "path_exists", "instance": "PIA", "color": "#fb4934", "markup": "none", "full_text": "PIA: no"}]
...
I start to have all my other modules running but not mpris
Any idea?

**Comment by lasers** [comment]
See if `mpris` will work without `--gevent`. I can't try `mpris` because I don't have `pydbus` available.

If `mpris` is still broken without `--gevent`, then maybe some other commits between py3status versions might had broken `mpris` (again) so we should see if that was the problem here. Otherwise, I have no idea where to start looking... Also, `mpris` might be a hard module to fix too.

**Comment by cyrinux** [comment]
@lasers I confirm this is working without gevents. What should I do? Do you need more information? Thanks for your help

**Comment by lasers** [comment]
Don't use `--gevent` for now... Or try and solve this.

`py3status` added `gevent` not long ago... Last month or so.

Initially, there was a problem with `subprocess` https://github.com/ultrabug/py3status/issues/1209. I don't see `mpris` using any `subprocess` or `Popen` so I assume the problem is related to threading/Thread this time.
* https://github.com/gevent/gevent/blob/master/src/gevent/thread.py
* https://github.com/gevent/gevent/blob/master/src/gevent/threading.py

Does `mellowplayer`/`spotify` work fully with `mpris`? With clicks and everything?

**Comment by cyrinux** [comment]
Mellowplayer seems to work well without gevent. I have test tidal and
soundcloud service inside mellowplayer, no problem, I can play/pause,
next/prev

**Comment by lasers** [comment]
@cyrinux Is it okay for you to close this in favor of working `mpris`?

**Comment by cyrinux** [comment]
Yes @lasers, I will be back if necessary ;)

**Pull request closed without merging**
