### PR TITLE
add new module: dexcom

### PR DESCRIPTION
**Pull request by lasers**
Hi, I made a new module `dexcom`.

Tested OK in the term. Not tested on the bar.

### CODE REVIEW

**Comment by ultrabug** [comment]
Thanks @lasers , but do you plan to use it? without a user base, a module is doomed to deprecation and I won't be able to handle it myself tbh

**Comment by lasers** [comment]
@ultrabug, I don't plan to use it as I'm on KDE, but I think this module would be useful for users with dead pancreas.

**Comment by ultrabug** [comment]
KDE? what happened mate? :scream:

**Comment by lasers** [comment]
Tried NixOS. Liked it. Its default DE grew on me too. I still help out with py3status.

Give it few days. Find some testers.  Idk. I could work on this some more... to add things like low_{urgent,alert},  high_{urgent,alert}, and up/down change.

**Comment by lasers** [comment]
@ultrabug I think I'm not trying to enhance this module some more, but it's already usable.
```shell
Dexcom 80 mg/dL → 7:15 PM # sample output

```

**Comment by ultrabug** [comment]
I'll let the module in because it's you but I dislike modules without user base.

To you potential user of the future : please make yourself known if you do use this!

**Pull request merged**
