### PR TITLE
Py3.format_placeholders() helper

### PR DESCRIPTION
**Pull request by tobes**
This adds a helper to get all the placeholders from a format_string.

It is helpful for a number of potential modules.

### CODE REVIEW

**Comment by ultrabug** [comment]
The method name is not clear to me, shouldn't it be named `get_placeholders_list` or something instead ?

**Comment by tobes** [comment]
is `format_list_placeholders()` acceptable? If not I'll go with your suggestion.

**Comment by ultrabug** [comment]
Well I may be stubborn but this looks like a getter function to me, so I'd stick with my previous statement sorry

**Comment by tobes** [comment]
stubborn wins :)

**Pull request merged**
