### PR TITLE
external_script module: add support for colors

### PR DESCRIPTION
**Pull request by enguerrand**
Read a color code from the second line of output.

If the external script has only one line of output the behavior
is unchanged.

### CODE REVIEW

**Comment by tobes** [comment]
@enguerrand thanks for this PR.  I'm slightly worried by the change in behaviour.  A script that worked previously might no longer.  So maybe it would be better to add an option for this.

The behaviour also seems similar to that of https://github.com/ultrabug/py3status/pull/687 although that would need some adaptation of your script (colour is 3rd line) and is over-complicating things.

**Comment by enguerrand** [comment]
@tobes The only scenario I can think of right now where a previously working script would now stop working is if that script gave a second line of output which isn't a valid hex color code. (Or am I overlooking something?).
I am happy to build in a check for that and make it fall back to the previous behavior (no color) if the 2nd line is not a valid color code. 
Let me know what you think.

**Comment by tobes** [comment]
> I am happy to build in a check for that and make it fall back to the previous behavior (no color) if the 2nd line is not a valid color code.

that seems a good solution and also no extra user config params to confuse

**Comment by enguerrand** [comment]
There it is. Not a 100% secure check for a valid hex color, but should be good enough to avoid breaking old scripts?

**Comment by tobes** [comment]
@enguerrand I think this is good enough and a nice feature.  Thanks

**Comment by enguerrand** [comment]
@tobes You are welcome & thanks for merging it!

**Pull request merged**
