### PR TITLE
bluetooth: reinitialize dbus

### PR DESCRIPTION
**Pull request by lasers**
I wonder if it is a race condition. Untested. Trying to catch this exception.

Closes https://github.com/ultrabug/py3status/issues/2218.

### CODE REVIEW

**Comment by lasers** [comment]
SERVICE_UNKNOWN
* https://lazka.github.io/pgi-docs/Gio-2.0/enums.html#Gio.DBusError.SERVICE_UNKNOWN 

FOUND IT -- Something like this.
* https://pygobject.readthedocs.io/en/latest/guide/api/error_handling.html

**Comment by syyyr** [comment]
Okay, your patch almost works, but it needed this patch:
```
diff --git a/py3status/modules/bluetooth.py b/py3status/modules/bluetooth.py
index cb9a8638..a7b36371 100644
--- a/py3status/modules/bluetooth.py
+++ b/py3status/modules/bluetooth.py
@@ -130,7 +130,7 @@ class Py3status:
                 self.py3.log(" --- SUCCESS ---")
             except GLib.Error as err:
                 self.py3.log(" --- FAILED ---")
-                if err.matches(Gio.io_error_quark(), Gio.DBusError.SERVICE_UNKNOWN):
+                if err.matches(Gio.dbus_error_quark(), Gio.DBusError.SERVICE_UNKNOWN):
                     self._dbus_init()
                     self.py3.log(" --- MATCHED ---")
                 else:
```
If we want to match the dbus error, we must get the dbus error quark instead of io error quark

**Comment by syyyr** [comment]
Just FYI, as of now (92b76c66a78d601161eeacd4bd1b414363693c9d), the PR works for me.

**Comment by lasers** [comment]
OK. The next one should be same. I think retrying loop might be unnecessary since trying it once should be enough... and if it failed for some reason, giving it some time for the next one (10s) should be more than enough. I'm guessing the `post_config_hook` method isn't covered in py3status error retries.

**Comment by syyyr** [comment]
Hi, I haven't had any problems for the past week, so I think the patch is correct.

**Comment by ultrabug** [comment]
Thanks!

**Pull request merged**
