### PR TITLE
github: remove the trailing slashes

### PR DESCRIPTION
**Pull request by lasers**
I think we don't like slashes. This should allow users to copy and paste URL into a config and not having to worry about the trailing slash. If you prefer `rstrip`, let me know. I think `strip` may be a slightly faster (not that it matter....)

### CODE REVIEW

**Comment by tobes** [comment]
what I'd really prefer is a comment explaining why we are doing it so that in future it is nice and clear why we are doing this

**Comment by lasers** [comment]
Comment included. Go.

**Comment by tobes** [comment]
@lasers if you want to rebase this then we can see if travis is still in the psycho ward

**Comment by tobes** [comment]
Cool, sometimes the small things are the best

**Pull request merged**
