### PR TITLE
Tweak battery_level

### PR DESCRIPTION
**Pull request by ben-e-whitney**
Changes explained in the commit messages. They fall into the following categories:
* add new parameters for controlling how the battery level is decided to be bad, degraded, or good
* tweak existing code to make it clearer (to me, at least) in ways that do not change functionality
* tweak existing code in ways that (slightly) change functionality!

### CODE REVIEW

**Comment by ultrabug** [comment]
Hi @ben-e-whitney

Thanks a lot for your contribution which I didn't review fully yet. Just a quick note while I do : please make sure you do not modify the default behaviour of the module, so I can merge this quickly :)

Cheers

**Comment by ben-e-whitney** [comment]
Yes, of course. No more changes to the default in future pull requests. Thank you! :)

**Comment by ultrabug** [comment]
@ben-e-whitney no I meant that please change the current PR so that `tweak existing code in ways that (slightly) change functionality!` is not there :)

I mean, you acknowledge that the current PR changes the default right ?

**Comment by ben-e-whitney** [comment]
Oh, yes, I would be happy to change the PR. I'm a little busy right now, so it might be a week or two. I will make another comment here when I've made the changes.

**Comment by ultrabug** [comment]
ping @ben-e-whitney as per PR #152 would you please rebase and add back your ideas with respect to default behaviour ? Thanks again !

**Comment by ultrabug** [comment]
Friendly ping @ben-e-whitney since PR #157 got merged !

**Comment by ben-e-whitney** [comment]
Sorry for the delay, @ultrabug. Busy semester. PR #331 includes most of the code in this PR and doesn't change the default behavior of the module.

**Pull request closed without merging**
