### PR TITLE
lm_sensors: fix invalid json if specified more than one chip

### PR DESCRIPTION
**Pull request by lasers**
Config `chips` worked perfectly before we switched from `-u    Raw output` to `-j    Json output`.

The issue is that `sensor -j` does not always output valid json with multiple chips.

If you specify multiple chips using wildcard, you get valid json.

```json
❯ sensors -j '*-pci-*'
{
   "nvme-pci-0b00":{
      "Adapter": "PCI adapter",
      "Composite":{
         "temp1_input": 27.850,
         "temp1_max": 79.850,
         "temp1_min": -5.150,
         "temp1_crit": 84.850,
         "temp1_alarm": 0.000
      }
   },
   "amdgpu-pci-0c00":{
      "Adapter": "PCI adapter",
      "vddgfx":{
         "in0_input": 1.112
      },
      "vddnb":{
         "in1_input": 0.837
      },
      "edge":{
         "temp1_input": 32.000
      },
      "PPT":{
         "power1_input": 18.000
      }
   },
   "k10temp-pci-00c3":{
      "Adapter": "PCI adapter",
      "Tctl":{
         "temp1_input": 38.875
      }
   }
}
```

If you specify multiple chips individually, you don't get valid json.

```json
❯ sensors -j asus-isa-0000 k10temp-pci-00c3 nvme-pci-0b00
{
   "asus-isa-0000":{
      "Adapter": "ISA adapter",
      "cpu_fan":{
         "fan1_input": 800.000
      }
   }
}
{
   "k10temp-pci-00c3":{
      "Adapter": "PCI adapter",
      "Tctl":{
         "temp1_input": 40.125
      }
   }
}
{
   "nvme-pci-0b00":{
      "Adapter": "PCI adapter",
      "Composite":{
         "temp1_input": 27.850,
         "temp1_max": 79.850,
         "temp1_min": -5.150,
         "temp1_crit": 84.850,
         "temp1_alarm": 0.000
      }
   }
}
```

This dirty fix is a workaround to deal with invalid json https://github.com/lm-sensors/lm-sensors/issues/372.

Ought to close https://github.com/ultrabug/py3status/issues/2224.

### CODE REVIEW

**Comment by mlmatlock** [comment]
Patch worked good.

20231228_12h00m37s_grim

Got an added benefit of getting the GPU fan colored:

20231228_12h02m38s_grim

The remaining fans in the whole image are also from the NCT6793 sensor (along with MoBo and CPU temp in first image).

I'm guessing that it doesn't particularly care to call the same sensor twice.

Not a show stopper; this actually fixed my original request (getting drives colorized). anything else is probably out-of-scope.

Thanks, @lasers!!!!

**Comment by lasers** [comment]
You should try putting everything in one config... For starters, go with `chips = ["drivetemp-scsi-*", "*-*"]` ... this ought to place your drivetemp chips in first before any other chips now...

I might add `-i <file>` support to this module in order to simplify troubleshooting with other people's sensor json outputs.

Your issue with fans... I think it may be already fixable by fixing up your sensors.conf https://github.com/lm-sensors/lm-sensors/blob/master/etc/sensors.conf.eg.... You need to add `min` values higher than `0.000`.... Otherwise, it just uses default font color.

**Comment by lasers** [comment]
This fan have `min` and `max`.... This get auto colorized.
```json
      "fan1":{
         "fan1_input": 2055.000,
         "fan1_min": 0.000,
         "fan1_max": 3600.000
      },
```
This fans doesn't have `min` and `max`.... This doesn't get auto colorized.
```json
      "CHA_FAN1":{
         "fan1_input": 1106.000,
         "fan1_min": 0.000,
         "fan1_alarm": 0.000,
         "fan1_beep": 0.000,
         "fan1_pulses": 2.000
      },
      "CPU_FAN":{
         "fan2_input": 1800.000,
         "fan2_min": 0.000,
         "fan2_alarm": 0.000,
         "fan2_beep": 0.000,
         "fan2_pulses": 2.000
      },
      "M_2_FAN":{
         "fan3_input": 0.000,
         "fan3_min": 0.000,
         "fan3_alarm": 0.000,
         "fan3_beep": 0.000,
         "fan3_pulses": 2.000
      },
      "AIO_PUMP":{
         "fan5_input": 1434.000,
         "fan5_min": 0.000,
         "fan5_alarm": 0.000,
         "fan5_beep": 0.000,
         "fan5_pulses": 2.000
      },
      "CHA_FAN2":{
         "fan6_input": 1162.000,
         "fan6_min": 0.000,
         "fan6_alarm": 0.000,
         "fan6_pulses": 2.000
      },
```

**Comment by mlmatlock** [comment]
Ok.  So the machine idled for a couple of hours this afternoon, and no matter what I tried, this is the current output:

20231228_20h49m35s_grim

Here's my updated config:
```
lm_sensors {
    chips = ["nct6793-*", "*-pci-*", "drivetemp-*"]
    format_sensor = '[\?if=name=motherboard MoBo: ]'
    format_sensor += '[\?if=name=cpu CPU: ]'
    format_sensor += '[\?if=name=edge GPU: ]'
    format_sensor += '[\?if=name=composite NVMe: ]'
    format_chip = '[\?if=name=drivetemp-scsi-0-0 sda: ]'
    format_chip += '[\?if=name=drivetemp-scsi-2-0 sdb: ]'
    format_chip += '[\?if=name=drivetemp-scsi-4-0 sdc: ]'
    format_chip += '{format_sensor}'
    format_sensor += '[\?color=auto.input {input:.0f}°C]'
    sensors = ['samsung*', 'hitachi*', 'input', 'composite', 'edge', 'motherboard', 'cpu']
    }
    lm_sensors {
    format_chip = '{format_sensor}'
    format_sensor = '[\?if=name=fan1 GPU fan: ]'
    format_sensor += '[\?if=name=aio_pump Pump: ]'
    format_sensor += '[\?if=name=cpu_fan CPU Fan: ]'
    format_sensor += '[\?if=name=cha_fan1 Top Fan: ]'
    format_sensor += '[\?if=name=cha_fan2 Rear Fan: ]'
    format_sensor += '[\?color=auto.input {input} RPM ]'
    sensors = ['aio_pump', 'cpu_fan', 'cha_fan1', 'cha_fan2', 'fan1']
    }
```
  If I don't use a `chips =` line, everything before the fans is jumbled, but colorized (no fan at all).

20231228_21h03m19s_grim

I'll try playing some more tomorrow.

> Your issue with fans... I think it may be already fixable by fixing up your sensors.conf https://github.com/lm-sensors/lm-sensors/blob/master/etc/sensors.conf.eg.... You need to add `min` values higher than `0.000`.... Otherwise, it just uses default font color.

Already have one (both for the nct6793 (eg: the aio_pump is actually a header on my mobo, and is called fan5 normally) and drivetemp.  Since I set my fan curves in BIOS, the .conf file has no effect for setting a min speed. 

> 
> EDIT: Your issue with fans not being colorized... is due to values. There is nothing to compare against. You can try changing them with `color_excl_input = pink` or so.

I'll play around with that tomorrow as well.

Thanks!!!

**Comment by lasers** [comment]
>Ok. So the machine idled for a couple of hours this afternoon, and no matter what I tried, this is the current output:

I see two `lm_sensors` in your updated config. You probably got bit by that bug again. Nom, nom.

I'll put together an updated config for you to try later.

**Comment by mlmatlock** [comment]
> I see two `lm_sensors` in your updated config. 

Yeah; I can't come up with a way to combine

`format_sensor += '[\?color=auto.input {input:.0f}°C]'` and `format_sensor += '[\?color=auto.input {input} RPM ]'` so that a temp input would trigger the former, while a fan speed would trigger the latter.

Using the former, I'd get 1191°C, (fan speed) the latter would give me 42 RPM (temp)
> 
> I'll put together an updated config for you to try later.

That's cool...

**Comment by lasers** [comment]
>Yeah; I can't come up with a way to combine

To give you an answer _right now_...

Something like this.
```
format_sensor += '[\?if=name=edge GPU: [\?color=auto.input {input:.0f} °C]]'
format_sensor += '[\?if=name=composite NVMe: [\?color=auto.input {input:.0f} °C]]'
...
format_sensor += '[\?if=name=aio_pump Pump: [\?color=auto.input {input} RPM]]'
format_sensor += '[\?if=name=cha_fan1 Top Fan: [\?color=auto.input {input} RPM]]'
```
Crazy, I know.

**Comment by lasers** [comment]
```python
lm_sensors {
    format_chip = '{format_sensor}'
    format_sensor = ''
    format_sensor += '[\?if=name=samsung_860_ssd_(sda) SDA [\?color=auto.input {input:.0f}°C]]'
    format_sensor += '[\?if=name=samsung_860_ssd_(sdb) SDB [\?color=auto.input {input:.0f}°C]]'
    format_sensor += '[\?if=name=hitachi_hds72302_(sdc) SDC [\?color=auto.input {input:.0f}°C]]'
    format_sensor += '[\?if=name=motherboard MB [\?color=auto.input {input:.0f}°C]]'
    format_sensor += '[\?if=name=cpu CPU [\?color=auto.input {input:.0f}°C]]'
    format_sensor += '[\?if=name=edge GPU [\?color=auto.input {input:.0f}°C]]'
    format_sensor += '[\?if=name=composite NVMe [\?color=auto.input {input:.0f}°C]]'

    format_sensor += '[\?if=name=fan1 GPU Fan [\?color=auto.input {input} RPM]]'
    format_sensor += '[\?if=name=aio_pump Pump [\?color=auto.input {input} RPM]]'
    format_sensor += '[\?if=name=cpu_fan CPU Fan [\?color=auto.input {input} RPM]]'
    format_sensor += '[\?if=name=cha_fan1 Top Fan [\?color=auto.input {input} RPM]]'
    format_sensor += '[\?if=name=cha_fan2 Rear Fan [\?color=auto.input {input} RPM]]'

    chips = ["drivetemp-scsi-0-0", "drivetemp-scsi-2-0", "drivetemp-scsi-4-0", "nct6793-*", "*-pci-*"]
    sensors = ['samsung*', 'hitachi*', 'input', 'composite', 'edge', 'motherboard', 'cpu']
    sensors += ['aio_pump', 'cpu_fan', 'cha_fan1', 'cha_fan2', 'fan1']

    format_chip_separator = '\?color=lightblue \|'
    format_sensor_separator = '\?color=lightpink \|'
    color_excl_input = "lightgreen"
}
```

**Comment by mlmatlock** [comment]
@lasers, you are the $BEING!!!!!
I changed one thing: `color_excl_input = "#1793D1"` (Arch Blue).

20231229_15h25m25s_grim

Thank you so much!!

**Comment by ultrabug** [comment]
Well I'm in after the fight and once again @lasers mastered it all, you'll never cease to impress me as you're far way better than me on this formatting things...

So thanks a lot @lasers and thanks @mlmatlock for your nice gesture which I don't feel I deserve :/

**Comment by MacGyverNL** [comment]
Has this regressed? I'm on 3.62 and although
```
chips = ['coretemp-isa-0000 amdgpu-pci-1700 amdgpu-pci-6700 nct6798-isa-0290 nvme-pci-0200 nvme-pci-b400']
```
works to filter out unwanted sensors, 
```
chips = ['coretemp-isa-0000', 'amdgpu-pci-1700', 'amdgpu-pci-6700', 'nct6798-isa-0290', 'nvme-pci-0200', 'nvme-pci-b400']
```
fails with `Instance `lm_sensors`, user method `lm_sensors` failed.`

Judicious use of `self.py3.log` has led me to conclude that the curly-brace-insertion code doesn't actually insert any braces, because the chunk *already starts and ends* with `{` and `}`, but the first chunk's braces are now **unbalanced** due to split removing the last one in the chunk, crashing out of `_get_lm_sensors_data` with a `ValueError` / `JSONDecodeError` when `loads` tries to process it.

Example sensors -j output:
```
sensors -j amdgpu-pci-1700 amdgpu-pci-6700

{"amdgpu-pci-1700":{"Adapter":"PCI adapter","vddgfx":{"in0_input":0.875000},"fan1":{"fan1_input":1145.000000,"fan1_min":900.000000,"fan1_max":4200.000000},"edge":{"temp1_input":56.000000,"temp1_crit":97.000000,"temp1_crit_hyst":-273.150000},"PPT":{"power1_input":11.105000,"power1_cap":35.000000},"pwm1":{"pwm1":24.500000,"pwm1_enable":2.000000},"sclk":{"freq1_input":582930000.000000},"mclk":{"freq2_input":1500000000.000000}}}
{"amdgpu-pci-6700":{"Adapter":"PCI adapter","vddgfx":{"in0_input":0.006000},"fan1":{"fan1_input":0.000000,"fan1_min":0.000000,"fan1_max":3100.000000},"edge":{"temp1_input":37.000000,"temp1_crit":100.000000,"temp1_crit_hyst":-273.150000,"temp1_emergency":105.000000},"junction":{"temp2_input":41.000000,"temp2_crit":110.000000,"temp2_crit_hyst":-273.150000,"temp2_emergency":115.000000},"mem":{"temp3_input":38.000000,"temp3_crit":100.000000,"temp3_crit_hyst":-273.150000,"temp3_emergency":105.000000},"PPT":{"power1_average":6.000000,"power1_cap":264.000000},"pwm1":{"pwm1":0.000000,"pwm1_enable":2.000000},"sclk":{"freq1_input":0.000000},"mclk":{"freq2_input":96000000.000000}}}
```

Resulting first chunk in `_get_lm_sensors_data(self)`:
```
{"amdgpu-pci-1700":{"Adapter":"PCI adapter","vddgfx":{"in0_input":0.875000},"fan1":{"fan1_input":1146.000000,"fan1_min":900.000000,"fan1_max":4200.000000},"edge":{"temp1_input":55.000000,"temp1_crit":97.000000,"temp1_crit_hyst":-273.150000},"PPT":{"power1_input":10.210000,"power1_cap":35.000000},"pwm1":{"pwm1":24.500000,"pwm1_enable":2.000000},"sclk":{"freq1_input":255320000.000000},"mclk":{"freq2_input":1500000000.000000}}
```

Changing from `output.strip().split("}\n{")` to `output.strip().split("\n")` makes everything start working, but of course this feels rather fragile. Is there a better way to "repair" this json, short of outright catching `loads` ValueErrors, counting the opening and closing braces, then inserting that many at start / end?

**Pull request merged**
