### PR TITLE
fix XDG_CONFIG_HOME #204

### PR DESCRIPTION
**Pull request by tobes**
This fixes the XDG_CONFIG_HOME issue.

I'm not sure what other paths if any we want to add from that issue #204 

It looks like we cover all the i3status default locations https://i3wm.org/i3status/manpage.html#_options

### CODE REVIEW

**Comment by ultrabug** [comment]
I think @tobanw was referring to the inclusion folder for user modules, not the i3status.conf location detection itself (tho you're correctly fixing this too in this PR)

I guess he has a point there and we could extend these path to the i3 user modules inclusion directory detection ?

**Comment by tobes** [comment]
I can add extra module search dirs to this PR.

**Comment by tobes** [comment]
Currently it looks like we only allow one user directory `-i` overrides it.  This change would mean that we would now look in multiple directories.  So we need to worry about an order of dirs to look in (easy enough to change)

Are we still going to replace the user modules directory/directories if `-i` is used? 

For me it makes most sense to look in 
User supplied via `-i` > `~/.i3/py3status` > `~/.config/i3status/py3status/` >  `~/.config/i3/py3status/`

using the XDG_CONFIG_HOME if we have it set

although `~/.config/i3status/py3status/` feels wrong to me

**Comment by tobanw** [comment]
Yup that's right, it's this line: https://github.com/ultrabug/py3status/blob/master/py3status/core.py#L58

**Comment by pydsigner** [comment]
@tobes I think we should probably have an additional flag to tell py3status not to look in the standard directories.

**Comment by tobes** [comment]
I've updated the user module directories that are now checked in the following order:

`~/.i3/py3status` > `~/.config/i3status/py3status/` > `~/.config/i3/py3status/`

Assuming `XDG_CONFIG_HOME`  is not defined or `~/.config`

I removed the sorted as we should look in the directories in a user set order if provided by `-i` as that is what the user would expect.  Also this means that we look in our predefined directories in a set order.

We no longer overwrite user modules once they have been found. 

if `-i` is supplied we only look in those directories as that was the current behaviour, but I'd prefer to just add those to the front of the list, but that is a behaviour change.

**Comment by ultrabug** [comment]
I think this is good as is, `-i` users just point where to look themselves and the others use autodetection.

Thanks !

**Pull request merged**
