### PR TITLE
fix empty seeming composite block issue

### PR DESCRIPTION
**Pull request by tobes**
#1468 found an issue 

@lasers so yeah I found it and fixed it

usbguard code made me want to throw up though - it needs a full rewrite imho or at least comments explaining what the fuck it is up to

### CODE REVIEW

**Comment by tobes** [comment]
for usbguard. In `_get_devices()` we do far too much work by the look of it.  We should remember the devices.  I'm not sure what dbus gives us (sample output in the function would be great here) but I think it is text so we only care if it changes, or devices are added/removed.
Hey you could probably cache the whole output for each device too (save even more work)

With the regex how often do they run?  Maybe we could have one big regex rather than lots - again I'd need to see the output.  But really we can probably save loads of cpu by just being slightly clever.

With the Thread - the whole dbus stuff needs to be done by py3status not by individual modules but that is for another day...

**Comment by tobes** [comment]
> The fix is good! smiley

you could add a ready to merge label at least ;p

**Comment by lasers** [comment]
We'll continue this discussion in #1376. Sure! You can have both: a label and a smiley face. :)

**Comment by ultrabug** [comment]
> With the Thread - the whole dbus stuff needs to be done by py3status not by individual modules but that is for another day...

that's also true for udev related events... but hey, I'm coming with a crazy thing soon(tm)

BUT I say it again, we should **release** a new version now, too much has been done already

**Pull request merged**
