### PR TITLE
check_tcp: merge formats

### PR DESCRIPTION
**Pull request by lasers**
This merges three things.
```
-    format: (default '{host}:{port} {state}')
-    icon_off: (default 'DOWN')
-    icon_on: (default 'UP')
```
```
+    format: (default '{host}:{port} [\?if=is_open UP|DOWN]'
```

### CODE REVIEW

**Comment by tobes** [comment]
No this is the wrong approach.

we should just choose one of `state` or `icon` and go with that like we have on other modules.

**Comment by lasers** [comment]
Basically, this PR is not necessary because `check_tcp` is completed?  This is similar to `wifi` in a way that it only contain a single format for simple on/off operation.

This maybe goes same for `file_status`, `dpms`, `process_status`, `xscreensaver`? I likely missed some more. Idk. It sounds like we are not sure about merging this kind of things.

I can hold this off for now... Get other PRs merged in first... Take things slow... No sweat. I guess I could clean up the exceptions now, blah... single PR or separate PRs?

I think this kind of idea may need to be discussed first with others... Draw a line on sand on whenever we want to put many things as we can in the `format` so we can use `formatter` stuffs right away... or just going with `state`/`icon` and still the `formatter` stuffs (optional) per-state...... and whenever we want to keep things easy or put everything in the format.... Complex syntax for everybody and all.

Just trying to make your dream happen! 👍 ;-)

**Comment by lasers** [comment]
Hi. I'm revisiting this... I think using `{state}` or `{icon}` is the wrong approach when it comes to customizing. AFAIK you may have a branch that allows more rich colors and we wouldn't be able to apply it here without this PR or other PR to convert `{icon}`/`{state}` to `format_on`/`format_off`.

Go for single `format` or multiple `format_*`. Expose everything.

```
# Current (Wrong ; Cannot customize colors everywhere)
format: (default '{host}:{port} {state}')
icon_off: (default 'DOWN')
icon_on: (default 'UP')
```
```
# Ideal (Choice A)
format: (default '{status}')
format_off: (default 'host}:{port} DOWN')
format_on: (default 'host}:{port} UP')
```
```
# Ideal (Choice B)
format: (default '{host}:{port} [\?if=is_open UP|DOWN]'
    OR
format: (default '[\?if=is_open {host}:{port} UP|{host}:{port} DOWN]'
```

**Pro/Con:** Putting everything in the `format`.
* We introduce more placeholders.
* We leave users to figure out formatting and/or controlling.
* We leave users to learn this without a documentation.
* If we change one thing, we hoard all other stuffs in our `format`... and in our config. This includes default options too.
* Cleaner to remove unwanted string in `format` instead of toggling `hide_when_playing` or `hide_when_stopped`. Can be hassle if somebody toggle it back on by adding and/or commenting other `format` below.
* `get_placeholders_list` does not work with `\?if=connected`.
* More potential helpers like `get_control_list` and something to convert `is_connected` boolean to `is_connected` --> `''`,`' '` and add it to the return (auto if possible) ,eg `self.py3.update(is_connected, True)` or `self.py3.update(is_connected, True, data)`. If not `self.py3.update()` due to existing method, then maybe `self.py3.control()`.

**Pro/Con:** Using `format_*`.
* We control if, states, etc in the code.
* Easier for users. Leave less (and no default) options in the config.
* May have to introduce simple options that checks things, simple options that toggles things, etc, but we try to work within `format_*` using placeholders first.
* Set up new standard to have all `format` going with either `'{status}'` or `'{output}'`. Make it easier to add prefix and not having to remember what placeholder it may be. This should work quite well if we don't pass in colors immediately until after `[\?color]` so the statusline color can colorize all module prefix (if any) ie `'GPU[: [\?color]{format_temp}]'` could pass in white `GPU: ` then green `62 F`.

Sorry about the text wall. I hope I make sense. Many thanks.

**Comment by tobes** [comment]
@lasers sorry you are finding this all a bit frustrating.  From my point of view the move to get all modules to use format has been a great piece of work but has taken almost 2 years to get to where we are now, so don't expect things to happen instantly.  Often there are dependencies that slow things down.  Change is slow and hard sometimes.

Anyhow with the format stuff, my take again is.  We have `state_..`, `icon_..` in some modules.  I think this is fine and makes sense to the user.  We could remove all these but currently I do not see an advantage to this.  This situation is very different to the `wifi` multiple formats to single format issue.  But here, these are definitely not formats in my opinion.  Why? Mainly because they do not contain any placeholders, and we are always using `format`

The reality is that currently you can just use the format and ignore the `icon_..` options if you want.

Now with this module imho we should look at passing `icon_..` through `safe_format()` so that we can have colors for them. but that is about it.  Maybe we revisit this again at some point when we have learnt to do this better.

A few last points

> is_connected boolean to is_connected --> '',' ' 

we can just use a boolean when things are fixed

> get_placeholders_list does not work with \?if=connected.

`connected` is not a placeholder so it not being returned is fully correct.

> We leave users to learn this without a documentation.

yes we do need format documentation, but let us get that before 'forcing' the user to have to learn it


Also, please __do not__ add people to the authors list without their __explicit__ consent.

**Comment by lasers** [comment]
>@lasers sorry you are finding this all a bit frustrating.

I'm finding all of this fun... Just making things happen instantly.

>don't expect things to happen instantly.

I understand. Just making things happen whenever we can... slowly or instantly. One PR at a time to fix there and another one to improve there. No rush.

> We have state_.., icon_.. in some modules. I think this is fine and makes sense to the user. We could remove all these but currently I do not see an advantage to this.

Master `check_tcp` can't do much with color right now. 

Using `format_on`,`format_off` example. [@lasers:format-check-tcp/check_tcp.py](https://github.com/lasers/py3status/blob/format-check-tcp/py3status/modules]/check_tcp.py)
```
check_tcp{
    format = 'SSHD{status}'
    format_on = '[\?color=#fff&show :] [\?color=#a3d572&show Host][\?color=#fff&show :] [\?color=#6d9e3f {host}] [\?color=#a3d572&show Port][\?color=#fff&show :] [\?color=#6d9e3f {port}]'
    format_off = '[\?color=#fff&show :] [\?color=#ffa7da&show Host][\?color=#fff&show :] [\?color=#d370a3 {host}] [\?color=#ffa7da&show Port][\?color=#fff&show :] [\?color=#d370a3 {port}]'
}
```
I make nice green imho. I think the red is kinda meh, need to be worked on a bit more to find that right shade of red. With `single` format, we could just toss everything all in one line... or keep using `format_*`. Does not matter... just that `{icon}` and `{state}` can make things like this harder to customize... so we works with neutral colors instead.

>The reality is that currently you can just use the format and ignore the icon_.. options if you want.

Maybe. I guess I could try use `format = '{state}`, and work with `icon_*`. I don't know if `{host}`and `{port}` work in `icon_*` too. I think it is already possible... or it will with your pending formatter PR. I say already possible because the code does not show that we're passing port/host at all... so yeah, maybe.



>    is_connected boolean to is_connected --> '',' '
>>we can just use a boolean when things are fixed

Better in every way. 👍 

>get_placeholders_list does not work with ?if=connected.
>>connected is not a placeholder so it not being returned is fully correct.

This is more for `post_config_hook` to check if new format contains any control placeholders (only if we're going with that). I could do `=connected` in self.format` thing instead.

>Also, please do not add people to the authors list without their explicit consent.

Yes, sir. 👍

**Comment by tobes** [comment]
I think we should close this PR.  I can't see it getting merged in it's current state, due to increasing complexity for no benefits imho.

**Comment by ultrabug** [comment]
In general, I agree we should close non crucial PRs to make our roadmap more clear. I don't like all these lying around and I really think we should stick to **good & simple should is enough**

I like the formatter and its possibilities, but keep in mind that users just tend to use non brainer options.

**Pull request closed without merging**
