### PR TITLE
lm_sensors: revert, cache, optimize, cleanup

### PR DESCRIPTION
**Pull request by lasers**
The command `sensors` got  `-j` for JSON output not long ago. However, they hadn't made a release for 3-4 years so we think not many users will be able to use `-j` or install `lm_sensors-git` easily so we're going to support native/raw `-u` output instead.

This means... More users can use `lm_sensors` and not having to fuck around with anything. Yay.

### CODE REVIEW

**Comment by tobes** [comment]
I'm not comfortable merging this in 3.13

yes it is almost certainly better that what we currently have but it needs more work and I can see this taking a while.

**Comment by lasers** [comment]
>yes it is almost certainly better that what we currently have

:-)

>but it needs more work and I can see this taking a while.

I gave this more work and it didn't take a while. I hope this confirms that it's not something we're merging at last minute since I gave this more work (to well confirm that it's not something we're merging at last minute).

**Comment by lasers** [comment]
Comfortable or not... Merge this then we can release `3.13` today. I worked with this module enough to see that reverting `-j` to `-u` is not going to pose a problem for anybody except for some users that may need to specify `ignore sensor_name` in `/etc/sensors` (100% unrelated to this issue).

I made enough unrelated modifications as a proof that I'm working on this module some more, eg cleaning up things a bit, killing excessive information, caching names, and whatnot. There is not much anything more I can do with this. All of this is required to show that `-u` is still working okay.

**Comment by tobes** [comment]
> I made enough unrelated modifications as a proof that I'm working on this module some more

that's great but also 100% why I feel the not merging till 3.14 is the correct decision

my view is that if this was important you would have done it earlier - you are doing it now == it is not vital

**Comment by lasers** [comment]
I'm happy to do this for you and users that does not have to... or want to... wait for `-j` to hit mainstream. In either case, I think it's still a good move to merge this. Maybe it's unimportant, but I strives to make everybody using `py3status` happy as possible... including reverting + last minutes works to ensure that everything are still working smoothly. First impression can be good.

I hope we don't have to do this at every reelase, but `3.12` is a weird timeline... Your long-term absence, me getting a status (I suspect to get things moved a bit), then you suddenly came back so I stopped moving things, then we still roll back some things... you say if this was important, I'd had moved things... but I think I would still have move this (as well as more things) if you hadn't came back... Also, this `-j` issue was revealed a week later after you can back... but after 4 weeks since `lm_sensors` got merged...... really, we can't predict everything. We need things to be able to merge new things so users can test and report unexpected things.

Point beings. We can't predict everything. I certainly didn't predict issue with `sensors -j` itself as well as ignoring things in `/etc/sensors` to ignore error codes, etc. I predicted different issues such as `min`, `max` actually changing values anytime so we would need to update thresholds all times instead of first_run... or users need assistance with setting up their `lm_sensors` format.

You're probably not going to be the only user not wanting to install `lm_sensors-git` to get `-j`.

**Comment by ultrabug** [comment]
Ok so I want to make a few points as I am going to merge this:

- You guys had a long discussion about it on IRC
- I want this **3.13 release to be a warm welcome to @lasers new role** in the project

so I will make an exception BUT it is important for us to acknowledge

- this is bad timing, I declared the code frozen before this happened and this is not critical
- in 3.14 we should enforce a **very strong** policy in our workflow (nor merging own PR, respecting the release goals)

Thanks

**Pull request merged**
