### PR TITLE
Better module doctest failures

### PR DESCRIPTION
**Pull request by alexoneill**
Hey all!

While working on #930, I ran into the linter pretty consistently. The most annoying issue to deal with was alphabetical ordering for parameters, as the error message in the linter would not indicate clearly which items were out of place. This becomes a bigger issue the more options you have!

I decided to take a crack at improving it! Below are my changes. I added a simple `diff` method to signal differences between two lists of items. This improves the linter output significantly:

_Module source_:
```python
...
    cache_timeout = 10
    fallback = True
    force_on_start = None
    fixed_width = True
    format = '{output}'
    icon_clone = '=' 
    icon_extend = '+' 
    hide_if_single_combination = False
    output_combinations = None
...
```

_Before_:
```
Attributes not in alphabetical order, should be
['cache_timeout', 'fallback', 'fixed_width', 'force_on_start', 'format', 'hide_if_single_combination', 'icon_clone', 'icon_extend', 'output_combinations']
```

_After_:
```
Attributes not in alphabetical order, should be
                        Source    Target
    --------------------------------------------------------
                 cache_timeout    cache_timeout
                      fallback    fallback
                force_on_start !! fixed_width
                   fixed_width !! force_on_start
                        format    format
                    icon_clone !! hide_if_single_combination
                   icon_extend !! icon_clone
    hide_if_single_combination !! icon_extend
           output_combinations    output_combinations
```

Something which is not shown is that the diff engine can handle different length lists, where two 'arrows' (either `>>` or `<<`) go from the side which has the line to the side which does not.

As long as the lists have items which can be compared for equality and have a string representation, the simple diff method can be used.

Let me know what you think!

### CODE REVIEW

**Comment by tobes** [comment]
This sounds fantastic!

**Comment by ultrabug** [comment]
This is awesome 👍

Congratz and thanks for the neat implementation, LGTM. @tobes ?

**Comment by ultrabug** [comment]
@alexoneill we are looking to release 3.6 and this PR and the OWM module one are listed as being needed for that.

Please tell us if you are too busy to take care of them yourself, then if you're okay we'll merge & do the little fixes ourselves?

Thanks a lot mate

**Comment by ultrabug** [comment]
I'm merging this as-is to release 3.6, we'll iterate from there. Thanks @alexoneill !

**Pull request merged**
