### PR TITLE
use utc not local time to get time offset fix #229

### LINKED ISSUE #229: Wrong tztime guess when using local
When using `tztime local`, the guessed time is UTC even if i3status outputs the right time.

i3status output : `{"name":"tztime","instance":"local","markup":"pango","full_text":"2016-03-29 09:42:50 CEST"}`

py3status output : `{"name":"tztime","instance":"local","markup":"pango","full_text":"2016-03-29 07:42:50 CEST"}`

Config :
```
tztime local {
	format = "%d/%m/%y %H:%M:%S"
}
```

### PR DESCRIPTION
**Pull request by tobes**
use `datetime.utcnow()` not `datetime.now()`

### CODE REVIEW

**Comment by tobes** [comment]
fixes #229

**Comment by ultrabug** [comment]
:+1:

**Comment by tobes** [comment]
I'm not sure if fixing a bug I introduced deserves a :+1:

**Comment by ultrabug** [comment]
> I'm not sure if fixing a bug I introduced deserves a :+1:

it does since all I had to do is report it :palm_tree:

**Pull request merged**
