### PR TITLE
Persistent CookieJar using the new storage system

### PR DESCRIPTION
**Pull request by raspbeguy**
There is mainly 2 changes in this PR:
* I defined a `StorageObject` class which can be used to define subclasses which will be saved in storage (methods `save()` and `load()`)
* I implemented such a class with `PersistentCookieJar`. With this I guess I'll finally be able to progress on #1194, at last!

Just a question before it's fully ready to merge: How do you edit the documentation? I see there are both RST files and a README.md file which contains the same text for what I've seen. Is the README generated from the RST (or the opposite)? If so, how do you do that?

### CODE REVIEW

**Comment by lasers** [comment]
`README.md` is deprecated and hadn't been updated much. We leave it alone as-is for Github front page. Use RST... which will be reflected eventually on `readthedocs`.

**Comment by tobes** [comment]
> How do you edit the documentation?

Depends.  Some is in /doc and hand crafted.  Some of it is auto generated eg modules/py3
building docs limited info https://py3status.readthedocs.io/en/latest/contributing.html#building-documentation

The docs need a cleanup as some is left over from the old system

**Comment by raspbeguy** [comment]
OK so I updated the RST. Feel free to tell what you think about this storeable object system.

**Comment by raspbeguy** [comment]
@tobes is there anything I can do to help making PR validations go faster?

**Comment by tobes** [comment]
Sorry for the delay in looking at this properly.

I think we can slim this down a little by just having the one PersistentCookieJar, I think subclassing things just for one object over complicates things.  Sure if we had other similar things but we don't for now.

Also we can just use the modules `py3` and not worry about initialization of storage etc.

Something like this (untested)

```diff
diff --git a/py3status/py3.py b/py3status/py3.py
index 15ed85e0..bfe03625 100644
--- a/py3status/py3.py
+++ b/py3status/py3.py
@@ -15,7 +15,7 @@ from time import time
 from py3status import exceptions
 from py3status.constants import COLOR_NAMES
 from py3status.formatter import Formatter, Composite
-from py3status.request import HttpResponse
+from py3status.request import HttpResponse, PersistentCookieJar
 from py3status.storage import Storage
 from py3status.util import Gradiants
 
@@ -1009,6 +1009,14 @@ class Py3:
             items.add((key, value))
         return items
 
+    def storage_new_cookiejar(self, name='cookie_jar', policy=None):
+        """
+        Return an instance of persistant cookie jar using our storage system.
+
+        Can be used like original CookieJar constructor
+        """
+        return PersistentCookieJar(self, name, policy)
+
     def play_sound(self, sound_file):
         """
         Plays sound_file if possible.
diff --git a/py3status/request.py b/py3status/request.py
index 2a31dfe5..7716417a 100644
--- a/py3status/request.py
+++ b/py3status/request.py
@@ -4,6 +4,7 @@ import socket
 
 try:
     # Python 3
+    from http.cookiejar import CookieJar
     from urllib.error import URLError, HTTPError
     from urllib.parse import urlsplit, urlunsplit, parse_qsl, urlencode
     from urllib.request import (
@@ -12,6 +13,7 @@ try:
     IS_PYTHON_3 = True
 except ImportError:
     # Python 2
+    from cookielib import CookieJar
     from urllib import urlencode
     from urllib2 import (
         urlopen, Request, URLError, HTTPError,
@@ -146,3 +148,28 @@ class HttpResponse:
         Set the cookie jar in care we want to change it after object creation
         """
         self._cookiejar = cj
+
+
+class PersistentCookieJar(CookieJar):
+    """
+    Custom CookieJar child class that will use our storage module.
+    """
+
+    def __init__(self, py3, name, policy=None):
+        CookieJar.__init__(self, policy=policy)
+        self._key_name = name
+        self._py3 = py3
+
+    def save(self, key):
+        """
+        Store object.
+        """
+        self._py3.storage_set(self._key_name, self._cookies)
+
+    def load(self, key):
+        """
+        Retrieve object.
+        """
+        data = self._py3.storage_get(self._key_name)
+        if data:
+            self._cookies = data
```

**Comment by raspbeguy** [comment]
I'm not a big fan of your solution.

I think the subclass solution is the most elegant and pythonic way to do stuff. Even if we have only this `PersistantCookieJar` object for now, I know that it's better to implement a scalable system now rather than reimplementing it with pain and horror later. Also I have tons of ideas for potential subclasses to `StorageObject`. Basically I think that every non-standart type or structure (understand not `int`, `bool`, `dict`...) we wish to be storable should be implemented as a subclass that will contain our method `save` and `load`. You don't wish to reimplement those methods each time you design a new storable object, do you?

**Comment by tobes** [comment]
> Also I have tons of ideas for potential subclasses to StorageObject

Sounds interesting what sort of things?

I'm for keeping thing simple if we can,  The `StorageObject` is just re-implementing things already in `Py3` so why not just use that to start with?

As a thought how about just implementing `__getstate__()` and `__setstate__()` so we are pickalable?

something like
```python
class PickleableCookieJar(CookieJar):
    """
    Custom CookieJar child class that can use our storage module.
    """

    def __getstate__(self):
        """
        Store object.
        """
        return self._cookies

    def __setstate__(self, data):
        """
        Retrieve object.
        """
        self._cookies = data
```

that way I could do
```python
# get cookie jar or create one
cj = self.py3.storage_get('cookie_jar')
if not cj:
    cj = self.py3.create_cookie_jar()
....
self.storage_set('cookie_jar', cj)
```

this does miss out on the `policy` but scanning the code it should be possible without too much pain, your code does to by the way

**Comment by ultrabug** [comment]
@tobes bump plz

**Comment by ultrabug** [comment]
Then @raspbeguy please your PoV ?

**Comment by raspbeguy** [comment]
Sorry for the delay.
Well, if you really don't want that subclass system I guess it wan't be helped. I still think su subclass way is the most pythonic (and most fun) way, but whatever, I guess this isn't that important.
At this point I'm just a bit frustrated because that code took me quite a lot of time and we will just nuke it to something more simple on the short term.
Also it imply me reworking not only that PR, but also #1194.
Well, I'm sure I'll survive.

**Comment by tobes** [comment]
@ultrabug I'm still of the opinion that this PR adds unneeded complications for what could be more simple see the proposed patch https://github.com/ultrabug/py3status/pull/1278#issuecomment-370582837

@raspbeguy 
> At this point I'm just a bit frustrated because that code took me quite a lot of time and we will just nuke it to something more simple on the short term.

Yeah it can be frustrating but sometimes this happens.  If it is any consolation I have also had branches that I've spent days on that have not gone anywhere both on this project and on others so I feel your pain.  However I think we need to be careful about adding extra complication to the code base.  It is already overly complex and we need to look at how we can simplify stuff, to reduce the number of bugs, make things more maintainable and make it easier to understand.

**Comment by ultrabug** [comment]
Closing as discussed with @raspbeguy

**Pull request closed without merging**
