### PR TITLE
coin_market: remove first_run

### PR DESCRIPTION
**Pull request by lasers**
Parroting.

>Simplify the code.

>I think this makes things cleaner and is worth the minor change

>This needs #1246 as otherwise it slows down startup of py3status.

### CODE REVIEW

**Comment by tobes** [comment]
seems good.  Can you just confirm that you have tested this.

Hopefully we can push for #1246 to be merged asap as it does allow more of these cleanup/code removal.

**Comment by lasers** [comment]
I confirm this works okay. Rebasing.

**Comment by tobes** [comment]
cool nice clean and readable 👍 merged within the day :)

**Comment by tobes** [comment]
except we need #1246 so I'll revert till then

**Pull request merged**
