### PR TITLE
scratchpad_async: Fix name

### PR DESCRIPTION
**Pull request by lasers**
This helps with telling the difference between two scripts in the log.

### CODE REVIEW

**Comment by tobes** [comment]
I'm curious why this is needed.  In the logs etc we should have the name of the module as well as the method.  Maybe I'm missing something.

**Comment by lasers** [comment]
This prints `scratchpad counter` for me. I looked it again just now.

`2017-01-09 03:00:43 INFO method scratchpad_counter returned {'full_text': '0 ⌫', 'instance': '', 'name': 'scratchpad_async'}`

Okay. I see my mistake. Leaving it `scratchpad_counter` as a method could be misunderstood for `scratchpad_counter` module. Same thing for `window_title` module where I initially saw the issue... as I was testing somebody's PR.

**Comment by tobes** [comment]
>  Leaving it scratchpad_counter as a method could be misunderstood for scratchpad_counter module. 

I think it's more that we should have the info in the logs.  That looks like it is from using the debug option.  And as we have the output we can see the module causing it.

If we do logging from inside a module we should get the modules name in the logs.  So I think we have the info.  If not then we should be improving the output not need to change the modules name.

**Comment by lasers** [comment]
I was using debug option + `-l /tmp/py3status-top.log`. I can leave this currently as-is or rename to something simple/generic.
- `get_counter`,`return_counter` as to keep scratchpad out of it.
- `get_title`, `return_title` to keep window_title out of it.

Good idea to improve output by starting off with module names, then method. Also, I think we may not have to do anything here because it is only two scripts so far. I didn't realize I got confused until you pointed it out.

**Comment by ultrabug** [comment]
It's a good QA PR thanks, improving logs is another topic indeed

**Pull request merged**
