### PR TITLE
systemd: Suppress output if unit is in default state

### PR DESCRIPTION
**Pull request by flyingapfopenguin**
The most systemd units have a clear "default" state.

To be able to be notified only, if the unit is not in this "default" state, I suggest the following config option:

hide_if_default: suppress the output if the systemd unit is in default state (default 'Off')
        'Off' the output is never suppressed
        'On' the output is suppressed if the unit is (enabled and active) or (disabled and inactive)
        'active' the output is suppressed if the unit is active
        'inactive' the output is suppressed if the unit is inactive

### CODE REVIEW

**Comment by ultrabug** [comment]
Thanks @flyingapfopenguin 

Another convention thing, please make your options values lower case

On/Off -> on/off

**Comment by lasers** [comment]
@ultrabug (Q) Are we going to try and put them all in the `format`? (all examples documented). If yes, then there might be some things that need to be changed first, eg convert `active/inactive` to `True/False`. Same for new `state` here... convert `enabled/disabled` to `True/False`.

We don't really have to do this, but it could be better to use `\?if=state...` instead of always specifying   `\?if=state=enabled ...`

**Comment by flyingapfopenguin** [comment]
@lasers I thought about the possibility to implement the complete "hide logic" in the format string, but this would lead to really complex string. So I decided to suggest this solution: The logic is implement in the python code and a boolean can be used in the format string to use this feature.
But i support your question @ultrabug: What is the guide line?

**Comment by lasers** [comment]
I thought about using `GetAll()` and putting everything in the new `format`, but like you said, it would lead to really complex string because of 80~ new placeholders, much longer format, and deprecating of placeholders + colors.

This module does not have `on/off` format so users can't add `on/off` icons if they want. At most, they only can add name or custom icon... and relies on `good/bad` colors.

Users can copy old `sshd` or `sshd.service` (colorized `sshd` or `sshd.service`) with new format.
With new format, users can make `sshd on` or `sshd off` (non-colorized `sshd`, colorized `on/off`).

```python
systemd {
    format = '{unit} [\?if=ActiveState=active&color=good on|\?color=bad off]'
}
```

This looks identical to your `hide_if_default = on` config. Not hardcoded.
```python
systemd {
    format = '[\?if=ActiveState=active '
    format += '[\?if=UnitFileState=disabled&color=good {unit}]]'
    format += '|[\?if=ActiveState=inactive '
    format += '[\?if=UnitFileState=enabled&color=bad {unit}]]'
}
```
or if you prefer without `.service`, swap out `{unit}` with `sshd` instead of using `hide_extension = True`. Another reason why `hide_extension` is meh is because the next new config could be `uppercase = True` versus using `SSHD` or even `SSH` in the format.

Things suggested here will be overkill for all users :face_with_head_bandage: but it would prevent more fairly-simple configs from being added and would offer more customization flexibility than before... even although the new `format` can be ugly sometimes. This also avoids fake placeholders (ie `{hide}` in this PR).

**Comment by lasers** [comment]
@flyingapfopenguin Hi. I'm wondering if you had made any progress on this PR? :-)

**Comment by ultrabug** [comment]
Simple & works as intended, thanks @flyingapfopenguin

**Pull request merged**
