### PR TITLE
arch_updates: remove obsolete cower from docs

### PR DESCRIPTION
**Pull request by lasers**
`cower` has been deprecated for a year and a day. The source repo is gone too. We should remove `cower` from `arch_updates`. It's always possible that some users are still using `cower` today. Time to kick them off if that's actually true, I guess. 

Addresses the issues in #1716.
1) >`cower` has been deprecated and is no longer in the AUR available for install.
2) >`auracle` is not mentionned in the doc then x)

Adding `pikaur` or other helpers should be done separately.

### CODE REVIEW

**Comment by maximbaz** [comment]
Shall we postpone removing cower to 4.0? This is a breaking change after all 🤔 

And maybe in 4.0 we can return to the idea of a generic "updates" module that you created earlier...

**Comment by lasers** [comment]
>This is a breaking change after all :thinking: 

My :thinking:  is that there are no release date for `3.17` and `cower` is not available in aur repository for some time (how long?). It might not matter because users installed `yay`, `auracle`, or other aur helpers to replace `cower`, `pacaur` and others. We can test `yay` and `auracle` instead and proceed from there with any other helpers if necessary.

Other issue is that `arch_updates` ought to catch up with standards too. Use helpers instead of `subprocess`, `LINE_SEPARATOR` which I don't mind doing after this PR. 

>And maybe in 4.0 we can return to the idea of a generic "updates" module...

I don't know if that'll happen. I don't feel `post_config_hook` is perfect, but it is working fine (assuming because of managers not set). I also wanted to consolidate `scratchpad` modules, `window_title` modules, etc too...

Not to mention that `updates` would kill several configs like `hide_if_zero` in favor of basic formatter (which is now ought to be replaced with f-string formatter). I believe we're against this now too.

**Comment by maximbaz** [comment]
even though it's not in AUR now, many people might have it installed :( Minor release must not introduce breaking changes, add cower removal to 4.0 milestone and let's push for starting work on 4.0 :)

let's keep cower, but update documentation for auracle and do other improvements.

**Comment by lasers** [comment]
Done.

**Pull request merged**
