### PR TITLE
formatter: add expand_color()

### PR DESCRIPTION
**Pull request by lasers**
This aims to replace unrelated `fix_color` code in #1472. I found more things to use `expand_color` on too. This passed all the tests, but I see two instances where the tests can be wrong.

If you want to close this and #1472 instead, then that's fine too. Black star just in case.

Addresses #1472 unrelatedly.

EDIT: Do you like `expand_color` or something else? `get_color`?

### CODE REVIEW

**Comment by lasers** [comment]
@ultrabug Seeing `3.19` just came out, would you want to merge this today so we can see if we run into any color issues later on?

**Comment by ultrabug** [comment]
Wel have a gentle user reporting regression on color management between 3.14 and 3.18/3.19 on IRC (would be cool to have you there sometimes btw)

So I'd like first to address this before merging anything color related!

**Comment by lasers** [comment]
>gentle user reporting regression on color management between 3.14 and 3.18/3.19 on IRC

gimme dem irc logs and/or have the user open an issue. plz and thx.

**Comment by ultrabug** [comment]
> user: my mpd_status is full of colors (one for artist, one for album, one for the track) and it works as intended on 3.14, but on 3.18 and 3.19 the entire mpd_status is color_good, anything change ? I looked at the changelog but didnt see anything

then I unfortunately didn't get an answer for:

>  care to open an issue on github with your format config plz ? would help debugging

**Comment by lasers** [comment]
(Lazy analysis) Imho.

>user: my mpd_status is full of colors (one for artist, one for album, one for the track) and it works as intended on 3.14, but on 3.18 and 3.19 the entire mpd_status is color_good, anything change ?

Not possible... According to...

https://github.com/ultrabug/py3status/blob/321425ddc43bfdc4a0096f3b42d0f01a4803076e/py3status/modules/mpd_status.py#L207-L215

Possible... User used multiple instances to print different colors and forget about this.

Possible... User used `new module from scratch: mpd_status` branch and forget about this.

**Pull request merged**
