### PR TITLE
Allow external_script to preserve number formatting

### LINKED ISSUE #2100: external_script modifies numeric output
The external_script module converts numeric values to a numeric type. This removes the original formatting of the input and is undesired.

To reproduce create an external script and simply echo "0.123000", the output in the bar will be "0.123".

### PR DESCRIPTION
**Pull request by nkuttler**
This fixes #2100. Please let me know if anything else should be done or if any changes are needed.

### CODE REVIEW

**Comment by nkuttler** [comment]
I'm just thinking, shouldn't the argument be `convert_number` and default to True?

**Comment by ultrabug** [comment]
Ok let's just call this option `convert_numbers` and default it to `True` please

**Comment by ultrabug** [comment]
I think (at least to my non native english standpoint) that having it plural makes more sense. It's also what you documented : `convert numbers to a numeric type`

**Comment by nkuttler** [comment]
Done!

**Comment by ultrabug** [comment]
Thank you

**Pull request merged**
