### PR TITLE
ignore ZFS ARC cache in memory usage

### PR DESCRIPTION
**Pull request by anarcat**
Workstations with a ZFS filesystem will report an abnormal memory
usage due to the ZFS ARC cache. For example, on my workstation, the
ARC cache takes up 6GB out of the 16GB core memory. Total memory
usage, as reported by py3status, is close to 87%, quite alarming, but
when we *know* about the ZFS cache, this is no big deal.

Note that tools like `top(1)` also get it wrong, but `htop(1)` and
`btop(1)` don't. I actually took this idea from btop.

I didn't make this customizable because there's one of two things
here, either:

 1. the user doesn't have a ZFS setup and this will silently
    not change anything, or;

 2. the use *has* a ZFS setup and they will almost *certainly* want to
    count that out of their memory usage

btop(1) actually makes this configurable, but I think that's
superfluous: who would want to count that in anyways?

Obviously, this is kind of a flaw in the (Linux?) implementation of ZFS:
ZFS should use the normal caching systems of the operating system. But
considering how different that cache is, that might be practical (the
Linux memory cache is a LRU cache, and ZFS is an ARC cache).

I suspect this may also work on other ZFS implementations, but I
haven't tested those.

### CODE REVIEW

**Comment by ultrabug** [comment]
Hi @anarcat I sincerely apologize for the delay in getting back to you...

Thanks for this nice contribution, I don't know why some checks did not run on your PR. Did you make sure that this commit pass the py3status tests?

I agree with you in this added computation not needing to be configurable **but** I think we should catch all Exceptions when reading the ARC cache to accommodate with possible different setups. I'd rather report a bad number than break users' RAM reporting which they've been happy with so far.

Could you fix that please?

**Comment by anarcat** [comment]
> Thanks for this nice contribution, I don't know why some checks did not run on your PR. Did you make sure that this commit pass the py3status tests?

i did not, sorry.

> I agree with you in this added computation not needing to be configurable **but** I think we should catch all Exceptions when reading the ARC cache to accommodate with possible different setups. I'd rather report a bad number than break users' RAM reporting which they've been happy with so far.

What are you refering to here? Maybe this block?

```
                    m = ZFS_SIZE_REGEX.match(line)
                  if m:
                        return int(m.group(1))/1024
```

i guess i could handle `m.group` better and handle exceptions on failures to cast as an `int()`, anything else you had in mind?

**Comment by ultrabug** [comment]
L423 you could maybe just catch any Exception and ignore it

**Comment by anarcat** [comment]
isn't that considered bad practice?

**Comment by anarcat** [comment]
ack, wilco.

**Comment by anarcat** [comment]
i split the difference: i broadened the `FileNotFoundError` into `OSError`, which should catch any open/read-related error, and added a ValueError for the `int()` cast. I cannot think of *any* other exception this might raise, so we won't raise any with this *except* if someone changes the code in the future and introduces some Deprecation or SyntaxError....

i am okay with switching to a plain `Exception` if you really insist, but I cannot in good conscience just do that on my own. :p

**Comment by anarcat** [comment]
oh, and i just ran the test suite - looks like i had overlooked that in the first time, and now it passes. (i had to run `black`, otherwise things were okay.)

**Comment by ultrabug** [comment]
Congratulations, and most importantly thank you for your first contribution to py3status!

**Pull request merged**
