### PR TITLE
Added module for Project Hamster.

### PR DESCRIPTION
**Pull request by Spirotot**

### CODE REVIEW

**Comment by ultrabug** [comment]
Thanks a lot for your contribution @Spirotot !

The module you're proposing is for an old format of py3status modules, would you please update it to something more like https://github.com/ultrabug/py3status/blob/master/doc/example_module.py ?

Especially :
- your method should return a dict (no need of the position any more)
- try to use shlex like in the *taskwarrior* module : https://github.com/ultrabug/py3status/blob/master/py3status/modules/taskwarrior.py

The taskwarrior module is pretty similar to yours, I think you could almost copy/paste it for your PR ;)

Cheers

**Comment by Spirotot** [comment]
Sure, I will get on that soon! (Don't have much time during the week
unfortunately, so may not happen 'til next weekend.)

On Mon, Nov 23, 2015, 4:31 AM Ultrabug <notifications@github.com> wrote:

> Thanks a lot for your contribution @Spirotot <https://github.com/Spirotot>
> !
>
> The module you're proposing is for an old format of py3status modules,
> would you please update it to something more like
> https://github.com/ultrabug/py3status/blob/master/doc/example_module.py ?
>
> Especially :
>
>    - your method should return a dict (no need of the position any more)
>    - try to use shlex like in the *taskwarrior* module :
>    https://github.com/ultrabug/py3status/blob/master/py3status/modules/taskwarrior.py
>
> The taskwarrior module is pretty similar to yours, I think you could
> almost copy/paste it for your PR ;)
>
> Cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ultrabug/py3status/pull/142#issuecomment-158886756>.
>
-- 

-Aaron

**Comment by ultrabug** [comment]
Sorry @Spirotot, github does not send an update when you add commits to a current PR so I did not notice you made the changes !

I'll review ASAP !

**Comment by Spirotot** [comment]
Ah, sorry! I should have commented or something. Sounds good, though!

On Sun, Dec 6, 2015, 4:50 AM Ultrabug <notifications@github.com> wrote:

> Sorry @Spirotot <https://github.com/Spirotot>, github does not send an
> update when you add commits to a current PR so I did not notice you made
> the changes !
>
> I'll review ASAP !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ultrabug/py3status/pull/142#issuecomment-162292617>.
>
-- 

-Aaron

**Comment by ultrabug** [comment]
@Spirotot : just to know, did you make sure it works on python3 as well ? I don't have hamster so I can't test your module at all :(

**Comment by Spirotot** [comment]
I'm like 99% confident it works with Python3. I didn't _intentionally_ test
with Python3, but the system I developed this on uses Python3 as its
default Python interpreter, so I'm pretty sure that's what was being
used... I will set a reminder for myself to double-check tomorrow.

On Sun, Dec 6, 2015, 12:35 PM Ultrabug <notifications@github.com> wrote:

> @Spirotot <https://github.com/Spirotot> : just to know, did you make sure
> it works on python3 as well ? I don't have hamster so I can't test your
> module at all :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ultrabug/py3status/pull/142#issuecomment-162330926>.
>
-- 

-Aaron

**Comment by ultrabug** [comment]
Thanks @Spirotot ! then just plz make sure you can run it with both py2 & py3 from the command line

Cheers

**Comment by Spirotot** [comment]
Just ran it with Py3 and Py2, and it worked for both.

**Comment by ultrabug** [comment]
Awesome @Spirotot thanks a lot !

FYI : I will be doing some QA on your module for consistency AND to make it compatible with the `py3status modules details` command. So you might want to check it again on master soon. I'll ping you here when I'm done.

**Comment by Spirotot** [comment]
Cool, sounds good!!

On Tue, Dec 8, 2015 at 6:02 AM Ultrabug <notifications@github.com> wrote:

> Awesome @Spirotot <https://github.com/Spirotot> thanks a lot !
>
> FYI : I will be doing some QA on your module for consistency AND to make
> it compatible with the py3status modules details command. So you might
> want to check it again on master soon. I'll ping you here when I'm done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ultrabug/py3status/pull/142#issuecomment-162850842>.
>
-- 

-Aaron

**Comment by ultrabug** [comment]
@Spirotot done ! If you can, please try again with the version I refactored a bit which you can find on master now. Just in case I broke smthing ;)

**Pull request merged**
