### PR TITLE
Prometheus query module.

### PR DESCRIPTION
**Pull request by Wilm0r**
I'm still in your IRC channel, asked you a few questions there a while ago.

Hope I've got everything ready now. It's been working pretty flawlessly on my machines for 2w now. :-)

### CODE REVIEW

**Comment by Wilm0r** [comment]
OK, there are still some complaints about variable sorting, I kinda prefer the kind of natural/priority ordering I have now. Do you require all checks to be satisfied, or not?

**Comment by ultrabug** [comment]
@Wilm0r I apologize for the response delay

Thanks a lot for your first contribution to this project! Prometheus is indeed a great module to have :+1: 

Yes, we require those QA checks to pass please. As much as we understand and respect everyone's habits, we have set up those QA checks in order to get a better code consistency within the project.

Also; would you please elaborate on the `rotate_interval` and the corresponding rotation logic please?

**Comment by Wilm0r** [comment]
BTW screencast at https://gaa.st/~wilmer/.py3prom.ogv in response to some questions via IRC.

Waiting for agreement on whether to preserve this feature inside the module or not before also working on the other requests in this review. :)

**Comment by ultrabug** [comment]
As discussed on IRC with you, I'm waiting for your updates, thanks again!

**Comment by ultrabug** [comment]
Hello @Wilm0r ; I hope you're doing good!

Just checking in to get a little status update on your PR mate?

**Comment by Wilm0r** [comment]
Aw man, as good as it gets in these crazy times eh? /o\

Giving this a shot now. Have to strip out a lot of functionality :-( But what's left is hopefully enough for most users.

**Comment by Wilm0r** [comment]
Changed branch so I had to move this to a new PR: https://github.com/ultrabug/py3status/pull/1947

**Pull request closed without merging**
