### PR TITLE
Added geolocation support from ip-api.com

### PR DESCRIPTION
**Pull request by neutronst4r**

### CODE REVIEW

**Comment by tobes** [comment]
You shouldn't be changing the defaults or allowed options as that just breaks things for existing users.

Additionally you need to check your formatting to ensure the tests pass use `flake8`

**Comment by ultrabug** [comment]
Thanks @neutronst4r ! What @tobes said please :)

**Comment by neutronst4r** [comment]
I added geolocation as optional parameter and also added the option to color the as "good" when online. I fixed the flake8 issues. There are no more changes in the default options, all changes are keept to a minimum to add the new features.

**Comment by pydsigner** [comment]
Looks pretty good now, however, I think `url2` would be better as `geo_url` The parameter should be documented either way.

**Comment by tobes** [comment]
you could remove the geolocation parameter and use `if '{country}' in self.format:` to see which url to use.

**Comment by ultrabug** [comment]
please rebase mate, some major module doc rework got merged

**Comment by neutronst4r** [comment]
How to I resolve the conflicts? I Added the changes to the new base file in the master branch, but git says there are conflicts.

**Comment by tobes** [comment]
`git status` will show which files have conflicts

edit the files look for `<<<<` `====` `>>>>` this is where the conflict is

fix conflicts

`git add <file>`

`git commit`  (will be option to change commit message

done

**Pull request closed without merging**
