### PR TITLE
deadbeef: add sleep_timeout

### PR DESCRIPTION
**Pull request by lasers**
I used `deadbeef` for short time yesterday to help out someone and sometimes later, I forget I still have the module running in the bar when I saw too many `deadbeef` in the log. I wish to fix this.

We can make `deadbeef` relax more... so we're changing `cache_timeout` to `5` and we're adding new config `sleep_timeout = 20` where the module can sleep longer between intervals when it's not in use.

Before
```
Not in use..... 1 second..... 60 refreshes per minute.
In use.....  1 second..... 60 refreshes per minute.
```

After
```
Not in use..... 20 seconds..... 3 refreshes per minute.
In use.....  5 seconds..... 12 refreshes per minute.
```
Ty. 🎧

### CODE REVIEW

**Comment by lasers** [comment]
@tobes No room for potential clash in this one.

**Comment by tobes** [comment]
Hmm,  this is an interesting topic.

It is good that users have control over modules but also that they work sensibly when the user just leaves the defaults.  What is sensible depends on many factors.  Take this module.  If beadbeef is playing and we show the `{playback_time}` placeholder we probably want to refresh every second so that this info is correct.  And likewise when the track changes we want to show that change in a timely manner.  When nothing is happening we do not want to be wasting resources doing lots of updates.

This is also something we do in many places so I think we need to work out a nice way to do this for many modules and I like these solutions to need as little updating of modules as possible.

So I think we should think about this for a bit and see what ideas can be come up with by the community

**Comment by lasers** [comment]
`1` is an accident. When we fix up `deadbeef` months ago, I used `1` to test not only placeholders, but to test changes when I open/close deadbeef too... so this was just a number that should not be default in first place.

This should be noted that time placeholders is not part of default format... and because this uses new foobar2000 remapped metadata fields... The users likely does not know that they can use more time placeholders too... So I think we should at least not make `deadbeef` poll every `1` second for most users. I can at least think of 1 user.

**Comment by tobes** [comment]
because I'm in such a good mood today, I'll take this as is and we can look at the issue later but I won't merge any more like this until we have a nice general solution to this sort of problem

**Pull request merged**
