### PR TITLE
add new module: pew

### PR DESCRIPTION
**Pull request by lasers**
Hi. I made a new module ``pew``. :zap: 

The notifications does not always carry the same weight as i3bar urgents.

* I sometimes do not pay attention to notifications.
* I sometimes did not notice or just miss the notifications.
* Notifications sometimes appear on different monitor due to mouse cursor.
* Et cetera.

I pay attention to notifications more because of this simple module.
* Show summary/body with an urgent across all monitors.
* Can be customized (urgent, colors, min_length, etc).

pew-2018-10-24

### CODE REVIEW

**Comment by tobes** [comment]
@lasers mate you have 15 PRs open - This is not sustainable.

I cannot be involved in reviewing this many PRs at one time, especially as you do not seem to work on ones that I have been involved in eg  #1555 you have not addressed the issues mentioned.

Can we get this under control or I am going to have to stop being involved with your PRs

imho 5 open PRs is too many for one person as demonstrated by you not addressing issues.  It also grinds the whole process to a standstill

**Comment by lasers** [comment]
>especially as you do not seem to work on ones that I have been involved in eg #1555 you have not addressed the issues mentioned.

I finished that one. As for `kill py3status` thing, I can't reproduce this issue anymore and is too insignificant to look for the bug. I finished your request on undoing the names. This is pure cosmetic `--help` PR and can be closed instead. I made this to resolve #1550 asap.

>Can we get this under control or I am going to have to stop being involved with your PRs.

Okay, we can discuss on making `3.15` a `Get everything under control` milestone right after `core/enhancement` milestone. I'm awaiting reviews on several PRs which is also a serious problem.

**Comment by ultrabug** [comment]
I'm not in favor of adding this mate @lasers 

For the simple fact that I want a (re)work on dbus core handling first. Is that ok?

**Comment by lasers** [comment]
@ultrabug That's okay. I love this module. Lol. Saw your notification on my bar. ;-)

**Comment by ultrabug** [comment]
I tried it, my bar is now empty, nothing shows at all, this stuck py3status entirely for me :-1: 

As I said, I'm not in favor to add this one and would like a chance for a generic dbus support

**Pull request closed without merging**
