### PR TITLE
systemd: add config parameter to hide service extension

### PR DESCRIPTION
**Pull request by flyingapfopenguin**
Even if the systemd unit is addressed with '.service'-extension, it would be nice to save the space.

### CODE REVIEW

**Comment by ultrabug** [comment]
Thanks a lot @flyingapfopenguin 

Our variable convention is to use snake_case, could you rename your variables and options as such ?

hideExtension -> hide_extension

Cheers

**Comment by lasers** [comment]
(Q) If we have to specify a config to hide something, why don't we use `format = ssh: {status}`? I do not think users would change services often.

**Comment by flyingapfopenguin** [comment]
(A @lasers) Of course one can also edit the format string. But then one has to edit this string instead of setting a Boolean config variable to not get the format updated in the future if the default is changed.

**Comment by lasers** [comment]
@flyingapfopenguin Hi. I'm wondering if you had made any progress on this PR. Otherwise, I could take over on this implementation. We can add your name to `@author` too if you would like that too. \o/

**Comment by flyingapfopenguin** [comment]
@lasers Hey, I didn't make any progress. From my point of view, this PR is ready to merge. If you see anything to be done/discuss, we can do so or you can take over. In both cases, I don't care if my name is added to the authors.

**Comment by lasers** [comment]
For this PR, we already can ~~ab~~use `format = '[\?max_length=-8 {unit}]: {status}'`.

For the other PR, I want to expose (all) placeholders to keep everything in the `format` and to allow users to have non-colorized text too instead of everything always in constant general colors.

I also want to kill `cache_timeout` intervals in favor of listening to dbus signals (far fewer updates). There is a string thresholds PR that would help simplifying the `format` more too.

Sure, I'd like to take over. :100:

**Comment by ultrabug** [comment]
Thanks a lot @flyingapfopenguin for your contribution and patience!

**Pull request merged**
