### PR TITLE
Sysdata: only care about shown info for threshold

### PR DESCRIPTION
**Pull request by tobes**
a fix for issue #355

### CODE REVIEW

**Comment by ultrabug** [comment]
ping @Q3CPMA for testing plz.

**Comment by Q3CPMA** [comment]
Doesn't seem to work. I'm testing it by cloning into /tmp and putting `status_command python /tmp/py3status/py3status/__init__.py` in the config file.

**Comment by Q3CPMA** [comment]
(Of course, I didn't forget to fetch/checkout)

**Comment by tobes** [comment]
> cloning into /tmp

are you on the right branch?  I tested using your config and it worked as expected.

**Comment by Q3CPMA** [comment]
Yeah, I looked at the code manually, after that.

**Comment by Q3CPMA** [comment]
Example of problem a little more tangible:
`{"instance": "ram", "full_text": "RAM: 0.82 / 15.57", "color": "#FFFF00", "name": "sysdata", "cached_until": 1467134905.901781},{"instance": "cpu", "full_text": "CPU: 43.55", "color": "#FFFF00", "name": "sysdata", "cached_until": 1467134905.9035525}`

**Comment by tobes** [comment]
what version of python are you running it under?

if not python3 does that help the issue?

**Comment by Q3CPMA** [comment]
3.4.3

**Comment by tobes** [comment]
@Q3CPMA 

Can you fix your config and try again

you were using
```
sysdata ram
{
    cache_timeout = 1
    format = "RAM: {mem_used} / {mem_total}"
    high_treshold = "75"
    mid_treshold = "50"
}

sysdata cpu
{
    cache_timeout = 1
    format = "CPU: {cpu_usage}"
    high_treshold = "75"
    mid_treshold = "50"
}
```

it should be

```
sysdata ram
{
    cache_timeout = 1
    format = "RAM: {mem_used} / {mem_total}"
    high_threshold = 75
    med_threshold = 50
}

sysdata cpu
{
    cache_timeout = 1
    format = "CPU: {cpu_usage}"
    high_threshold = 75
    med_threshold = 50
}
```

You had the parameters for thresholds incorrectly named and they should be integers not strings

Can you confirm this fixes the issue for you

**Comment by tobes** [comment]
@Q3CPMA 
Could you attach your config (for sysdata and general sections) and the latest output.

cheers

**Comment by Q3CPMA** [comment]
Sure.
~/.i3statusconf
```
# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
        output_format = "i3bar"
        colors = true
        interval = 1
}

order += "mpd_status"
order += "run_watch DHCP"
order += "wireless wlp2s0"
order += "sysdata ram"
order += "sysdata cpu"
order += "uname"
order += "tztime local"

mpd_status
{
        cache_timeout = 1
        format = "%state% %artist% #│ [(%date%) ]%album% #│ %title% (%time%)"
}

sysdata ram
{
    cache_timeout = 1
    format = "RAM: {mem_used} / {mem_total}"
    high_threshold = 75
    med_threshold = 50
}

sysdata cpu
{
    cache_timeout = 1
    format = "CPU: {cpu_usage}"
    high_threshold = 75
    med_threshold = 50
}

wireless wlp2s0
{
        format_up = "W: (%quality at %essid) %ip"
        format_down = "W: down"
}

run_watch DHCP
{
        pidfile = "/var/run/dhcpcd*.pid"
}

tztime local
{
        format = "%Y-%m-%d %H:%M:%S"
}
```

```
cd ~/py3status/
git log -1
commit 2f9ab2089df7ceb8782aa200268ea4b8f29d9791
Author: Toby Dacre <toby.junk@gmail.com>
Date:   Tue Jun 28 14:17:04 2016 +0100

    sysdata only care about shown info for threshold
```
```
python ~/py3status/py3status/__init__.py -c ~/.i3status.conf
...
[{"instance": "", "cached_until": 1467208853.0906022, "full_text": "[play] Vinnie Moore \u2502 (1999) The Maze \u2502 King of Kings (5:48)", "name": "mpd_status", "transformed": false},{"instance": "DHCP", "full_text": "DHCP: yes", "name": "run_watch", "color": "#00FF00"},{"instance": "wlp2s0", "full_text": "W: (064% at WiFiExtender-f4068d757a82) 192.168.1.21", "name": "wireless", "color": "#00FF00"},{"instance": "ram", "cached_until": 1467208854.0771976, "full_text": "RAM: 0.98 / 15.57", "name": "sysdata", "color": "#FF0000"},{"instance": "cpu", "cached_until": 1467208854.080653, "full_text": "CPU: 77.50", "name": "sysdata", "color": "#FF0000"},{"cached_until": 1467212449.0829964, "full_text": "Linux 4.4.6-gentoo x86_64", "name": "uname", "instance": ""},{"full_text": "2016-06-29 16:00:53", "name": "tztime", "instance": "local"}]
...
```

**Comment by tobes** [comment]
There is another commit since that one, could you see if that helps.

```
$  git log --oneline 
e050ffa fix python2 division based errors
2f9ab20 sysdata only care about shown info for threshold
```

**Comment by Q3CPMA** [comment]
Tested again with full PR. Still the same colour.

**Comment by tobes** [comment]
hmmm,

This is frustrating.  I've added a couple of commits.  The first just makes thing a bit cleaner to read.  The second adds some debug logging.

If you run py3status with `-l /path/to/logfile` and then paste some of the log that would be great (especially where we cross thresholds) Hopefully that will show what's going on a bit better

**Comment by Q3CPMA** [comment]
I've run it like this `python ~/py3status/py3status/__init__.py -c ~/.i3status.conf -l py3status.log` but the log only contains
```
2016-06-30 12:00:36 INFO i3status spawned using config file /tmp/py3status_hy9g1b9b
2016-06-30 12:00:36 INFO loading module "mpd_status" from py3status.modules.mpd_status
2016-06-30 12:00:36 INFO loading module "sysdata ram" from py3status.modules.sysdata
2016-06-30 12:00:36 INFO loading module "sysdata cpu" from py3status.modules.sysdata
2016-06-30 12:00:36 INFO loading module "uname" from py3status.modules.uname
2016-06-30 12:00:51 ERROR i3status died with code -2
2016-06-30 12:00:51 ERROR [Errno 2] No such file or directory: '/tmp/py3status_hy9g1b9b'
```
(and the problem is still here, of course hehe)

**Comment by tobes** [comment]
hmm, should be seeing something like this


```
2016-06-30 10:17:07 INFO Module `sysdata cpu`: 8.499999999999996 (5/10) degraded CPU: 8.50
2016-06-30 10:17:08 INFO Module `sysdata ram`: 60 (50/75) degraded RAM: 2.26 / 3.76
2016-06-30 10:17:08 INFO Module `sysdata cpu`: 10.499999999999998 (5/10) bad CPU: 10.50
2016-06-30 10:17:09 INFO Module `sysdata ram`: 60 (50/75) degraded RAM: 2.26 / 3.76
2016-06-30 10:17:09 INFO Module `sysdata cpu`: 10.552763819095478 (5/10) bad CPU: 10.55
2016-06-30 10:17:10 INFO Module `sysdata cpu`: 11.5 (5/10) bad CPU: 11.50
2016-06-30 10:17:10 INFO Module `sysdata ram`: 60 (50/75) degraded RAM: 2.26 / 3.76
```

**Comment by Q3CPMA** [comment]
Yeah, I know. But I don't know why there's nothing. By the way, is ^C the normal way of stopping it?

**Comment by tobes** [comment]
> Yeah, I know. But I don't know why there's nothing. 

odd you are letting it run for a little while

> By the way, is ^C the normal way of stopping it?

yeah it is but it can take a while (Something I've wanted to fix but never got round too)

**Comment by tobes** [comment]
@ultrabug I've reverted the debug info commit.  I think that @Q3CPMA is not running this branch for some reason and that is why his issue remains.

Regardless, using the following config master has the described issue and this branch does not.  So it fixes a real issue.

```
general {
        output_format = "i3bar"
        colors = true
        interval = 1
}

order += "sysdata ram"
order += "sysdata cpu"

sysdata ram
{
    cache_timeout = 1
    format = "RAM: {mem_used} / {mem_total}"
}

sysdata cpu
{
    cache_timeout = 1
    format = "CPU: {cpu_usage}"
}
```

**Comment by ultrabug** [comment]
Okay I see, thanks a lot guys !

**Pull request merged**
