### PR TITLE
timew: fix future bug caused by copy and paste

### PR DESCRIPTION
**Pull request by lasers**
> no time like the present, there's

### CODE REVIEW

**Comment by tobes** [comment]
please describe the problem that this is fixing - also what is a future bug?

**Comment by lasers** [comment]
There will be a bug if I don't fix it now...  therefore I fix a future bug.

I copied + pasted threshold lines from `loadavg` to `timewarrior`. The `self.load_data` dict doesn't exist anywhere in this module so I renamed the dict to `timew_data`.

**Comment by tobes** [comment]
ok so it is a current bug then :)

**Comment by tobes** [comment]
>  the timewarrior command is timew too.

ok good enough argument I'll merge

**Comment by tobes** [comment]
thanks

**Pull request merged**
