### PR TITLE
GLPI: Add cache_timeout

### PR DESCRIPTION
**Pull request by pferate**
Setting default cache_timeout to 5 minutes.

Resolves: #497

### CODE REVIEW

**Comment by tobes** [comment]
Thanks for this PR.

The config parameters in both the class and the docstring should be in alphabetical order.  If you could fix that it would be great.

**Comment by pferate** [comment]
No problem.  Shouldn't `test_module_doc.py` catch that?  It says that it does:

> * config parameters listed in alphabetical order

I can try to look into that to see if there is a problem in the test.  I had some other ideas for testing that I'll post in IRC for some opinions.

**Comment by tobes** [comment]
> I can try to look into that to see if there is a problem in the test. 

PR #499 improves the tests so probably worth waiting till that is merged or dropped.

>  I had some other ideas for testing that I'll post in IRC for some opinions.

this sounds good we could do with more

**Comment by pferate** [comment]
@tobes: PR has been updated.

**Comment by tobes** [comment]
> I can try to look into that to see if there is a problem in the test. 

The reason is that this module has dependencies and so can't be imported without them installed.  the updated test used ast so doesn't need to import the module.  So currently this is blacklisted from the docstring tests.

**Comment by pferate** [comment]
I see.  The current tests only check the docstrings, but not the actual modules, right?  What do you think of running the modules during the unit tests?  Obviously, those dependencies would need to be installed for testing, but we could add them to a `requirements-dev` or something similar.

Locally, I added a `test_modules.py` and modified the `module_test.module_test()` to run once, rather than continuously.  It has a lot a failures right now, but once it gets all massaged, it would be trivial to test in py2 and py3, as well as handle any regression.

That was one of the things I was going to bring up in IRC.

**Comment by tobes** [comment]
> What do you think of running the modules during the unit tests? 

I think this would be good I have done some work in branch `tests-modules` some modules are just hard to test.  So I have the basics.  It has sort of stalled around dbus as I want to test modules using pydbus.

The issue is around python-gi not being a proper module.  I've been hacking on pydbus to get it to be independent of python-gi but need to do some more I've got glib working but need to get Gio and MainLoop sorted.

**Comment by pferate** [comment]
> I think this would be good I have done some work in branch `tests-modules`

Thanks, I'll take a look at that branch

> some modules are just hard to test.

I agree.  It will be a process to get them all covered.

**Comment by ultrabug** [comment]
Thank you so much @pferate !

**Pull request merged**
