### PR TITLE
add new module: twitchy

### PR DESCRIPTION
**Pull request by lasers**
Hi. I made a new module `twitchy`. :purple_heart: This requires @BasioMeusPuga's [twitchy](https://github.com/BasioMeusPuga/twitchy).

Because `twitchy` is a command-line interface tool, we can add channel names to our database instead of specifying them in the config. We can delete them later too. `twitchy` makes it easy for users to manage number of channel names so I figure we could use this tool.

`twitchy` also offer other things like opening your favorite channel with `mpv` or searching for channel name in the database, but that's not what I'm doing here. I'm using this to display online channels.

Because we can add many channel names as we want, this will be scrollable. The screenshots illustrates how it looks when we have four channels currently streaming. It optionally can display number of viewers and streaming time too.

@cyrinux Can you review this? Thanks. :blush: 

twitchy-1
twitchy-2
twitchy-3
twitchy-4

### CODE REVIEW

**Comment by cyrinux** [comment]
yeah sure, will try this thx 👍

**Comment by cyrinux** [comment]
"Works well for me :)"

But

If twitchy db is empty, the returned error is not clear, not a module problem but maybe we need to catch the error for the moment with a message like unconfigured or empty channel list.

{code}
❯ twitchy --non-interactive
Traceback (most recent call last):
  File "/usr/bin/twitchy", line 11, in <module>
    load_entry_point('twitchy==3.4.0', 'console_scripts', 'twitchy')()
  File "/usr/lib/python3.7/site-packages/twitchy/__main__.py", line 392, in main
    non_interactive('get_online', delimiter=args.delimiter)
  File "/usr/lib/python3.7/site-packages/twitchy/__main__.py", line 242, in non_interactive
    id_string_list = [str(i[0]) for i in channel_data]
TypeError: 'NoneType' object is not iterable
{code}

Also, would be cool to be able to be able to change the default player, to open the stream like the default twitchy behavior, in mpv for eg, and not throught xdg-open. Will try more asap.

**Comment by lasers** [comment]
@cyrinux I'm not sure if I want to expose `command` option. I was thinking about sticking with `xdg-open` and if users really want `mpv` or such, then they could open a terminal and type `twitchy` or `twitchy --hanselgretel`, enter, press a number, enter, done. That's what `twitchy` is for after all.

**Comment by cyrinux** [comment]
> @cyrinux I'm not sure if I want to expose `command` option. I was thinking about sticking with `xdg-open` and if users really want `mpv` or such, then they could open a terminal and type `twitchy` or `twitchy --hanselgretel`, enter, press a number, enter, done. That's what `twitchy` is for after all.

In that case, instead of xdg-open, can you invoke "twitchy -w channel" ?

**Comment by lasers** [comment]
Invoking `twitchy -w channel` still prompts me with a number to pick.

**Comment by cyrinux** [comment]
> Invoking `twitchy -w channel` still prompts me with a number to pick.

yes, we need to patch twitchy

**Comment by lasers** [comment]
This works. `$ twitchy --hanselgretel --noconfirm -w cyrinux`. 
```diff
diff --git a/twitchy/__main__.py b/twitchy/__main__.py
index a61d2f5..b47f0da 100755
--- a/twitchy/__main__.py
+++ b/twitchy/__main__.py
@@ -126,7 +126,7 @@ def database_modification(option, database_search=None):
                 criteria_dict)
 
 
-def watch_channel(mode, database_search=None):
+def watch_channel(mode, database_search=None, noconfirm=False):
     if mode == 'watch':
         # database_search is expected to be a list
         # exact names of the channels the user wants to watch
@@ -195,9 +195,20 @@ def watch_channel(mode, database_search=None):
     if not channels_online:
         raise YouAndTheHorseYouRodeInOn(' All channels offline.')
 
-    final_selection = twitchy_display.GenerateWatchTable(
-        channels_online).begin()
-    print(' q / Ctrl + C to quit \n Now watching:')
+    if noconfirm:
+        first = database_search[0]
+        quality = Options.video.default_quality
+        for name in channels_online:
+            if first == name:
+                final_selection = channels_online
+                final_selection[name]['quality'] = quality
+                break
+
+    else:
+        final_selection = twitchy_display.GenerateWatchTable(
+            channels_online).begin()
+        print(final_selection)
+        print(' q / Ctrl + C to quit \n Now watching:')
     twitchy_play.play_instance_generator(final_selection)
 
 
@@ -360,6 +371,10 @@ def main():
         help='Watch specified channel(s)',
         metavar='<channel>')
 
+    parser.add_argument(
+        '--noconfirm', action='store_true', help='Watch first channel'
+    )
+
     args = parser.parse_args()
 
     if (args.s or args.v) and args.searchfor:
@@ -406,7 +421,7 @@ def main():
         watch_vods(args.v)
 
     elif args.w:
-        watch_channel('watch', args.w)
+        watch_channel('watch', args.w, args.noconfirm)
 
     else:
         watch_channel(None)
```

**Comment by cyrinux** [comment]
> This works. `$ twitchy --hanselgretel --noconfirm -w cyrinux`.
> 
> ```diff
> diff --git a/twitchy/__main__.py b/twitchy/__main__.py
> index a61d2f5..b47f0da 100755
> --- a/twitchy/__main__.py
> +++ b/twitchy/__main__.py
> @@ -126,7 +126,7 @@ def database_modification(option, database_search=None):
>                  criteria_dict)
>  
>  
> -def watch_channel(mode, database_search=None):
> +def watch_channel(mode, database_search=None, noconfirm=False):
>      if mode == 'watch':
>          # database_search is expected to be a list
>          # exact names of the channels the user wants to watch
> @@ -195,9 +195,20 @@ def watch_channel(mode, database_search=None):
>      if not channels_online:
>          raise YouAndTheHorseYouRodeInOn(' All channels offline.')
>  
> -    final_selection = twitchy_display.GenerateWatchTable(
> -        channels_online).begin()
> -    print(' q / Ctrl + C to quit \n Now watching:')
> +    if noconfirm:
> +        first = database_search[0]
> +        quality = Options.video.default_quality
> +        for name in channels_online:
> +            if first == name:
> +                final_selection = channels_online
> +                final_selection[name]['quality'] = quality
> +                break
> +
> +    else:
> +        final_selection = twitchy_display.GenerateWatchTable(
> +            channels_online).begin()
> +        print(final_selection)
> +        print(' q / Ctrl + C to quit \n Now watching:')
>      twitchy_play.play_instance_generator(final_selection)
>  
>  
> @@ -360,6 +371,10 @@ def main():
>          help='Watch specified channel(s)',
>          metavar='<channel>')
>  
> +    parser.add_argument(
> +        '--noconfirm', action='store_true', help='Watch first channel'
> +    )
> +
>      args = parser.parse_args()
>  
>      if (args.s or args.v) and args.searchfor:
> @@ -406,7 +421,7 @@ def main():
>          watch_vods(args.v)
>  
>      elif args.w:
> -        watch_channel('watch', args.w)
> +        watch_channel('watch', args.w, args.noconfirm)
>  
>      else:
>          watch_channel(None)
> ```

Nice! Will try asap.

**Comment by cyrinux** [comment]
Works as i expect with your patch 

```            if button == self.button_open:
                index = event["index"]
                if not isinstance(index, int):
                    self.py3.command_run(
                        "twitchy --hanselgretel --noconfirm -w {}".format(
                            index))
```

**Comment by BasioMeusPuga** [comment]
Hey,
I got a notification for this. You don't need `-w` if you just want to watch something. `twitchy --non-interactive kickstart <stream name>` already does what you want.

**Comment by lasers** [comment]
Closing in favor of https://github.com/BasioMeusPuga/twitchy/pull/30. Still a better Twitch module than `twitch`.

**Pull request closed without merging**
