### PR TITLE
add new module: external.py

### PR DESCRIPTION
**Pull request by lasers**
Hi.

### CODE REVIEW

**Comment by tobes** [comment]
you know there is https://github.com/ultrabug/py3status/blob/master/py3status/modules/external_script.py

what do you offer that cannot be done there or it be adapted?

also

`color` is magic and just works - delete it from your module to see.

`symmetric` should be done by the formatter we have `\?max_length`

**Comment by tobes** [comment]
`subprocess` should also be avoided `self.py3.command_output` is your friend

**Comment by lasers** [comment]
This works with xsel, xclip, etc and is less annoying than `external_script.py`. if I put `xsel -o` in there, it'll trip up on multi-lines and notify the user. This will display the warning string instead (in color_bad).

I tried `self.py3.command_output`. It does not work with `~/.bin/some_script.sh` and was annoying to spell out the whole path (which means this could break the `external_script` if you were to update it to use `self.py3.command_output`).

I didn't know about `color`. Will try. Having all those options make this more friendly than having users looking up documentations.

Does the formatter support `strip_whitespace` too? Seems like a possibility.

**Comment by tobes** [comment]
> This works with xsel, xclip, etc and is less annoying than external_script.py. if I put xsel -o in there, it'll trip up on multi-lines and notify the user. This will display the warning string instead (in color_bad).

ok but we could get external_script to allow such things I think with little work

> I tried self.py3.command_output. It does not work with ~/.bin/some_script.sh and was annoying to spell out the whole path (which means this could break users's py3status external_script if you were to update it to use self.py3.command_output).

ok so we should fix this the `~` is easy to fix

> I didn't know about color. Will try. Having all those options make this more friendly than having users looking up documentations.

there is a simple section on colors https://github.com/ultrabug/py3status/blob/master/doc/README.md#configuring_color

but the comment was more for module configs `color_..` is bad.

> Does the formatter support strip_whitespace too? Seems like a possibility.

no but it could easily learn `trim`

**Comment by lasers** [comment]
Removing color indeed works... except that I don't get `py3.COLOR_BAD`.

**Comment by tobes** [comment]
> except that I don't get py3.COLOR_BAD.

you'd need to set that explicitly in the response.

Anyhow I still think you'll have a hard time getting this through as a duplicate module when we can fix up external_script

**Comment by lasers** [comment]
Sure. I started off looking at `xsel`, I think I have the `fix-xsel` branch with working code. Need to add format stuffs too. This works right now.

One tiny thing. When error, I get `external: too many newline` (missing last letter). Other than that, it's completed. It's okay if this does not go in. 👍

**Comment by tobes** [comment]
> I get external: too many newline

yeah because you trim it.

Anyhow the real point is to fix external_script rather than duplicate stuff.

I think there are some good ideas here but some should be done through the formatter like trimming (so available in all modules) and some by updating core/py3

**Comment by lasers** [comment]
I made `external` because of subprocess not wanting to break somebody's `~/.bin/script`. 
We can close this in favor of fixing up `external_script`. Maybe `external` can be renamed to simply take over `external_script` with small modifications.

**Comment by tobes** [comment]
> I tried self.py3.command_output. It does not work with ~/.bin/some_script.sh 

this issue is because you have a path that needs to do `os.path.expanduser()` now the thing to note is that a path is not the same as a command

**Comment by lasers** [comment]
Similar issue to **xsel: Fix xsel #664** arises using this external module blaming this line.
```
output = subprocess.check_output(self.command, shell=True, universal_newlines=True)
return {'full_text': 'moo'}
```
```
2017-01-15 09:56:54 ERROR py3status: Instance `external xsel`, user method `external` failed (CalledProcessError) external.py line 56. Please try to fix this and reload i3wm (Mod+Shift+R)
2017-01-15 09:56:54 INFO lock cleared, exiting
2017-01-15 09:56:55 INFO ========
2017-01-15 09:56:55 INFO Starting py3status version 3.4rc0 python 3.6.0
2017-01-15 09:56:55 INFO git branch: add-external
2017-01-15 09:56:55 INFO git commit: 20de2a2 add new module: external.py
2017-01-15 09:56:55 INFO py3status started with config {'cache_timeout': 60, 'interval': 1, 'minimum_interval': 0.1, 'dbus_notify': False, 'include_paths': ['/home/chris/src/py3status/py3status/modules'], 'version': '3.4rc0', 'debug': True, 'log_file': '/tmp/py3status-top.log', 'standalone': False, 'i3status_config_path': '/home/chris/.config/i3/i3status-py3status.play'}
2017-01-15 09:56:55 INFO i3status thread mocked with config {'general': {'color_bad': '#FF0000', 'color_degraded': '#FFFF00', 'color_good': '#00FF00', 'color_separator': '#333333', 'colors': False, 'interval': 5, 'output_format': 'i3bar'}, 'order': ['static_string APPLE', 'external xsel'], 'static_string APPLE': {'format': 'APPLE', 'color': '#ffffff'}, 'external xsel': {'cache_timeout': 1, 'command': 'xsel', 'color': '#ffaaff', 'color_bad': '#ff0000', 'strip_whitespace': True}, 'on_click': {}, 'i3s_modules': [], 'py3_modules': ['static_string APPLE', 'external xsel'], '.module_groups': {}}
2017-01-15 09:56:55 INFO events thread started
2017-01-15 09:56:55 INFO user_modules={'external': ('/home/chris/src/py3status/py3status/modules/', 'external.py'), 'static_string': ('/home/chris/src/py3status/py3status/modules/', 'static_string.py')}
2017-01-15 09:56:55 INFO loading module "static_string APPLE" from /home/chris/src/py3status/py3status/modules/static_string.py
2017-01-15 09:56:55 INFO module "static_string APPLE" click_events=False has_kill=False methods=odict_keys(['static_string'])
2017-01-15 09:56:55 INFO loading module "external xsel" from /home/chris/src/py3status/py3status/modules/external.py
2017-01-15 09:56:55 INFO module "external xsel" click_events=False has_kill=False methods=odict_keys(['external'])
2017-01-15 09:56:55 INFO method static_string returned {'full_text': 'APPLE', 'instance': 'APPLE', 'name': 'static_string'} 
2017-01-15 09:56:56 INFO lock cleared, exiting
2017-01-15 09:56:56 WARNING Instance `external xsel`, user method `external` failed (CalledProcessError) external.py line 56.
2017-01-15 09:56:56 INFO Traceback
CalledProcessError: Command 'xsel' died with <Signals.SIGTERM: 15>.
  File "/home/chris/src/py3status/py3status/module.py", line 584, in run
    response = method()
  File "/home/chris/src/py3status/py3status/modules/external.py", line 56, in external
    universal_newlines=True)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)

2017-01-15 09:56:56 ERROR py3status: Instance `external xsel`, user method `external` failed (CalledProcessError) external.py line 56. Please try to fix this and reload i3wm (Mod+Shift+R)
```

**Comment by lasers** [comment]
Closing in favor of refitting `external_script` and other modules with `helpers`... and for simple features to be extended to all modules instead of one... usually done via the formatter or ~~in other 'universal` ways~~ with more magic from @tobes.

**Pull request closed without merging**
