### PR TITLE
Made CPU temp work with Ryzen CPUs

### PR DESCRIPTION
**Pull request by BomBardyGamer**
As the title says, makes CPU temp work with Ryzen CPUs. This is from and old patch made by my good friend @kacgal so all credit goes to him, he just didn't want to make the change to the upstream, so I've made it instead.

Let me know if you have any issues.

### CODE REVIEW

**Comment by ultrabug** [comment]
Thanks for stepping up and contributing @BomBardyGamer !

Unfortunately it seems that your regex change does break the temperature detection for other CPUs. If I use your module, my temp goes to flat 100.0 :(

**Comment by BomBardyGamer** [comment]
Thanks for this, as you probably know, it's quite difficult to test this on other CPUs, so it's good that you've been able to do this. Will look in to it.

**Comment by su8** [comment]
Why don't u havé two separate regéxés for intél and amd ¿

**Comment by BomBardyGamer** [comment]
That is a good point

**Comment by lasers** [comment]
@BomBardyGamer What does `sensors -u` output? Thx.

**Pull request closed without merging**
