### PR TITLE
screenshot: Add enhancement

### PR DESCRIPTION
**Pull request by lasers**
Closes https://github.com/ultrabug/py3status/issues/625. 

~~* This adds format: // (default 'SHOT')~~
~~* This adds format_screenshot: // (default '{filename}')~~

This enhances on_click feedback.
* Stop taking rapid screenshots with scrolling wheel up/down.
* Stop taking screenshots with middle button or right button.
* Make the {filename} go away with middle or right button instead of leaving it there.
* Updates new default: format: // (default '{format_ss} 📷 Screenshot')
* Updates new default: format_ss: // (default '{filename}')

Ongoing efforts to `FORMAT ALL THE THINGS!` (meme). https://github.com/ultrabug/py3status/issues/98

### CODE REVIEW

**Comment by lasers** [comment]
All ready to go. I think `push = True` to push your screenshot to server should be `False`. I see somebody's server in that URL. No idea if it works... but wouldn't want risk having users accidentally uploading sensitive stuffs to there with default screenshot options.

**Comment by tobes** [comment]
We don't generally like changing behaviour for users and your defaults do this.  Also some unicode chars are not well supported across fonts, I suspect the camera maybe among these.  So adding the format is ok but the default should give the current behaviour and the user then can set it how they wish.

The on click behaviour seems to have been changed too again this affects current users.

Also just be aware of #594 which is also making changes to this module

**Comment by lasers** [comment]
I can drop last two commits and that will be it.

All onclick behaviours takes screenshot. (Up, down, left, right, middle), leaves format... to format_screenshot... and when you're done, that filename will stay there with zero option to make it go away. 

New behaviour will allow you to take shot with left click. All other clicks will reset the message back to format (after you do your quick glance and know what file it is under). I have several screenshots from scrollwheeling.

I can replace/omit the unicode, rephrase the format, or just remove the last commit. Let me know how many last commits you would like me to drop. Will look at somebody's PR.

(I still suggest to turn Push off by default ; One would hate to not know and constantly upload personal/banking screenshots to somebody's www by just scrolling on this icon).

**Comment by raspbeguy** [comment]
Yeah, indeed I still plan to finish #594 but I have personnal stuff to finish first.

**Comment by lasers** [comment]
@tobes Idk wat to do.
```
`path` (default 'UNKNOWN BinOp BinOp Mod') does not match docstring u'~/Pictures/'`
```

**Comment by tobes** [comment]
In the test error it says

> The tests may give incorrect errors for some configuration parameters that the tests do not understand. Such parameters can be excluded from the test by adding them to the IGNORE_ITEM list in tests/test_module_doc.py

I'd not worry too much as

a) I'd like to see #594 merged first (and you'll get massive merge conflicts)

b) I think you are trying to change a lot of stuff that maybe doesn't need it.

c) there are other ways to achieve some of these things that I think would be better (not that I'm always right)

**Pull request closed without merging**
