### PR TITLE
sysdata: add htop-like memory usage

### PR DESCRIPTION
**Pull request by lasers**
This introduces a new option `mem_htop` to print `htop`-like values for `{mem*` placeholders.

* I'd like your opinions on replacing this without a config.
* I'd like your opinions on defaulting this new option.

Addresses #666.

### CODE REVIEW

**Comment by ultrabug** [comment]
> I'd like your opinions on replacing this without a config.

replacing what?

> I'd like your opinions on defaulting this new option.

I'm never in favour unless it expands user experience

That means that I would like some example outputs to compare plz

**Comment by ultrabug** [comment]
Ok I tried and erm...

without htop:
`Mem: 3.99/15.53 GiB (25.69%)`

with htop:
`Mem: 12.66/15.53 GiB (92.71%)`

This is confusing, but looking at `free -h` shows that indeed I have 2GiB free RAM so htop is the closest to the truth

Does that mean that the current implementation is wrong?...

**Comment by lasers** [comment]
I don't know if it is wrong. I didn't study this. It could be just different or even outdated. 

I personally think it'd be more nice if we don't offer this option in first place. Swap it out and everybody should have more accurate `Mem: ` readings in sync with `htop`. If somebody come back complaining about this, then we could add the old `Mem:` behavior back in... :bomb:

**Comment by ultrabug** [comment]
I'd like a real user of sysdata module input before deciding on this.

Else, I agree with you and would do exactly the same.

**Comment by lasers** [comment]
I have removed the config if you want to merge this now. I think it would be a good move for the users.

**Comment by tobes** [comment]
> Does that mean that the current implementation is wrong?...

I think the problem is there are many different definitions - do I count `cache` etc anyhow been a long time since I looked at this issue

sysdata is a monster

**Comment by maximbaz** [comment]
I think htop is showing the sum of `used + shared` in what `free -h` is showing, but I might be wrong 🙂 

At any rate, I support this PR, being consistent with `htop` sounds like a very good idea.

**Comment by lasers** [comment]
@maximbaz Thank you for chiming in. :+1: We still need more feedback.

@cyrinux @dconathan @guiniol @JohnAZoidberg @raspbeguy  @su8 @valdur55

You all might be using `sysdata`. We need more people chiming in on this issue. Thx.

**Comment by cyrinux** [comment]
I prefer htop version which seems to consider shared_mem. But, yes, it is a running problem.
Cache memory cache be freed, shared memory is allocated memory like used. used + shared seems to me a good sum very near from thrust.

**Comment by guiniol** [comment]
Eyeballing it on my system, I don't see a large difference, so I'm fine with using the same value as htop.

**Pull request merged**
