### PR TITLE
wifi_nm: Display WiFi info using NetworkManager.

### PR DESCRIPTION
**Pull request by devkev**
Suggested new module which reports wifi info using `nmcli`, rather than `iw`.

### CODE REVIEW

**Comment by devkev** [comment]
I've been sitting on this code for a while now (well over a year), and it looks like there are some style issues (and possibly more) that need fixing.  Happy to make the necessary updates.

**Comment by ultrabug** [comment]
Thanks a lot @devkev.

I think the best way to go would be to add this as an option to the existing `wifi` module. Would you be interested to do so?

Cheers

**Comment by lasers** [comment]
Alternative approach: Replace `wifi` with this module.

I'm not sure if it's better or just different (e.g. fewer lines, single cmd querying, fewer requirements (i.e. no `sudo`, no additional binaries, etc).

The thing to ponder is if users actually prefer to use `iw` + optional `ip` instead of `nmcli` (usually already installed via `networkmanager` to keep it {c,}lean. Also, maybe `nmcli` have more goodies we can use (such as IP addresses and others).

Otherwise, I think `nmcli` would be a better module name instead of `wifi_nm`.

**Comment by lasers** [comment]
This supports more devices (instead of just wifi) + more fields. Dunno if it's better. https://github.com/lasers/py3status/tree/newmodule-networkmanager [wip]. Feedback welcome.

**Comment by maximbaz** [comment]
> The thing to ponder is if users actually prefer to use iw + optional ip instead of nmcli (usually already installed via networkmanager to keep it {c,}lean. Also, maybe nmcli have more goodies we can use (such as IP addresses and others).

For example I do prefer to use `iw` and `ip` because I use connman instead of networkmanager, so installing `nmcli` kinda feels weird, and I'm not even sure it will be able to recognize connections made by connman 🙂

**Comment by ultrabug** [comment]
I'd also rather stay as close to vanilla tools as possible instead of going after a network manager daemon

**Comment by lasers** [comment]
What about a new module `networkmanager` because it can handle `ethernet` too? My branch still need some more work / polishing to do. Then OP could use `networkmanager` instead.

If all OP use is laptop + wifi, then it'd effectively work same as `wifi` + `nmcli`.

**Comment by ultrabug** [comment]
Sure @lasers why not.. if OP is interested only tho

**Comment by lasers** [comment]
@devkev Hi, can you review a new module `networkmanager` to see if it'd be better to use that module versus your PR? We need to know where you stand before doing anything here. Thank you!

**Pull request merged**
