### PR TITLE
add new module: cmus

### PR DESCRIPTION
**Pull request by lasers**
I looked at `cmus` from `i3py3status`. Made one for py3status.

`cmus-remote` offers ton of buttons to click so I tossed them all in.
The `--volume` and `--seek` options are quite nice for scrolling wheel.

We get metadata directly from `cmus` so there are quite lot of placeholders and I likely didn't get them all... due to missing metadata in songs, Internet radio stations and such.

This makes it a fun module to use. Please let me know if you have any questions. Thx.

### CODE REVIEW

**Comment by ultrabug** [comment]
As I'm no user of cmus, I must say that I have no opinion on your points I'm sorry.

If you would use this module as a cmus user, then it's okay as-is, I trust your judgement mate.

Tell me.

**Comment by lasers** [comment]
@ultrabug @tobes I do not know how you feel about `button = {dict}` or `cache_timeout = [list]` to weed out number of button options. 

I thought about turning cache_timeout into a dict too (eg `cache_timeout = {'cache': 5, 'sleep': 20, 'request': 5}` assuming most people won't care about `request_timeout`. If users input `cache_timeout = 5`, then it's assumed `5` for all three.

I did the same thing (button + cache_timeout) with `moc`.

**Comment by ultrabug** [comment]
Ok now that I understand better your point then I'm sorry but I do not want to see a dict or list on those configuration options.

Giving power to the users is one thing but I see this as over complicating things. Simple is better please.

**Comment by lasers** [comment]
Fixed.

**Comment by ultrabug** [comment]
One last thing mate, what is this sleep_timeout setting that you use as cache_timeout? please stick with cache_timeout?

**Comment by lasers** [comment]
When `cmus` is not running, it will use `sleep_timeout = 20`. Otherwise, it will use `cache_timeout = 5`. If people want to add `{duration*}` or `{position*}`, they could set `cache_timeout = 0` so the elapsed time will iterate without any problem on the statusbar.... but they are not always going to run `cmus`... then it would be stupid to have it updated `0` all times. I added this for `moc` too.

**Comment by ultrabug** [comment]
Okay then I agree but make it clear on the docstring plz that sleep_timeout is used when cmus is not running

**Comment by lasers** [comment]
I trimmed things. If you want me to remove `sleep_timeout` and we use `cache_timeout` here. Let me know. 👍

**Comment by ultrabug** [comment]
Thanks, good as is :)

**Pull request merged**
