### PR TITLE
Use absolute path for iw

### PR DESCRIPTION
**Pull request by paradoxisme**
iw is not is the PATH in debian 9.
I propose to use /sbin/iw instead.

### CODE REVIEW

**Comment by tobes** [comment]
this will break things for me as my path is `/usr/sbin/iw`.

We can do a search for it and use the one we find.

eg
```
self.iw_cmd = self.py3.check_commands(['iw', '/sbin/iw'])
...
cmd = [self.iw_cmd, 'dev']
```

**Comment by paradoxisme** [comment]
OK, I've tried and it's work well with check_commands().

**Comment by tobes** [comment]
is `ip` good for you?  you changed that in your first commit

**Comment by lasers** [comment]
IIRC last time I used Debian, you have to use `use_sudo = True` along with required root rights without a password for `iw` before it can check a command since it's located in `/sbin` (System administrative binaries). For other distros, probably no problem checking.

Can you try this first (since you might have to use `use_sudo` one way or another) ?

**Comment by paradoxisme** [comment]
yes ip is good for me in no root privilege. It's a mistake.
I've tried to add  use_sudo = True in my configuration file. I should to add <use_names>  ALL=(ALL) NOPASSWD: /sbin/iw dev wl* link in my sudoers files (like that explain in documentation). After that, it's work fine. But I think it's more complicated for users. No root access seems needed for reading. The problem is just the PATH ? What do you think ?

The path for iw in my debian 9 is /sbin/iw.

**Comment by tobes** [comment]
If this allows things to work on debian by default then I think it's worth taking.

**Comment by lasers** [comment]
The users might not notice this, but some placeholders would not be available without the root rights. I think maybe `{signal_dbm}` and `{signal_percent}`. Some users might like percent. Otherwise, `0`? 

If we add this, then (debian|possibly other) users may not realize that they would need the root rights to fully access the information. Also, how would the users know if they set up the root rights correctly? 

I guess this trips on `try/except` so there was an error code.... probably bad command because no `sudo` and/or `iw` is not recognized in the PATH.. because `iw` often requires `sudo` for some tasks. 

We switch from`not_working` to (until we get the sudoers bit working correctly) `working_fully`... to...  `partially_working` to either `partially_working` (if left not configured) or `working_fully` (only that if the users might have hard time knowing if they set it up correctly because of sticky sudoers situation).

> No root access seems needed for reading

@paradoxisme Can you paste...
```
sudo -k
/sbin/iw dev <wifi_interface> link
```
and...
```
sudo -k
sudo /sbin/iw dev <wifi_interface> link
```
There should be some diff in there that will require the root rights. Maybe just `signal` information.

**Comment by ultrabug** [comment]
This is a separate issue, thanks a lot for this @paradoxisme !

**Pull request merged**
