### PR TITLE
add new module: switch

### PR DESCRIPTION
**Pull request by lasers**
Hi. I made a new module `switch`. This module is made to work commands and/or scripts. The users can switch things by making a list of 2-tuples, then we switch through the list via  scrolling or clicking... And we can go through the list in a loop manner or in a range manner (default). There won't be any feedback from whatever it is that we're trying to control... and I was able to emulate basic functionality of many modules with this. Thanks. 👍 🎮 
 
py3status-switch

### CODE REVIEW

**Comment by lasers** [comment]
One thing I'd like to fix here... An ability to launch applications from the list too.

**Comment by lasers** [comment]
@tobes. This can go in now. I have nothing else to do. Popen looks good?

**Comment by lasers** [comment]
@ultrabug If you want to merge more, this could go in now.

**Comment by ultrabug** [comment]
Are you still backing this one?

**Comment by lasers** [comment]
I think it's worth to add this... The potential is there for users to do what they wanted. I need to see if I can work on this some more to make it less biased with controls. I'd like to figure out how I can evaluate ` ~/home` and/or `$HOME`... and be able to launch apps without freezing py3status.

**Comment by tobes** [comment]
This is a nice idea but I think we should think about it a bit more, and make the code nicer.  Some comments 

I think we should start new blocking modules that are not clear because they will create a huge technical debt/support nightmare (this is not a comment specific to this module)

**Comment by lasers** [comment]
@ultrabug Yes. `switch` is literally what it all does. It's a generic module like `frame`, `group`, etc. If users have two options or more, they only can assign each to a button. With this, users can add as many as they want... They can either click on it... or make it active on each switch.

This already can behave like `dpms`, `volume_status`, `hueshift` that works better (heh), your `xrandr`, and many more. Perfect for many on-off scenarios because lot of commands offer that.

@tobes I had problems with launching apps, I tried code from `xscreensaver` to survive, but it does not work well (iirc). I also wanted users to be able to do things like `nautilus ~/Downloads`. I went with `self.py3.command_output(command, shell=True)` to make it possible.

**Comment by ultrabug** [comment]
> I think we should start new blocking modules that are not clear because they will create a huge technical debt/support nightmare (this is not a comment specific to this module)

I do not understand this sentence sorry

**Comment by ultrabug** [comment]
> I think we should start new blocking modules that are not clear because they will create a huge technical debt/support nightmare (this is not a comment specific to this module)

I do not understand this sentence sorry

**Comment by lasers** [comment]
@ultrabug Is that okay if I close this?

**Comment by ultrabug** [comment]
I guess so yes, closing. Thanks

**Pull request closed without merging**
