### PR TITLE
add new module: nvidia_smi

### PR DESCRIPTION
**Pull request by lasers**
We revives an accidentally closed pull request. https://github.com/ultrabug/py3status/pull/903

2017-10-28-061420_1343x148_scrot

* Support 140~ external placeholders. Some duplicates. eg, `gpu_name` and `name`, but unofficially, I can use 10~ placeholders. It can vary from GPU to GPU. See if we should make a script that'll output a list of properties and values, weeding out the others, eg `Not Supported`.

* I like `{memory.used}` here in the default format.

* Backward compatible not included for `nvidia_temp` as of this time. New module?

* Support color thresholds for placeholders in the `format_gpu`. _**New!**_
    ```
    thresholds = {
        'memory.used': [(0, 'good'), (1, 'degraded'), (2, 'bad')],
        'temperature.gpu': [(0, 'bad'), (1, 'degraded'), (2, 'good')],
    }
    ```
* I clean up things.

* I fix mistakes too. `format_gpu` makes more sense here than former `format_properties` as we're not formatting anything in the properties in the GPU, but the properties for every GPU we have.

* @tobes: I'm merely pointing out an issue with `color_threshold`. This lacks an optional `index`/`string` because lot of things are usually done in the loop and sometimes we will have same color thresholds for different things in the loop. An example.
    ```
    thresholds = {
        '1.temperature.gpu': [(0, 'good'), (80, 'degraded'), (90, 'bad')],  # same
        '2.temperature.gpu': [(0, 'good'), (80, 'degraded'), (90, 'bad')],  # same
        '3.temperature.gpu': [(0, 'good'), (80, 'degraded'), (90, 'bad')],  # same
        '4.temperature.gpu': [(0, 'good'), (80, 'degraded'), (90, 'bad')],  # same

        '1.memory.used': [(0, 'good'), (4096, 'degraded'), (8192, 'bad')],  # 8GB card
        '2.memory.used': [(0, 'good'), (2048, 'degraded'), (4096, 'bad')],  # 4GB card
        '3.memory.used': [(0, 'good'), (1024, 'degraded'), (2048, 'bad')],  # 2GB card
        '4.memory.used': [(0, 'good'), (512, 'degraded'), (1024, 'bad')],   # 1GB card
    }
    ```

### CODE REVIEW

**Comment by lasers** [comment]
1) We can haz different NVIDIA GPUs.
2) For every NVIDIA GPU, we can haz different usable/supported placeholders.
3) Should the users want to supply their format with more placeholders, they can use this custom helper script instead of probing various placeholders to find out what their cards supports.
4) This script puts together an explicit list of all valid NVIDIA placeholders then probe everything in one command... and filters out unsupported properties... leaving us with only an explicit list of usable / supported placeholders for our NVIDIA GPUs, eg...
```
$ python nvidia_smi.py --list
[
    {
        "= This GPU contains at most 24 usable placeholders.": "",
        "===================================================": "",
        "clocks_throttle_reasons.supported": "0x0000000000000000",
        "compute_mode": "Default",
        "count": "1",
        "driver_version": "340.102",
        "gpu_bus_id": "0000:05:00.0",
        "gpu_name": "Quadro NVS 295",
        "gpu_uuid": "GPU-abcdefgh-ijkl-mopq-rstu-vwxyz0123456",
        "index": "0",
        "memory.free": "148",
        "memory.total": "255",
        "memory.used": "107",
        "name": "Quadro NVS 295",
        "pci.bus": "0x05",
        "pci.bus_id": "0000:05:00.0",
        "pci.device": "0x00",
        "pci.device_id": "0x6FD10DE",
        "pci.domain": "0x0000",
        "pci.sub_device_id": "0x62E10DE",
        "persistence_mode": "Disabled",
        "pstate": "P10",
        "temperature.gpu": "66",
        "timestamp": "2018/02/14 02:39:51.983",
        "uuid": "GPU-abcdefgh-ijkl-mopq-rstu-vwxyz0123456",
        "vbios_version": "62.98.75.00.07"
    }
]
```

**Comment by lasers** [comment]
@ultrabug This is 100% ready. 1 year anniversary coming up soon. :man: :woman: :ring: 

I'm having a different issue with `nvidia_smi` where we can't use`:.2f` in placeholders containing periods... which does not exist in this because my new placeholders are made from the `nvidia_smi` output... including the same name w/ new suffix.

* `{memory.used}` --> 512  # OK
* `{memory.used_percent}` --> 12.3  # PROBLEM.

We can sort out the issue later... and then I merge the new placeholders. This easily replace `nvidia_temp` (eg, >24 placeholders for my GPU versus 1 placeholder) too.

`nvidia_temp` prints `GPU: 60°C` by default.
This prints `Quadro NVS 295 60°C 215 MiB`.

**Comment by ultrabug** [comment]
@lasers we can't remove modules, add one and modify the formatter in the same PR I'm sorry

**Comment by ultrabug** [comment]
please split them

**Comment by lasers** [comment]
This just show what I need to get this merged.

* I need the formatter to deal with `.2f`, .`0f`, etc for ~~three~~ one placeholder containing period... ie `{memory.used_percent:.2f}`. I removed `{memory.free_percent}`, `{memory.total_percent}`.

* I want to use config parser to rename `nvidia_temp` to `nvidia_smi` along with `nvidia_temp` deprecation...  so we don't increase number of modules. This also would mean users never can use the names of old modules for years.

* Backward compatible is done in `nvidia_smi` for `nvidia_temp`, but it will print out different due to different (default) formats. Will users like this formats? eg printing card `{name}` instead of `GPU: `.  I do this for consistency with other modules. That's why `hddtemp` does not print `HDD:` too.

* This also bring new behaviors, eg `nvidia_smi` will colorize temperature based on temperature instead of always good `nvidia_temp`. Did I use the ideal `thresholds` value? I think it's decent enough for starters, but users should be able to use `memory.free_percent` in `thresholds` too.

Additionally, I want to rename more in the future to kill a module or two. I'm waiting for eyes to review this before I put them up into different PRs. Will you accept the `formatter PR`?  Will you accept `renaming modules + backward deprecation` PR... to kill modules?

Eg
* ~~nvidia_temp~~  ......... nvidia_smi
* ~~scratchpad_async, scratchpad_counter~~ ......... scratchpad
* ~~window_title, window_title_async~~  ......... window_title

Address this, then I split them up or whatever I need to do.

**Comment by lasers** [comment]
What do you want me to do here?
1) Merge `nvidia_smi` as a new module?
    a) Nothing changed, but stupid to have one simple module + one real module.
2) Replace `nvidia_temp` (only 1 placeholder) with `nvidia_smi` (over 100 placeholders)?
    a) Break format because if I deprecate them all, it still come out stupid due to colors, new format, etc.

**Comment by lasers** [comment]
@ultrabug I'd like to move here. `nvidia_smi` will look like `hddtemp` out of the box without deprecation. With deprecation, it can look weird since it's not possible to retain everything... especially the colors.  Replace or add this as new module?

**Comment by lasers** [comment]
I merge this without the deprecation and not replacing `nvidia_temp`.

It's no-brainer that we should deprecate `nvidia_temp` in favor of `nvidia_smi` because `nvidia_smi` can copy `nvidia_temp` legacy format too... along with 100+ placeholders, a helper script to fetch a list of supported placeholders, `memory.used_percent`, thresholds, and not having hardcoded colors. <3

**Pull request merged**
