### PR TITLE
nvidia_smi: remove string 'None', use memory.used_percent

### PR DESCRIPTION
**Pull request by lasers**
An alternative for #1477. Should I combine ~6~ 7 commits into 3 commits for better readability?

@tobes With this merged, you can have your period.

I initially do this because if I run into an issue, I can come up with an edge-case solution for this module only or I can try and make formatter work better overall. For instance, `{None:.2f}` can still happen in other modules with `data_dict.get('placeholder')`.

### CODE REVIEW

**Comment by tobes** [comment]
@lasers 

You cannot do this.  If you want to make changes you need to do separate PRs for them, especially if you mess with the core code.  They may be related but having them together helps no-one.  Sorry maybe I've never tried to explain this before, but it is very important.

I see no explanation for your changes here in this PR.  I would have expected a __clear well thought out__ explanation including the consequences of the change.

FYI it is still my intention to get commit 499e6e0a reverted

Please think about and review (several times) your reply here because I am getting tired.  I'm also unlikely to check back till tomorrow, so no rushed responses please.

**Comment by lasers** [comment]
It's important to have them together, but yes, I should explain what's going on here as the commits are not clear here. I can drop the unwanted commits afterward. I aim to help everybody understand the situation I had with my modules...

First...

```
Revert "formatter: show values instead of faking nonexistent keys"
lm_sensors: use 'None' instead of None
```
In `lm_sensors`, users can get some `{input}` instead of `None` because of `'{None:.2f}`. I prefer we don't drop this as it does not make sense to me to drop this. If you insist on dropping this, then I won't object.

I rename `None` to `'None` in `lm_sensors` as a workaround too.

-----

Second...

```
Revert "formatter: hide block on 'None' string too"
nvidia_smi: check each value instead of output
lm_sensors: remove string 'None' placeholders
```
In `nvidia_smi`, I check line. I replace all `'[Not Supported]'` to `'None'` in one go instead of checking value each. This is avoidable. We can revert this commit. Perfect.

This is funny because this will kill the recent `lm_sensors` workaround above of hiding string `'None'` placeholders now so I remove the whole thing now... Just know that in `lm_sensors`, the default `format` will sometimes always look broken to everybody because users will change hardware, buy another hardware, or whatever.

We can revert this either way. Conflict here would suggest to not revert the first commit above.

-----

Third...

```
Revert "formatter: parse placeholders with periods"
nvidia_smi: hardcode {memory.used_percent} to .1f
```

This gets what you want. `{memory.used_percent}` gets `.1f` too. We can drop this as I think users wouldn't complain much about hardcoded `.1f` and you get to use your period for something.

**Comment by lasers** [comment]
Dropped.
```
* lm_sensors: use 'None' instead of None
* Revert "formatter: hide block on 'None' string too"
* lm_sensors: remove string 'None' placeholders
```
What's the stance on other commits?
```
Revert "formatter: show values instead of faking nonexistent keys"
```
```
Revert "formatter: parse placeholders with periods"
nvidia_smi: hardcode {memory.used_percent} to .1f
```

**Comment by tobes** [comment]
If you link to the specific commits then it makes life easier

> Revert "formatter: parse placeholders with periods"

I want to kill this, but this can be undone with minimal fuss - so I'm not too concerned

> Revert "formatter: show values instead of faking nonexistent keys"

that should probably die too but it is less serious because it is about bad formats anyhow

the reverts in #1504  were for un-repairable changes

**Pull request merged**
