### PR TITLE
thunderbird_todos: new module from scratch

### PR DESCRIPTION
**Pull request by lasers**
2017-12-20-thunderbirds_todos

@mrt-prodz Let's continue the discussion here. Indeed, `diskdata` and `github` is already utilizing this feature since the implementation: https://github.com/ultrabug/py3status/pull/1011. I suppose you can remove the checking there and test the rest of the examples?

### CODE REVIEW

**Comment by lasers** [comment]
Hold off for now. I want to look around and add more examples.

**Comment by lasers** [comment]
@ultrabug Okay. Merge this.
@tobes We should address `\?if=placeholder>0` where `placeholder` can be `None`. We return it `False` instead of throwing an error.

**Comment by tobes** [comment]
> @tobes We should address \?if=placeholder>0 where placeholder can be None. We ought to return False instead of throwing an error.

Is there an issue for this? but is None <= 0 ?

**Comment by lasers** [comment]
Mentioned in https://github.com/ultrabug/py3status/pull/1005 too for `input` module. I can make an issue for this... `None` is `None`... so I think we just give it `0`. Not much of a choice.

**Comment by ultrabug** [comment]
@mrt-prodz need you to sign this off plz before I merge

**Comment by lasers** [comment]
@mrt-prodz I added `sort` option... but I still think you need more features!

```
sort = ['last_modified', True] # sort by modified time: recent first
```
This particular option is pretty nifty. I also added `{incompleted_index}` and `-1` for the last items. Your new config might be this.
```
format = '\?if=incompleted_index=-1 {title}'
```
... because `\?if=index=1 {title}` could give you a title of a completed todo.

Or you can `sort` things backward and use `\?if=incompleted_index=1 {title}`. Anyhow, this is cool and if you find an issue, had questions, or wanted something else, let me know. 👍

**Comment by mrt-prodz** [comment]
```format_todo = '\?if=incompleted_index=-1 {title}'```

This successfully displays the latest todo I edited in Thunderbird, once again I think you did a really neat job with this since it allows user for more control over what they want to display. I didn't test all examples provided but so far everything is working properly.

**Comment by mrt-prodz** [comment]
@lasers I also played around with the index argument in format_todo to display the latest todo along with a couple incompleted others incompleted:

```
format_todo = '[\?if=incompleted_index=-1 {title}][\?if=incompleted_index=1 {title}][\?if=incompleted_index=2 {title}]'                                                                
format_separator = ' - '
```
Works just fine as well. :+1:

**Comment by lasers** [comment]
I do not know if you know this, but you can break them up too.
```
format_todo = '[\?if=incompleted_index=-1 {title}]'
format_todo += '[\?if=incompleted_index=1 {title}]'
format_todo += '[\?if=incompleted_index=2 {title}]'
format_separator = ' - '
```
I'm happy to know I passed the @mrt-prodz test. 👌

**Comment by lasers** [comment]
I want to address a concern I have about that `-1` thing... This might be a superfluous feature because we can achieve the same goal with...
```
thunderbird_todos {
    format = '\?if=incompleted_index=1 {title}'
    sort = ['time_created', True]
}
```
instead... and is probably more efficient too. This cuts down 10~ lines too.

The only reason we should keep this is if we knew the users will need both `index=1` and `index=-1`... which is not likely so it'd be good to skip `-1` right away and reverse-sort the list.

For every `index` we add in this (I'm not adding `completed_index` on purpose as it's probably not wanted anyhow...), we would have to add `-1` for that... and it goes on.

I'm bringing this up right now because there are other modules that could take advantage of this `sort` config... such as `taskwarrior`, `transmission` (sorted by percents)... `coin_market` (sorted by names, price, currency, etc). Really, many modules can use this feature... so I'd like to avoid `-1` early on. What do you think?

**Comment by ultrabug** [comment]
@lasers are we done here ?

**Comment by lasers** [comment]
@ultrabug Yes. Merge, pls.

**Comment by lasers** [comment]
We merged this module 25 days ago, no release tag. If we release a version, then it can be hard to change later. So far, we know one possible current user. I agree all the `from scratch` PRs should be tested. Everything should be tested by not-authors.

**Comment by tobes** [comment]
> Everything should be tested by not-authors.

Everything should be tested by the person writing the code,  If you are not thoroughly testing your code then this is a big problem

**Comment by lasers** [comment]
That's a given. I meant `s/not-authors/not-authors too` as we will always miss things. 

_Quis custodiet ipsos custodes?_ Who will test the testers?

Do you want a default format in this or let users configure it themselves? By the way, I should make it clear that this throws an exception on startup due to empty `format_todo` so users will need to add `\?if=!todo_completed {title}` or something.

From my experience in writing `window_manipulation`,  `taskwarrior: new module from scratch`, and several other modules... I find it easier/cleaner to add and/or test the configs without defaults because sometimes we may need to undo defaults... Useful when module have lot of configs... and/or I come up with lot of examples.

I presume I wait for you to test this?

**Comment by tobes** [comment]
>  should make it clear that this throws an exception on startup due to empty `format_todo`

All modules should really work with defaults unless very good reason like needing an api key

> so users will need to add `\?if=!todo_completed {title}` or something.

And imho all default formats should be very simple so absolutely no `if`, `not_zero` etc I know some have but I think this is a mistake.  It show either that the formatter is f$%^&d (which it partly is) or other things are bad.  I also think that there should be no `:.2f` etc either but this is for another battle.

> I find it easier/cleaner to add and/or test the configs without defaults because sometimes we may need to undo defaults

I think this is unhelpful.  It is easy to either change defaults or just have them in the config.  Hopefully we will make this easier soon anyhow.

> I presume I wait for you to test this?

I'm not going to get to test as I don't use thunderbird tasks but really you need to fix the conflict, maybe you can get @mrt-prodz to do some more

**Comment by lasers** [comment]
>And imho all default formats should be very simple so absolutely no if, not_zero etc I know some have but I think this is a mistake.

I have a conflict here. Do I use `{title}` or `\?if=!todo_completed {title}` here? You said _absolutely no `if`_ even although the latter is much more reasonable to have as default over the former? 

>but really you need to fix the conflict

I didn't see that. I must have a poor eyesight now. Will push out a change.

Pinging @maximbaz. I think you may be using `thunderbird`. Care to test this if you are?

**Comment by tobes** [comment]
> I have a conflict here. 

If you have a good enough argument but it needs to be rock solid :)

**Comment by lasers** [comment]
Lazy argument.. Show all incomplete tasks only instead of all tasks. Avoid history buildup.

**Comment by lasers** [comment]
>@tobes We should address \?if=placeholder>0 where placeholder can be None. We ought to return False instead of throwing an error. I include a minor fix in thunderbird_todo to overcome this issue, but would be good for all modules. :+1:

Can we address this now before this PR?

**Comment by tobes** [comment]
why not a filter?  It'd be easier to understand imho

**Comment by tobes** [comment]
> I include a minor fix in thunderbird_todo to overcome this issue,

Generally this is really bad to do.  All that happens is you make the module code messy and the problem continues.

If the feature is broken we should not be encouraging its use till we have it fixed.

**Comment by lasers** [comment]
PR to address this: https://github.com/ultrabug/py3status/pull/1228 -- Tested w/ `thunderbird_todos`. Is okay.

**Comment by lasers** [comment]
Req: Do not merge. Wait for https://github.com/ultrabug/py3status/pull/1228.
Opt: With https://github.com/ultrabug/py3status/pull/1240 in, I can add an example to colorize tasks based on `priority`.

**Comment by lasers** [comment]
Greetings @ultrabug and @tobes.

Following @tobes's request for changes... I went through this again. This is **BETTER** now because I simplified more things, added trivial comments and squeezed out few more placeholders.

I would like to have #1240 addressed so we can merge this next. Otherwise, we can merge this now too because I included the `None -> 0` fix back in... in order to work on this.

I didn't add deprecations too because we're still on same `py3status` version. This is a module written from scratch so I'm trying to keep this clean. Thank you for reading.

P.S.You should consider giving some **POWERS**... then I could try and close issues swiftly. Just give me some rules like what to do with my new modules? Merge them or not? What to do with new features (eg, buttons)? Merge them or not? Etc.... or at least... I could use this to label, tag, assign, make review difficulty stars, etc. All to close more issues. Thank you. *[fingers crossing]*

**Comment by ultrabug** [comment]
Since all interested parties here are okay, I'm merging now

**Pull request merged**
