### PR TITLE
move thread checks out of core main loop

### PR DESCRIPTION
**Pull request by tobes**
Currently we check event and i3status threads are alive in the main loop.  This moves these checks into the actual modules.  Also remove some other cruft in the loop that is no longer needed.

### CODE REVIEW

**Comment by ultrabug** [comment]
schedule every 5s the i3status thread aliveness plz

**Comment by ultrabug** [comment]
friendly bump @tobes

**Comment by tobes** [comment]
@ultrabug should be good to go now

**Comment by ultrabug** [comment]
Awesome, if I get it right we always restart i3status now, but every 5s

**Comment by tobes** [comment]
> if I get it right we always restart i3status now, but every 5s

ahh I just thought this was the merge conflict I made #1120 for this :)

**Pull request merged**
