### PR TITLE
modules: make docstrings consistent

### PR DESCRIPTION
**Pull request by lasers**
Make modules slightly more consistent. Little fix that I want to merge before the `3.6` release.

Ekk! 46+ lines... Quality over quantity? 😕

### CODE REVIEW

**Comment by tobes** [comment]
I sometimes wonder about the point of empty docstrings

@ultrabug your thoughts?  I think we should be consistent whatever we decide

**Comment by lasers** [comment]
More inconsistencies to point out...

* Not all main methods follows the file names... `rates` in `exchange_rate.py`, `return_status` in `vpn_status`, `counter` in `rate_counter`, etc...  We fix the names and/or replace them with generic name that mean nothing (like `available configuration parameters` for config). We probably should just update the names and get this over with?

* Not all main methods contains `"""\n"""` docstrings too. Idc about this, but brings it up.
* That's it for now. Separate (minior) issue is that there are two duplicate placeholders in moc and I wanted to update `moc+cmus` with some better phrasing and formatting (like `window_manipulation)`.

**Comment by tobes** [comment]
> Not all main methods follows the file names.

to be honest this is not currently important as we find the method.  In some ways just all using `update()` or some other name might make more sense. but we still need to support users custom modules.

modules can have more than one method, only sysdata I think uses this, may be a different module.

> Not all main methods contains """\n""" docstrings too. 

do you just mean docstrings or is the \n important?  If you mean empty docstrings then I think we should just remove them or add something meaningful so not `updates module output` I suppose it depends what we do on the previous issue.


> Separate (minior) issue is that there are two duplicate placeholders in moc and I wanted to update moc+cmus with some better phrasing and formatting (like window_manipulation). Can I have a go at this? 👍

sure maybe just do one first to see what you mean exactly

**Comment by lasers** [comment]
>modules can have more than one method, only sysdata I think uses this, may be a different module.

I think just `netdata` and we got rid of that already... 👍 because it shouldn't be there in first place and it also clashes with `frame_separator` color issue.

>do you just mean docstrings or is the \n important? If you mean empty docstrings

Empty docstrings. For now, we leave this kind of decision on quality assurance to @ultrabug.

**Comment by tobes** [comment]
@lasers I cherry-picked 55ab1d8e, really it should not have been added to this PR but as a new one.

The `format_separator` changes I don't think are correct.  imho they should be more like `format_separator: separator used to join multiple format_coin (default ' ')` for `coin_market`

I think we should close this PR as I think it is unlikely to move any further, but I'll leave that choice up to you.  Also combining different things in a PR is not good because if one little thing prevents merging then the whole lot is stuck in limbo.

**Comment by lasers** [comment]
We should consider `min` and `max` lengths too. Using `button_example: button...` instead of `button_example: mouse button..` can really shorten the length.

```
Configuration parameters:
    cache_timeout: refresh interval for this module. A message from the site:
        Please limit requests to no more than 10 per minute. (default 600)
    format: display format for this module (default '{format_coin}')
    format_coin: display format for coins
        (default '{name} ${price_usd:.2f} [\?color=24h {percent_change_24h}%]')
    format_separator: separator used to join multiple format_coin (default ' ')
    format_separator: show separator if more than one (default ' ')
    format_separator: show separator only if more than one (default ' ')
    markets: number of top-ranked markets or list of user-inputted markets
        (default ['btc'])
    request_timeout: time to wait for a response, in seconds (default 5)
    thresholds: for percentage changes (default [(-100, 'bad'), (0, 'good')])

Format placeholder:
    {format_coin} format for cryptocurrency coins
```

Maybe using `coin_market` was a bad example because explanations and/or default formats in that module is loaded.... It's more noticeable in other modules. I have my column at 79 so some descriptions are creeping up to that column.

>really it should not have been added to this PR but as a new one.

I don't want to make too many PRs that might end up rejected and/or nothing. I can remove commits easily if we don't need them. Where's @ultrabug ? I think he would like the first commit as it's making everything a bit more consistency. I'd like to remove `only` in separators to explain things more straightforward and less specific.

I remove the first commit and you merge the second commit?

**Comment by tobes** [comment]
> I don't want to make too many PRs that might end up rejected and/or nothing.

The bigger they are the more chance they go nowhere.

> I can remove commits easily if we don't need them.

This makes more work for all of us, but yes

> Where's @ultrabug ? 

Not about for a while, probably not till next month

Really, I think the way to go with this is to look at a single module and decide how we can do things better.  Once we have some agreement on that, then we can make the changes everywhere it applies.  Change is hard though.

**Comment by lasers** [comment]
@ultrabug Opinion, pls!

**Comment by tobes** [comment]
Consistency is good but I'm not a fan of the empty docstring.

**Comment by ultrabug** [comment]
This is one of my oldest QA, I think I'd like to stick to it

**Pull request merged**
