### PR TITLE
Require setuptools, py3status/core.py and tests/test_user_modules.py import pkg_resources

### PR DESCRIPTION
**Pull request by hrnciar**

### CODE REVIEW

**Comment by ultrabug** [comment]
Hello @hrnciar could you please elaborate on what you're proposing here?

**Comment by hrnciar** [comment]
Setuptools is a runtime dependency for pkg_resources. Without it, it can lead to `ModuleNotFoundError: No module named 'pkg_resources'` in case setuptools is not installed. 
See reproducer below:
~~~~
[thrnciar@localhost tmp]$ python3.9 -m venv __venv__
[thrnciar@localhost tmp]$ . __venv__/bin/activate
(__venv__) [thrnciar@localhost tmp]$ pip uninstall setuptools
Found existing installation: setuptools 53.0.0
Uninstalling setuptools-53.0.0:
  Would remove:
    /tmp/__venv__/lib/python3.9/site-packages/_distutils_hack/*
    /tmp/__venv__/lib/python3.9/site-packages/distutils-precedence.pth
    /tmp/__venv__/lib/python3.9/site-packages/pkg_resources/*
    /tmp/__venv__/lib/python3.9/site-packages/setuptools-53.0.0.dist-info/*
    /tmp/__venv__/lib/python3.9/site-packages/setuptools/*
Proceed (y/n)? y
  Successfully uninstalled setuptools-53.0.0
(__venv__) [thrnciar@localhost tmp]$ pip install --use-pep517 py3status
Collecting py3status
  Downloading py3status-3.36.tar.gz (441 kB)
     |████████████████████████████████| 441 kB 2.7 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: py3status
  Building wheel for py3status (PEP 517) ... done
  Created wheel for py3status: filename=py3status-3.36-py3-none-any.whl size=349002 sha256=264377cba0e7c84bf5612e4b9378f0f490aecfe6b32ee09553bdda54ffa3f2b8
  Stored in directory: /home/thrnciar/.cache/pip/wheels/8a/7d/cb/aef20134083c7242c42fbf697fcdf61be70cea1a2fa59b059b
Successfully built py3status
Installing collected packages: py3status
Successfully installed py3status-3.36
WARNING: You are using pip version 21.0.1; however, version 21.1 is available.
You should consider upgrading via the '/tmp/__venv__/bin/python3.9 -m pip install --upgrade pip' command.
(__venv__) [thrnciar@localhost tmp]$ pip list
Package   Version
--------- -------
pip       21.0.1
py3status 3.36
WARNING: You are using pip version 21.0.1; however, version 21.1 is available.
You should consider upgrading via the '/tmp/__venv__/bin/python3.9 -m pip install --upgrade pip' command.
(__venv__) [thrnciar@localhost tmp]$ py3status 
Traceback (most recent call last):
  File "/tmp/__venv__/bin/py3status", line 8, in <module>
    sys.exit(main())
  File "/tmp/__venv__/lib64/python3.9/site-packages/py3status/__init__.py", line 27, in main
    from py3status.core import Py3statusWrapper
  File "/tmp/__venv__/lib64/python3.9/site-packages/py3status/core.py", line 1, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
~~~~

**Comment by ultrabug** [comment]
@hrnciar okay but you explicitly uninstall setuptools so I'm not sure which user problem you're actually trying to solve I'm afraid?

I'm asking because py3status has been around for a while so if this was a major problem I guess we would have noticed by then.. so I'm really trying to understand clearly what we're missing here.

Thanks for your time and patience in explaining it more

**Comment by lasers** [comment]
>... because py3status has been around for a while so if this was a major problem I guess we would have noticed by then.

Added two years ago for our 10<sup>-9</sup> % users. https://github.com/ultrabug/py3status/pull/1823

**Comment by hrnciar** [comment]
It's definitely not a major problem. I was trying to demonstrate that it's possible that a package will fail if a user does not have installed setuptools. 

In Fedora, we package RPM package for py3status. I am not the maintainer of that package, but the maintainer of Python in Fedora.

We used to automatically generate a runtime dependency on setuptools for all RPM packages with Python projects with console_scripts entrypoints. Reason for this was that it was necessary for the way how was entrypoint script generated. Nowadays the entrypoint script looks differently. Particularly, they do not require setuptools to be installed on runtime in order to execute (at least on Python 3.8+ -- because it has importlib.metadata).

Hence we [are about to stop generating the automatic runtime dependency on setuptools for packages with console_scripts entrypoints.](https://fedoraproject.org/wiki/Changes/Reduce_dependencies_on_python3-setuptools) We went through all the affected packages in Fedora and identified some packages that will be negatively impacted in Fedora because when we stop adding the requirement automatically, they will have missing dependencies, because they use setuptools (pkg_resources) on runtime, but don't specify a dependency.

As long as you import from pkg_resources in the actual code, the project requires setuptools on runtime and the requirement needs to be specified, otherwise it might be missing.

**Comment by ultrabug** [comment]
Thanks a lot for explaining the rationale behind this @hrnciar , now it makes a lot more sense to me!

Now as I'm currently working on `mkdocs` could you confirm that https://github.com/mkdocs/mkdocs is also affected by this? because it looks to me like it is also packaged for Fedora.

**Comment by hrnciar** [comment]
> Now as I'm currently working on `mkdocs` could you confirm that https://github.com/mkdocs/mkdocs is also affected by this? because it looks to me like it is also packaged for Fedora.

Yes, it was affected as well, but seems like it was already taken care of. 
See this PR: https://github.com/mkdocs/mkdocs/pull/2347

**Comment by ultrabug** [comment]
> Yes, it was affected as well, but seems like it was already taken care of.

Indeed, I was stupidly looking at my own branch we predated the if in mkdocs.

Interestingly enough mkdocs chose another path... I'm investigating to find the best response for this in py3status, please bear with me.

**Comment by ultrabug** [comment]
Will move forward on this for the users' sake. I might consider moving to importlib.metadata later on

**Pull request merged**
