### PR TITLE
[whatismyip] Define `icon_*` params instead of `format_*`

### PR DESCRIPTION
**Pull request by maximbaz**
This is what @lasers asked in #819.

### CODE REVIEW

**Comment by maximbaz** [comment]
> The tests may give incorrect errors for some configuration parameters that the tests do not understand. Such parameters can be excluded from the test by adding them to the IGNORE_ITEM list in tests/test_module_doc.py

Travis is unhappy. Any ideas what this means?

**Comment by tobes** [comment]
==============================

whatismyip

==============================

Attributes not in alphabetical order, should be

['cache_timeout', 'format', 'hide_when_offline', 'icon_off', 'icon_on', 'mode', 'negative_cache_timeout', 'timeout', 'url_geo']

**Comment by maximbaz** [comment]
But they are already in this order... am I blind? 😕

**Comment by lasers** [comment]
Ha. Thanks. 👍 I don't know if we want this anymore as we could put everything in one `format` instead for upcoming 3.6... 

>I have no strong feelings against hide options, to the common user they are just straightforward and simple to use rather than understanding a more rich but complex format syntax.  --Ultrabug

Do we go for straightforward and simple options?
Do we go for rich but complex format syntax options?

**Comment by maximbaz** [comment]
Up to you guys, merge or close 🙂 

I really want to get #883 in the 3.5 release, as for this one I'm more or less indifferent, as it is invisible for me as a user 🙂

**Comment by tobes** [comment]
really `{icon}` should be added as a placeholder.

**Comment by maximbaz** [comment]
you mean _in addition_ to the current changes?

**Comment by tobes** [comment]
yeah

**Comment by maximbaz** [comment]
Added in the last commit, the only catch is that it only has effect in the 'ip' mode, and only when you are online. So it is really impossible to get `icon_off` in the format.

**Comment by tobes** [comment]
hmm, this module is a bit broken in it's logic from what I can see.  If we are offline then we ignore the format/mode anyhow that can be fixed another day.


merged, thanks

**Pull request merged**
