### PR TITLE
Sysdata: add support for colors/thresholds

### PR DESCRIPTION
**Pull request by guiniol**
This PR adds support for the new colors/thresholds utilities.

(I removed the swap and load support from this PR and open new PRs once this one is in)

### CODE REVIEW

**Comment by ultrabug** [comment]
Two things

Add yourself in the @author

I simply tested the module by loading it without config from master and then yours

- master one showed red
- yours without color

is that expected?

**Comment by guiniol** [comment]
> Add yourself in the @author

Should I do that for every module I make modifications to?


> is that expected?

No, but I didn't test it, so... I'll figure out what is going on.

**Comment by guiniol** [comment]
> I'll figure out what is going on.

That was easy. I wasn't even trying. Fixed ^^

**Comment by tobes** [comment]
I think we need to remove precision and padding parameters from this but I can make a PR for that

**Comment by guiniol** [comment]
@tobes you're right. I completely forgot. I'll do it like in #529 (with less complaining) unless you already started.

**Comment by guiniol** [comment]
@tobes I see you've added magic things for deprecating config parameters, so I tried using that in #553, but I can't get it to work. Once I know how to deprecate arguments using that, I'll make the PR for removing precision and padding.

**Pull request merged**
