### PR TITLE
Different Formats for the states of the mpd

### PR DESCRIPTION
**Pull request by L0ric0**
Adds the possibility to module to have different formats for the states
of the mpd. If a format for a state is not speccified then the format
option is used.
Adresses #1364

### CODE REVIEW

**Comment by ultrabug** [comment]
Hi @L0ric0 thanks for this proposal.

Did you try to do this using the formatter instead? looks to me you could achieve the same stuff using conditionals in the formatter

**Comment by L0ric0** [comment]
How do I use conditionals in the formater?
As far as I know one can only test if a placholder exists and define a fallback value. I haven't fond a possibility to test for the content of one.

**Comment by L0ric0** [comment]
Ok I have found a way to do this with the formater.

**Comment by lasers** [comment]
Can we see the `format`? Quick glance at `mpd_status` tells me that you might have to fix all three `state_*` configs to get rid of the brackets... then I dunno if that works now. Really, this module ought to be updated + simplified + documented with formatter examples.

**Comment by L0ric0** [comment]
Heres the format:
`MPD: {state} [\?if=!state=[stop] [[[{artist}] - {title}]|[{file}]]]`

The brackets around the stop are parsed literally and won't work if escaped. I think that is inconsistent with the grammar of the formats as literal brackets should be escaped. But I don't know if it is worth fixing.

I can look into updating the module. Can you give me pointers what to avoid?

**Comment by lasers** [comment]
Looking at the code, it looks like the problem is that the `state` is being replaced with user-defined `state_*` configs.. so try adding `state_stop = 'stop'` to your mpd config to "escape" the brackets. :-\

**Comment by L0ric0** [comment]
There is no problem with the format as shown above I just find it wired that you have to escape the brackets if you want to have them appear in the bar but not if you are using them in a string. But as I sayed I don't know if it is worth changing.

**Comment by lasers** [comment]
You found yourself in mostly unlikely scenario as you are the first one to test a string with brackets. Most placeholders will "never" have brackets so it's not worth changing.

The only reason you found this because `state_stop` uses `[stop]` so you're trying to working with that placeholder. If we're being reasonable, you would always be working with `stop` and not `[stop]`.

Somebody made `state_*` configs to to override `state` with same thing, but with brackets.

Brackets, I guess, are treated as string since there was no space so the whole thing is considered a string to be swallowed... As soon as there is a space, it becomes something else. I think trying to make most unlikely scenarios works... will not be useful in long run. Another unlikely scenario is to figure out how to test strings with spaces.

**Pull request closed without merging**
