### PR TITLE
Make frame button use average color of modules

### PR DESCRIPTION
**Pull request by MikaYuoadas**
This is a proposal of some code I use in my setup so the frame button display the average color of hidden modules.
If you think it's worth merging, I'll spend the extra bit of time cleaning up the code (e.g. should probably be an opt-in feature with a config flag to toggle it on).

### CODE REVIEW

**Comment by lasers** [comment]
This throws `invalid format` for me when toggling `button`.
```python
order += "frame"
frame {
    format = '{output} {button} '
    dpms {}
    dpms {}
    dpms {}
    dpms {}
}
```

**Comment by MikaYuoadas** [comment]
I've fixed the bug, it should no longer throw an "invalid format" error now.

**Comment by lasers** [comment]
Heads up. There is nothing wrong with my `format` so the bug is somewhere in py3status/formatter.

**Comment by MikaYuoadas** [comment]
Do you still get the bug with the updated code (I rebased the PR)?

I can no longer reproduce it with your example with the new code.

**Comment by lasers** [comment]
The "invalid format" bug stopped. The colorized "Hello, world!" bug is still there.

**Comment by lasers** [comment]
@MikaYuoadas There is a conflict. Can you fix it? Thx. :-)

**Comment by lasers** [comment]
@ultrabug "NAK :-1:" because too much colors in modules just makes it :hankey: dull brown fast.

**Comment by ultrabug** [comment]
Yes I'm not sure it's something too many of our users are expecting

Thanks @MikaYuoadas but I'm gonna close this

**Pull request closed without merging**
