### PR TITLE
getjson: use post_config_hook

### PR DESCRIPTION
**Pull request by lasers**
We make nice and unnecessary `post_config_hook` for `getjson`.

### CODE REVIEW

**Comment by tobes** [comment]
You have lots of open commits at the moment.  It would be good to limit the number.  I'm also thinking we should do this better.

The other PRs have improved the modules so they are good.

I think we want something like.
```
self.py3.missing_config(['url'])
```

that would put a nice error on the bar and do nice logging etc.  The actual way we do it might be different.
```
class Meta:
    compulsory_params = ['url']
```

**Comment by lasers** [comment]
>do nice logging etc.

Oh my gawd. Yes, please. The nice exceptions are making ugly dents in the logs. I tried both `raise Exception` and `self.py3.error()`. Both came out making same dents.

I'm also wondering maybe we should make exceptions be opened by default... Not hiding or making it small. Exceptions are exceptions. Always clicking to open them up... got old.

**Comment by lasers** [comment]
Replaced `not configured` with `missing url`.  We make it nice and soft... like puppies.

**Comment by tobes** [comment]
I still think this is the wrong solution here, and that we should do the right one first off otherwise we are just creating busy work

**Comment by lasers** [comment]
Okay, I do the right ones now... Check and merge `mpris: use post_config_hook` as that one loads okay here. I will look into adding an example using github url for this one.

**Comment by ultrabug** [comment]
I'm inclined to merge, @tobes ?

**Comment by tobes** [comment]
@ultrabug yeah merge it

**Pull request merged**
