### PR TITLE
cleanup: remove transformed from module responses

### LINKED ISSUE #671: transformed removal
Some modules return `transformed` in their response, this is legacy and should be removed

eg window_title

### PR DESCRIPTION
**Pull request by tobes**
closes #671 

removes code :)

I also made window_title easier to read

### CODE REVIEW

**Comment by lasers** [comment]
Morning, mate.
```
2017-01-17 10:29:07 INFO method window_title returned {'full_text': '...perator', 'transformed': False, 'instance': '', 'name': 'window_title'} 
2017-01-17 10:29:07 WARNING Instance `scratchpad_counter`, user method `scratchpad_counter` failed (TypeError) scratchpad_counter.py line 20.
2017-01-17 10:29:07 INFO Traceback
TypeError: 'NoneType' object is not subscriptable
  File "/home/chris/src/py3status/py3status/module.py", line 584, in run
    response = method()
  File "/home/chris/src/py3status/py3status/modules/scratchpad_counter.py", line 42, in scratchpad_counter
    count = len(find_scratch(i3.get_tree()).get("floating_nodes", []))
  File "/home/chris/src/py3status/py3status/modules/scratchpad_counter.py", line 20, in find_scratch
    if tree["name"] == "__i3_scratch":

2017-01-17 10:29:07 ERROR py3status: Instance `scratchpad_counter`, user method `scratchpad_counter` failed (TypeError) scratchpad_counter.py line 20. Please try to fix this and reload i3wm (Mod+Shift+R)
```

**Comment by tobes** [comment]
@lasers I've added a commit to hopefully fix the issue can you see if you can test it. Can you easily replicate the issue?

**Comment by tobes** [comment]
If there is a problem can you tell me how to reproduce it as I'm trying to fix it blind

**Comment by lasers** [comment]
I can't replicate the issue. I was just leaving your modules running in my i3playtime-bar and surfing the internet. I thought it was on this branch. It's not. I'll try and play with scratchpad windows to see if I can make it happen again.

**Comment by lasers** [comment]
Fix up debug output to differentiate information. `module first // method second` style and to print branch/commit every ten seconds to help confirming the correct branch and/or commit.

I think I can reproduce this issue. I already got two different issues, but wasn't sure which branch/commit I was on... and the log gets filled up fast with 0.5s. This crash is related to i3-msg restart.

```
2017-01-17 11:58:16 INFO lock cleared, exiting
2017-01-17 11:58:16 WARNING Instance `scratchpad_counter`, user method `scratchpad_counter` failed (Exception) py3.py line 699.
2017-01-17 11:58:16 INFO Traceback
Exception: Command 'i3-msg' returned non-zero exit status -15
  File "/home/chris/src/py3status/py3status/module.py", line 584, in run
    response = method()
  File "/home/chris/src/py3status/py3status/modules/scratchpad_counter.py", line 54, in scratchpad_counter
    tree = loads(self.py3.command_output('i3-msg -t get_tree'))
  File "/home/chris/src/py3status/py3status/py3.py", line 699, in command_output
    raise Exception(msg.format(cmd=command[0], error=retcode))

2017-01-17 11:58:16 ERROR py3status: Instance `scratchpad_counter`, user method `scratchpad_counter` failed (Exception) py3.py line 699. Please try to fix this and reload i3wm (Mod+Shift+R)
2017-01-17 11:58:17 INFO ========
```

**Comment by tobes** [comment]
If you run with this patch then we should get the info we need
```
diff --git a/py3status/modules/scratchpad_counter.py b/py3status/modules/scratchpad_counter.py
index 230e018..d1ccf38 100644
--- a/py3status/modules/scratchpad_counter.py
+++ b/py3status/modules/scratchpad_counter.py
@@ -49,7 +49,14 @@ class Py3status:
 
     def scratchpad_counter(self):
         tree = loads(self.py3.command_output('i3-msg -t get_tree'))
-        count = len(find_scratch(tree).get("floating_nodes", []))
+        try:
+            count = len(find_scratch(tree).get("floating_nodes", []))
+        except:
+            self.py3.log('SCRATCHPAD ERROR')
+            self.py3.log(type(tree))
+            self.py3.log(tree)
+            self.py3.notify_user('SCRATCHPAD ERROR')
+            count = '?'
 
         response = {
             'cached_until': self.py3.time_in(self.cache_timeout),
```

I suspect i3-msg is just returning nothing

That last error is related to #672

**Comment by lasers** [comment]
I got an exception. No `SCRATCHPAD ERROR`.

**Comment by lasers** [comment]
This branch too.
```
2017-01-17 12:51:07 INFO method sysData returned {'composite': [{'full_text': 'CPU: 12.42%', 'color': '#00FF00', 'instance': ' 0', 'name': 'sysdata', 'separator': False, 'separator_block_width': 0}, {'full_text': ', ', 'instance': ' 1', 'name': 'sysdata', 'separator': False, 'separator_block_width': 0}, {'full_text': 'Mem: 2.25/7.73 GB (29.06%)', 'color': '#00FF00', 'instance': ' 2', 'name': 'sysdata'}], 'instance': '', 'name': 'sysdata'} 
2017-01-17 12:51:07 WARNING Instance `sysdata`, user method `sysData` failed (ZeroDivisionError) sysdata.py line 261.
2017-01-17 12:51:08 INFO Traceback
ZeroDivisionError: float division by zero
  File "/home/chris/src/py3status/py3status/module.py", line 584, in run
    response = method()
  File "/home/chris/src/py3status/py3status/modules/sysdata.py", line 261, in sysData
    float(cpu_idle-self.cpu_idle) / float(cpu_total-self.cpu_total)

2017-01-17 12:51:08 ERROR py3status: Instance `sysdata`, user method `sysData` failed (ZeroDivisionError) sysdata.py line 261. Please try to fix this and reload i3wm (Mod+Shift+R)
```

**Comment by lasers** [comment]
This branch too.
EDIT: We are here for this one.
```
2017-01-17 12:58:02 INFO method scratchpad_counter returned {'full_text': '0 ⌫', 'instance': '', 'name': 'scratchpad_counter'} 
2017-01-17 12:58:02 INFO lock cleared, exiting
2017-01-17 12:58:02 WARNING Instance `scratchpad_counter`, user method `scratchpad_counter` failed (Exception) py3.py line 699.
2017-01-17 12:58:02 INFO Traceback
Exception: Command 'i3-msg' returned non-zero exit status -15
  File "/home/chris/src/py3status/py3status/module.py", line 584, in run
    response = method()
  File "/home/chris/src/py3status/py3status/modules/scratchpad_counter.py", line 51, in scratchpad_counter
    tree = loads(self.py3.command_output('i3-msg -t get_tree'))
  File "/home/chris/src/py3status/py3status/py3.py", line 699, in command_output
    raise Exception(msg.format(cmd=command[0], error=retcode))

2017-01-17 12:58:02 ERROR py3status: Instance `scratchpad_counter`, user method `scratchpad_counter` failed (Exception) py3.py line 699. Please try to fix this and reload i3wm (Mod+Shift+R)
```

**Comment by lasers** [comment]
I ran `while sleep 2; do i3-msg restart ; done` for several minutes. No error. The error is related to my restart shortcut which is `j4-make-config`. What j4-make-config does is merge two or more config files (config and theme for me) then `i3-msg restart`. I double check my branch to see if I didn't accidentally undo the diff. It's still there, but nothing came out differently.

**Comment by ultrabug** [comment]
You lost me here guys, seeing the diff on this MR looks fine to me but those comments make me believe that I'm wrong ?

**Comment by lasers** [comment]
Go ahead and merge. Exceptions occurred, but likely not related to this PR. It could be due to my setup. I'll investigate this later to see if it occurs just the same with pure `i3-msg restart` shortcut.

**Comment by tobes** [comment]
@ultrabug 

>You lost me here guys, seeing the diff on this MR looks fine to me but those comments make me believe that I'm wrong ?

The issues are all unrelated to this PR.

**Comment by lasers** [comment]
This need a tag. `f--king ready for merge`.

**Comment by lasers** [comment]
@ultrabug Don't forget this! Perplexed exotic bug! *ROAR!!!*

**Comment by ultrabug** [comment]
Thanks a lot, good cleanup !

**Pull request merged**
