### PR TITLE
backlight: expose floating-point numbers

### PR DESCRIPTION
**Pull request by lasers**
Instead of just `74%`, we can show `73.943127962085306%` or `73.9%` too if the users want them.

### CODE REVIEW

**Comment by tobes** [comment]
If I have a custom format of `'{level}'` then I will now see all the digits.  So this changes the behaviour.  One option is to fix this in `class Meta` but I'm thinking maybe we need a more elegant solution to this as part of the formatter.

The other issue is you have changed the default format and given no reason.  Yes it may be just removing a colon but this is the sort of change which should be discussed in detail, consistency is good but we need to work out our unified approach rather than just changing here and there else we risk one person adding such things and another removing them.

I think the whole format thing is something that we need to revisit as a project as I think we have been getting too complicated and we need to simplify things especially for any defaults.

**Comment by lasers** [comment]
>... then I will now see all the digits.

Yah. Just trying to untie this hard integer knot.

>One option is to fix this in class Meta.

I don't like that option. I think `sysdata` have this and I'm unaware that we can specify `float` for them. It might suck a bit that they're not exposed in all the placeholders, then again, it could suck just the same if we have to configure them all... I think the users shouldn't have to parse no more than the docs. I see `{example:.0f}`, then I understand it's probably a `float` value.

>I'm thinking maybe we need a more elegant solution to this as part of the formatter.

I have a solution in mind and can apply it. I'm curious about your elegant solution. 🤔 

>changed the default format and given no reason.

Consistency and clean.

(Opinion) Applying a colon to an icon and/or abbrev might be not necessary. We could check the other formats for colons and see if they're worth keeping too. We quickly glance at bar to glean information.  If there are colons, then the default format might be a bit too much. Numbers are probably more important to the users than the colons too.

>I think the whole format thing is something that we need to revisit as a project as I think we have been getting too complicated and we need to simplify things especially for any defaults.

What if the defaults are a bit too long but sensible? Like having `\?not_zero` might make sense for all  update modules... as the users wouldn't have to configure anything... Same thing with `scratchpad_async` assuming large percent of i3 users might want to have them hidden... because i3 does not show empty workspaces so maybe we shouldn't show empty `scratchpad_async`  too. Just trying to make things a bit easier. Let me know anytime if I should get on IRC.

>need to work out our unified approach

Okay I'm down for that... especially with the whole (merging?) formats.

**Comment by tobes** [comment]
> What if the defaults are a bit too long but sensible? Like having `\?not_zero` might make sense

I don't think `\?not_zero`  or similar should be in any modules default config.  To me that is a sign of failure on our part.  Likewise I want to kill all `{example:.0f}` style things in defaults.

I think we can do this in a much more sensible way so for example `{example}` would be sensible by default but users could do `{example:.2f}` if they felt the desire.

I'll try to knock up a patch when I have some free time.

**Comment by tobes** [comment]
closing as #1249 does this in a cleaner way.  Thanks for this though as it got attention to the issue

**Pull request closed without merging**
