### PR TITLE
check_tcp module: add IPv6 support

### PR DESCRIPTION
**Pull request by bbusse**

### CODE REVIEW

**Comment by ultrabug** [comment]
Hello and thank you for your contribution @bbusse ; could you check and make CI happy please?

**Comment by lasers** [comment]
```diff
diff --git a/py3status/modules/check_tcp.py b/py3status/modules/check_tcp.py
index 3614d0b..3b76f68 100644
--- a/py3status/modules/check_tcp.py
+++ b/py3status/modules/check_tcp.py
@@ -47,7 +47,7 @@ class Py3status:
 
         try:
             result = sock.connect_ex((self.host, self.port))
-        except:
+        except socket.gaierror:
             sock = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
             result = sock.connect_ex((self.host, self.port))
 

```

**Comment by bbusse** [comment]
Patch updated

**Comment by ultrabug** [comment]
Thank you!

**Pull request merged**
