### PR TITLE
flake8: resolve several warnings and errors

### PR DESCRIPTION
**Pull request by lasers**

### CODE REVIEW

**Comment by ultrabug** [comment]
alright, big wanda boy

**Comment by tobes** [comment]
hmm, might have been nicer just to change the .tox file I really don't like the `# noqa e722` that have been added throughout the code it is going to be really hard to unpick this because bare excepts are bad but some we need - now we don't know which are which :(

I think that also no comment on the PR is crazy bad

**Comment by tobes** [comment]
@lasers   fedora_updates has been broken and I suspect other modules too.  You need to be really careful about knowing exactly what your changes are doing especially if you are changing things you are not testing

another quick look finds `except (IOError, FileNotFoundError): # py2/py3` this is untested and does not work because `NameError: name 'FileNotFoundError' is not defined` in python2

@ultrabug are you ok reverting this?  We can then fix these properly one at a time

**Comment by lasers** [comment]
Looking at `fedora_updates`, I should have `noqa` the `b` line. Everything is tested except for `address invalid escape sequences` commits which `fedora_updates` falls under. Is it just the `b` line that need to be undo? I separate commits so we can look at each.

**Comment by lasers** [comment]
For me, `FileNotFoundError` is what python3 threw. `IOError` is what python2 threw.

**Comment by tobes** [comment]
The `address invalid escape sequences` are all broken can you think why this is?

Or put another way what did you commits do?

`FileNotFoundError` `IOError` where are these defined?  How did you test your changes?

**Comment by lasers** [comment]
To make it work in `python2`?

There are 3 `address invalid escape sequences` commits. We can undo all three.

>FileNotFoundError IOError where are these defined? How did you test your changes?

To get those exceptions, I remove the `try/except` and run modules under `python2 module.py` and `python3 module.py`. Those are what came up. Those particular errors might had to do something with importing things outside of classes.

Four commits here with that error.
```
flake8 + player_control: except 4 Errors
flake8 + yubikey: except FileNotFoundError, Exception
flake8 + rt: except ImportError, ModuleNotFoundError
flake8 + rate_counter: except IOError, FileNotFoundError
```

I undo them all in last commit `small changes to pass travis cli`.

**Comment by tobes** [comment]
Sorry I'm a little tired.

Anyhow I think the bare exception changes are hiding the issue not fixing it.  IMHO it is better to have an error than to hid it.  But they were not breaking travis from what I can tell.

**Comment by tobes** [comment]
`self.py3.error(str(self.error), self.py3.CACHE_FOREVER)` this also feels wrong to me the `str()` shouldn't be needed (or is the wrong place) and the `self.py3.CACHE_FOREVER` is papering over an issue that should be fix in the proper place

**Pull request merged**
