### PR TITLE
Use f-strings

### PR DESCRIPTION
**Pull request by eumiro**
Since `py3status` is Python 3.6+, we can use f-strings for immediate string formatting. Some templates will be still formatted later using `.format`.

### CODE REVIEW

**Comment by ultrabug** [comment]
I wonder why pyupgrade didn't catch most of them?

**Comment by ultrabug** [comment]
plz rebase mate?

**Comment by eumiro** [comment]
rebased, pushed.

I tried to reconstruct the `pyupgrade` (both with `py3-plus` and `py36-plus`) call with the older commit, but did not find anything. Anyway, now we're py3.6+.

**Comment by ultrabug** [comment]
Thanks mate

**Pull request merged**
