### PR TITLE
bluetooth: Report battery percentage if available

### PR DESCRIPTION
**Pull request by alextsits**
Support reporting the battery percentage of bluetooth devices if available.

### CODE REVIEW

**Review by lasers — COMMENTED** [review]
Use `battery` instead imho.
```diff
diff --git a/py3status/modules/bluetooth.py b/py3status/modules/bluetooth.py
index 56aec47..6d3711d 100644
--- a/py3status/modules/bluetooth.py
+++ b/py3status/modules/bluetooth.py
@@ -39,6 +39,7 @@ format_device placeholders:
     {address}          eg, 00:00:00:00:00:00
     {addresstype}      eg, public
     {alias}            eg, MSFT Mouse
+    {battery}          eg, 95
     {class}            eg, 1234
     {connected}        eg, False
     {icon}             eg, input-mouse
@@ -49,8 +50,6 @@ format_device placeholders:
     {servicesresolved} eg, False
     {trusted}          eg, True
     {uuids}            eg, []
-    {percentage}       bluetooth device battery percentage
-                       (use '[ {percentage}%]' in format_device to hide if not available)
 
 Color thresholds:
     xxx: print a color based on the value of `xxx` placeholder
@@ -132,11 +131,8 @@ class Py3status:
             for name, match in self.names_and_matches:
                 if match in interface_keys:
                     interface = {k.lower(): v for k, v in interfaces[match].items()}
-                    interface.update({"path": path, "uuids": []})
-                    percentage = None
-                    if "org.bluez.Battery1" in interface_keys:
-                        percentage = interfaces["org.bluez.Battery1"].get("Percentage")
-                        interface.update({"percentage": percentage})
+                    battery = interfaces.get("org.bluez.Battery1", {}).get("Percentage")
+                    interface.update({"path": path, "uuids": [], "battery": battery})
                     temporary.setdefault(name, []).append(interface)
                     break
 
```

**Comment by alextsits** [comment]
@lasers thanks for the review. Sure, I agree with your proposal. I was trying to keep the same name as the one in the DBus property, but from a user perspective, ``battery`` work better indeed.

**Comment by alextsits** [comment]
I made the suggested changes

**Review by lasers — APPROVED** [review]

**Comment by ultrabug** [comment]
Thanks for your first contribution @alextsits !

**Comment by ultrabug** [comment]
(As always, thanks for your reviews @lasers)

**Pull request merged**
