### PR TITLE
formatter: fix lost left brace

### PR DESCRIPTION
**Pull request by lasers**
Print `hello_world` (before) vs `{hello_world` (after).
```diff
diff --git a/py3status/modules/static_string.py b/py3status/modules/static_string.py
index dbcec8c6..1df42b9b 100644
--- a/py3status/modules/static_string.py
+++ b/py3status/modules/static_string.py
@@ -16,7 +16,7 @@ class Py3status:
     """
     """
     # available configuration parameters
-    format = 'Hello, world!'
+    format = '{hello_world'
 
     def static_string(self):
         return {
```

### CODE REVIEW

**Comment by tobes** [comment]
@lasers could you add some explanation to this this PR so i can understand why you want it?

If it is a bug fix can you give an example of the bug you are trying to fix - thanks

**Comment by lasers** [comment]
I was testing something and I happen to miss a right bracket `}` in my `format`.

In the terminal, I saw it didn't print any brackets... only to find that I see I do have a left bracket. I tried this with right bracket too and saw that it showed up okay... so I went out on making this PR.

The worst offender is this... as it eats absolutely all right brackets.

```diff
commit 24a8eb42c175972d9d7690533f58858ea55e3e07
Author: lasers <lasers@users.noreply.github.com>
Date:   Sun Jul 29 22:46:18 2018 -0500

    wip missing brackets

diff --git a/py3status/modules/static_string.py b/py3status/modules/static_string.py
index dbcec8c6..2c27fef3 100644
--- a/py3status/modules/static_string.py
+++ b/py3status/modules/static_string.py
@@ -16,12 +16,17 @@ class Py3status:
     """
     """
     # available configuration parameters
-    format = 'Hello, world!'
+    format = '{{{ultrabug}}}'  # expect {{ultrabug}}, got ultrabug
+    # format = '{ultrabug}}}}}'  # expect ultrabug}}}}, got ultrabug
+    # format = '{={ultrabug}}'   # expect ={ultrabug}, got ={ultrabug
 
     def static_string(self):
+        items = self.py3.get_placeholders_list(self.format)
+        data = {x: None for x in items}
+        self.py3.log(data)
         return {
             'cached_until': self.py3.CACHE_FOREVER,
-            'full_text': self.py3.safe_format(self.format),
+            'full_text': self.py3.safe_format(self.format, data),
         }
 
 
```

**Comment by lasers** [comment]
I don't think an error should be reported because I slip up on this `format`. Print it as-is...

I still want to retain everything between `{` and `}` to better support strange use cases, ie conky.

**Comment by ultrabug** [comment]
still needed?

**Pull request closed without merging**
