### PR TITLE
bitcoin_price: new module from scratch

### PR DESCRIPTION
**Pull request by lasers**
bitcoin_price

Please merge the helper first https://github.com/ultrabug/py3status/pull/1129.

There are things in this module that may be hard to deprecate. Identical placeholders, different values, icky hack, some config... stuffs like that. I finished writing most of the module from scratch, but will be back later to polish this 💩 until it turns into a 💠.

To colorize stuffs... I removed a icky hack that only works with first item in the list... and we don't have to worry about age-old first line `# FIXME color_index param` anymore. We  favor `thresholds` now. I think maybe we should hide `thresholds` configuration from the public because it's basically not configurable unless users want certain colors for certain amounts... which would not make sense here.

Anyway, things be working fine and dandy.  I default `4` bitcoins for now so you can see how it will change colors over time... and I think it'd be nice to default `coinbase*` too.

P.S. No more cherrypicked data. This gets 1 or 2 json urls based on the placeholders. 🍒  We just need to work out a discussion about what to do with some things. Thx. 👍

### CODE REVIEW

**Comment by tobes** [comment]
From my point of view, we need to make these changes slowly so we make sure we catch all the intricacies.

These let's change everything PRs scare me.  I know it is a pain to do smaller more focused ones but that is the way to get things merged quickly.  Bigger PRs take a much longer time.  It can be frustrating, but it is how things are.

**Comment by lasers** [comment]
Close all modules from scratch?

**Comment by tobes** [comment]
> Close all modules from scratch?

I think you should aim to have less than 10 open.  It is different, if they are say documentation changes and you have one per module but currently you have 32 open and 3 are failing the tests.  (I can feel smug as I only have 4 - even if 2 are ~ a year old)

Each should be treated on it's own merits.  I admit that @ultrabug and I have been a little slow of recently, but we are doing better now, but having fewer PRs that are more focused helps all of us.  You are getting more experienced at this whole thing now, so mostly you know the answers I think.

**Comment by lasers** [comment]
>32 open and 3 are failing

1) Failing test due to mismatched `format` due to me still working on implementing more things for `bitcoin_price`... such as missing `format_datetime` and `thresholds` for other URL too. I fixed the `format` now.

2) Failing test due to https://github.com/ultrabug/py3status/issues/1027. :-(
3) Failing test due to exceptions madness and https://github.com/ultrabug/py3status/issues/1027. :-(

So that's... what? `0` or still `2` failing? 

Maybe it ain't right, but it's my style, I guess.
I even have a `htop` branch ready for `sysdata`. :-\

I'm doing this to help `py3status` get ahead with everything, then we can focus on new changes and/or new methods rather than module trivial fixes.

>so mostly you know the answers I think.

No, not really. Do someone want me to close those PRs? The alternative is I tell you which I feel is ready... then the users can drop in with issues and/or bug reports. `taskwarrior` is just like `window_manipulation` in a sense that it got really lot of shit and/or possibilities. Shame that users won't be able to see it. :'(

What's the step from here? Fuck it and close them right away or just wait until it get reviewed eventually? Or fuck it, merge as instructed? Potential hiccups for users?

**Comment by tobes** [comment]
> Failing test due to #1027. :-(

This is actually failing correctly.  I have a branch that solves all these issues with defaults that I should polish and make into a PR

> What's the step from here? Fuck it and close them right away or just wait until it get reviewed eventually? 

Maybe wait and we do a review of each slowly.  But it is also about you making new PRs that are friendly for reviewing and merging.  So not trying to fix the world in one PR but fixing it bit by bit.  I realise this can be frustrating.  It took me a long time to get to this view of distributed development.

If you take this PR even just reviewing the docstring changes will take me maybe 15 mins to do properly, and that is without even looking at the code changes, this is for a module I don't use too, so it is not something like volume status that I use every day.

We'll get there but it takes a little time

**Comment by lasers** [comment]
@tobes What do you think about this?

Rather than depreciating everything slowly, `py3status` can use `--include` user-written modules from those directories. We make `modules_testing` next to `modules` and notify the users about the changes.

If users want to try `testing` earlier, they can do `general { testing = True }` which would `--include` that directory. Maybe users will need to do `general { testing = False }` to turn off the notification about the changes.

This could mean we put all new (untested) modules in `testing` right away... and those new formatting stuffs? Well, I'm sure that can go in that directory too... When we finished clearing out all those PRs via this way... then that's when we start documenting everything. The new changes would be already inside the `testing` directory... and we have much fewer number of PRs again. We then remove `testing` in `4.0` or so.

**Comment by lasers** [comment]
I made attempts to deprecate the last `DEPRECATION TODO`. Nothing came out of it. This is `substitute_by_value` with no specific value. There are many renamed things so I do not know which config I should retrieve... That specifically is last thing left.
```
            'substitute_by_value': [
                {
                    'param': 'field',  # parameter to be checked for substitution
                    'value': 'xxx',  # anything
                    'substitute': {
                        'param': 'format',  # parameter to be updated
                        'value': '{xxx}',  # anything
                    },
                    'msg': 'obsolete parameter use `format = "{xxx}"`',  #message
                },
            ],
```
P.S. I added `storage` support too. The users won't lose their colors between restarts.

**Comment by lasers** [comment]
>I think you should aim to have less than 10 open.

I'm trying to clean out my PRs right now. Hence me not putting out any bugfixes, issue closers, or new modules until I reach less than 1 open.

>I can feel smug as I only have 4 - even if 2 are ~ a year old)

:-) I'm trying to reach less than 1 open. What about my modules? You did review `hueshift`. That bug is not related to `hueshift` as it was correctly before that PR. Maybe merge that module and fix the thread later? Or I close `hueshift` to reach less than 1 open?

>so mostly you know the answers I think.

I get this. I made efforts to go through several modules though. You could focus more on some other exciting stuffs on py3status side. There are over 90 modules and I was only trying to rewrite some of them from scratch to get more benefits out of them... as well as to address old formats, things I think is bad codes, etc.

I still want to revisit my pull requests as I don't remember some of them now so this will be good to correct my mistakes. Anyway, I reviewed this module again and had made more enhancements. This can be merged or closed now. You pick. :-)

P.S. This acts like `coin_market` now on purpose.
* New default markets. Not practical to default markets w/ different currencies. Just like `coin_market`, we default one thing. It ought to be familiar and/or popular. I used `coinbaseUSD`.
* New default separator. `', '` to `' '`
* New default format.
* I did all deprecation I can add. However, if users have existing format, they will lose colors. Your code would prevent me from prefixing users `format` with `\?color=` anyway. And the original `bitcoin_price` code for colors were not exactly great. You have to configure it or something with `color_index = -1`... and have only one market... or to specify `color_index` if you have more markets. I just have colors working in this branch by default.

Even if I made mistakes somewhere, I think users would appreciate having this PR merged.

**Pull request closed without merging**
