### PR TITLE
Prevent error when i3status does not return timezone info (issue 362)

### PR DESCRIPTION
**Pull request by tobes**
Fixes issue #362

### CODE REVIEW

**Comment by ultrabug** [comment]
I'm confused since #362 got closed already, is it a code hardening PR ?

**Comment by tobes** [comment]
Yes, but now that it has been fixed I'm not sure if we should try to give the user a better error or just hide the issue (which is what this does)

**Comment by ultrabug** [comment]
I'd say leave it as-is tbh

**Comment by tobes** [comment]
Cool if we get another problem with the Timezone thing then we can look at a 'proper message' for the user.

**Pull request closed without merging**
