### PR TITLE
Notify when battery is running low

### PR DESCRIPTION
**Pull request by maximbaz**
With this simple change it is now possible to receive notifications when battery level becomes low (<30%) or critically low (<10%).

To achieve that, the following configuration parameter must be set in `.i3status.conf`:
```
battery_level {
  ...
  notify_low_level = true
}
```
Notifications have different urgency levels, which can be used by notifications daemon to choose colors, timeouts, etc. For example, my notification daemon is configured to display "urgent" notifications in red, and they will not hide automatically, comparing to "normal" notifications.

selection_013
selection_016

### CODE REVIEW

**Comment by ultrabug** [comment]
thanks @maximbaz that's a good idea indeed. my only concern is that I found the work of @ben-e-whitney very interesting on PR #137 who introduced thresholds

would you mind having a look at this too ?

**Comment by maximbaz** [comment]
Had a quick look, I think this change won't conflict with the idea of custom thresholds introduced in #137. It is still the same number of "slices" (statuses that battery can be): [0..9% -> bad, 10..29% -> degraded, 30..99% -> good, 100% -> full]. The only difference is that the thresholds become configurable, rather than hardcoded values of 10%, 30% and 100%.

I can see from the discussions that the final outcome/expectation of #137 is finalized yet. I think it is safe to merge this change, but warn @ben-e-whitney to rebase and consider notifications for `degraded` and `bad` states once they find time to finish their PR.

**Comment by ben-e-whitney** [comment]
I will gladly rebase and look through these changes before resubmitting my pull request. Thanks for the heads up.

**Comment by maximbaz** [comment]
So what do you say @ultrabug, should we merge this PR?

**Comment by ultrabug** [comment]
@maximbaz yes, done thanks !

**Pull request merged**
