### PR TITLE
Support a different type of battery

### PR DESCRIPTION
**Pull request by bpinto**
On my computer the key values are named differently.

### CODE REVIEW

**Comment by bpinto** [comment]
I couldn't figure out how to get the tabs/spaces working. Sorry.

**Comment by tobes** [comment]
Thanks for this

> I couldn't figure out how to get the tabs/spaces working.

It's complaining the line is too long
```
battery_capacity = (r.get("POWER_SUPPLY_ENERGY_FULL") or
    r.get("POWER_SUPPLY_CHARGE_FULL"))
```
would fix it, note the extra `(` `)` there are other ways you could also fix it

**Comment by bpinto** [comment]
@tobes updated.

**Comment by tobes** [comment]
@bpinto thanks looks good

**Comment by ultrabug** [comment]
Thanks a lot for your contribution @bpinto !

**Pull request merged**
