### PR TITLE
Add possibility to color mpd_status

### PR DESCRIPTION
**Pull request by daedric**

### CODE REVIEW

**Comment by ultrabug** [comment]
Thanks @daedric, this is a good idea indeed :)

Please, sort your new color class parameter alphabetically on the list of available config. vars before I can merge this.

**Comment by daedric** [comment]
Done :)

**Comment by ultrabug** [comment]
Thanks a lot for your contribution @daedric

**Comment by daedric** [comment]
My pleasure. It also seems that the format string with {} are not handled properly by i3.
But it might not be a bug fix for Py3status but more i3, I'll take a look later :)

Cheers,

**Comment by ultrabug** [comment]
That's what has been fixed by version 2.1 released a few hours ago mate :) see issue #51

**Comment by daedric** [comment]
That was fast ! I'll wait for pip package to catch up then !
Thanks !

**Pull request merged**
