### PR TITLE
vpn_status module: fix changed dbus signal handler signature

### PR DESCRIPTION
**Pull request by ultrabug**
backward compatible version of #2070 thx to @oceyral

### CODE REVIEW

**Comment by ultrabug** [comment]
@oceyral hi, this PR should be backward compatible with both what you have and what I still have on my laptop

Can you check that it works for you please?

**Comment by oceyral** [comment]
Hi, works for me.

**Comment by ultrabug** [comment]
Thanks @oceyral ; you might be happy to know that any active VPN connection will be detected on start/reload of the module now too ;)

**Comment by oceyral** [comment]
Yeah, I saw that second commit, nice to have !

**Pull request merged**
