### PR TITLE
add new module: wanda_the_fish 

### PR DESCRIPTION
**Pull request by lasers**
Hi. I made a new module `wanda_the_fish`. This module display a fortune-telling, swimming fish.

There was a nice little GNOME2 panel applet where it displays an animated character (a fish) which pops up quotes generated by `fortune`. Simply put, there are people out there who adores `wanda_the_fish` too much. People also made this possible for other DEs too, but we still don't have one for `i3wm`. :frowning_face: 

Now with this module, we can start appreciating `wanda_the_fish` and her fortunes again. :tropical_fish:  :blush: :heart_eyes: :heart_eyes:

wanda_0
wanda_1
wanda_2
wanda_3
wanda_4
wanda_5

### CODE REVIEW

**Comment by cyrinux** [comment]
So cute ! <3

**Comment by lasers** [comment]
@maximbaz Hi again. :blush: I split up two commits here for you to play with... One with dedicated buttons. One without dedicated buttons. I wanted you to understand what I was trying to do with your PR... using this example.

Truth be told, `button_refresh` shouldn't be added here in first place because it does not query anything from Internet... so let's just pretend it is not there in first place. It should be removed either way anyway. Anyway, okay... so it's just one dedicated button now... `button_toggle` to toggle fortunes from `wanda_the_fish`


Now, I want to preface that it is possible to add a dedicated button, but it's also possible to let it just work with all click events. I don't want to introduce a single button `button_toggle` config when we can avoid it in first place and wait for somebody to make another button with a different purpose than `button_toggle`. When that day come, then we can add that new button, `button_toggle`, and sometimes with third button `button_refresh`.

The experience between both commits is mostly same in the long run, but right now in the latest commit, `wanda_the_fish` will be more friendly than before... to all click events and the users have fewer configs because we didn't make them possible in first place...

Now with fewer configs, it should be easier for us to add new things than before. And because we still don't know what the new button does, we can make that decision later instead of right now along with other things we still don't know about... aside from the fact it need a button.

**Comment by maximbaz** [comment]
Thanks for making this demonstration 👍 

I totally see your point, it is valuable to avoid getting buried in maintaining backwards compatibility if it doesn't cost us much. 

Without having a dedicated `button_toggle` there is only a slight chance to hurt ourselves: by accidentally generating too many events with mouse scroll. But when this happens, the impact is low, both here and in `execute_script`. So I agree for not having a dedicated button to generate a fortune or show a notification with full script output.

`button_refresh` also makes sense to remove in this module. I wouldn't say `button_refresh` only relates to Internet, I think it can be generalized to "when it is expensive to refresh often". Internet traffic is valuable, so refreshing always is bad. External scripts can be slow or consume lots of CPU, so refreshing always is again bad. Generating fortunes is fast, so I don't see any issue with generating them on any click.

So, I think in the end we did agree on when to have a dedicated button and when not 🙂 

The only disagreement we have is what is better, have a button that by default does nothing, or let this button by default do some action (show notification) since it is unused — for that we are waiting third opinions 😉

**Comment by lasers** [comment]
The disagreement is about turning on the notifications by default on either dedicated button or all clicks for `external_script`.

I do always try to default buttons in many of my modules. I believe it is good to use `button_toggle = 1` to play/pause songs for many music modules, but I don't believe it is good to assign `button_prev` and `button_next` to scrolling `4, 5` by default.

I just don't believe that it is not good to assign `button_show_notificaiton` on `button_1`.

**Comment by ultrabug** [comment]
alright wanda, welcome aboard :)

**Pull request merged**
