### PR TITLE
backlight: better xbacklight detection

### PR DESCRIPTION
**Pull request by lasers**
Hi. Here's a bugfix. Just because the users can install `xbacklight`... does not mean `xbacklight` ought to be enabled internally in the module. For that, we need more than checking a command.

We need a better xbacklight detection.

When Linux distros and/or DE detects that the users are using a laptop, it can install `xbacklight` too... likely a part of laptop/other metapackage.

Having it installed does not necessarily mean that `xbacklight` are guaranteed to work out of the box... as some laptops can have native backlight support using Fn key. Some laptops can not have this feature too so the users would be left with a bad/broken module.

If you looked in the module, you can see that because you have `xbacklight` installed, it will try and get you a value from `xbacklight -get` instead of `/sys/class/backlight/???/brightness`... which can give you either nothing or an exception / error code.

The fix correctly turns off `xbacklight` so we can show the percent number natively.

Anyway... Here's how... In `post_config_hook`, we try few things.
* Is `xbacklight` installed? [y/n]
* Any error codes when running `xbacklight -get`?  [y/n] **NEW!**
* Any percent output when running `xbacklight -get`? [y/n] **NEW!**

P.S. I have more fun things for `backlight` in diff branch. Lemme know if you want it. This is just a worthy bugfix to get it working with my native backlight laptop. Thx. 👍 

EDIT: We could make do without `84: if self.py3.check_commands(['xbacklight']):`...

### CODE REVIEW

**Comment by tobes** [comment]
@lasers this is great.  upgrading to F26 broke backlight module for me 
```
$ xbacklight
No outputs have backlight property
```

This PR allows the module to show the backlight level correctly again.  However setting it does not work via `_set_backlight_level()` it would be amazing if we could fix that too.  If you don't want to do that, or want to do as a separate PR let me know.

Also thanks for the detailed PR message this really helps understand the reasons for the changes you made here.

I think I'd get rid of line 84 too and add a comment about why we do this xbacklight check.

**Comment by lasers** [comment]
Probably a different PR for now. Just checked that we can't use `xdotool key XF86MonBrightnessDown` because it does not work with hardware backlight.

If we want to, we can fake software backlight using `xrandr` command... but wouldn't conserve power at all.. so it's quite a misleading. It looks same / good.

I think maybe we just avoid the fake and use the real thing... The real thing likely will require a `sudo` privilege... just same as module `wifi`... I can try and add this in my branch.

**Comment by lasers** [comment]
Small report to make... I have issues with setting a backlight level in the script.

I can use sudoers to set a level interactively.
```
chris ALL=(ALL) NOPASSWD:/usr/bin/tee /sys/class/backlight/*/*brightness*
```
```
echo 0 | sudo -n tee /sys/class/backlight/acpi_video0/brightness
```
When it comes to script, it does not execute.

I tried `cat`, `tee`, python writing, etc.... along with various sudoers settings. If I read it correctly, sudoers doesn't allow any files to be edited, you have to supply a command too... so as I said, I tried various things... I added `backlight.py` in sudoers too... Nothing worked for me.

Additionally, I ponder if there is an issue of using `command_output(command, shell=True)` because it seems to ignore an error code from sudo... and does not trip the exception. The command again is...
```
echo 0 | sudo -n tee /sys/class/backlight/acpi_video0/brightness
```
With `sudo -n` (non-interactive)... If it requires a password, it's to end abruptly with an error code `1`... but we didn't pick it up... Idk. We just need to get everything in right place for `backlight` to work.

Also, I ponder about omitting `xbacklight` if we can get everything to work okay.... as it hadn't been updated for few years now... and it looks like the users may be starting to get `xbacklight`-related issues... so it might be nice if we can deal with this natively.

**Comment by lasers** [comment]
This is a bug fix. Please tag/approve. Ty.

**Comment by tobes** [comment]
Could you add `if self.xbacklight:` to `_set_backlight_level()`

then I think we are good to go.  Sorry I've been very busy this week.

**Comment by lasers** [comment]
All things that uses `_set_backlight_level()` already checks that. Still proceed?

**Comment by tobes** [comment]
Thanks this is a nice fixup 🔦

**Pull request merged**
