### PR TITLE
flake8 line length max 79

### PR DESCRIPTION
**Pull request by tobes**
This PR fixes line lengths to the PEP8 recommended max length of 79.

I have tried to do it in a way that minimizes the changes and maintains readability (something that yapf often fails at imho)

There are a few places where some refactoring was needed ( `xrandr_rotate.py`) but again I've tried to avoid this where possible.

### CODE REVIEW

**Comment by ultrabug** [comment]
I have mixed feeling about this, I'd like a third party to take part of the vote : @pydsigner ?

**Comment by pydsigner** [comment]
@ultrabug 160 character lines are definitely too long but I'd rather not throw down a 79 line restriction.

**Comment by tobes** [comment]
@pydsigner thanks for your response. What limit would you prefer?

@ultrabug why do you have mixed feelings?

Rather than just saying PEP8 my take would be this.  Restrictions are not always bad.  When I first started writing python I'd have had the same view, all this indentation making my lines head off to the right wtf!  But now I'd say that the whole 79 char limit has actually made me a much better coder. It makes me create much tighter code. It makes debugging stuff easier.  My code is more encapsulated.  So regardless of all the small screen (reading code on my phone) or in emails etc, which is a valid issue for me, overall it is about better code, not just to read, but mainly about helping others learn through the restrictions.

I'm an old fuck, and things change, and in many ways I don't care, but I'd not want others to not have the opportunities to improve that I've had.

Anyhow, I see two issues here.

1) are the code changes themselves acceptable?

2) can we knock the line length limit down to something more reasonable? 

A lot of this ends up in religious wars, vi/emacs or should the kernel be written in C++.  I don't claim to have any of the answers, but I'd like to think I have a small amount of insight. I'd be interested in what you think on line length and why.

**Comment by pydsigner** [comment]
For my personal coding, my *goal* is 80, but I'll allow a line to go to 100 if it makes things more legible. So it isn't that I don't like 79 character lines, it's that I don't want our QC to be broken by lines that *are* better a little longer. Whatever you put in flake8 is going to be an unbudgeable standard and that standard should be less strict.

**Comment by tobes** [comment]
>  lines that are better a little longer

If we really need a long line then we can always use `# noqa`.

Anyhow 100 would be a good start

**Comment by ultrabug** [comment]
I must say that at work we enforce a strong PEP8 / 80 chars policy which I'm fine with but I agree that for an OSS such as ours here, a bit of flexibility should prevail.

100 is it, okay and thanks !

**Comment by tobes** [comment]
> PEP8 / 80 chars 

PEP8 is 79

> 100 is it, okay and thanks !

99?  I've amended `tox.ini` if you really want 100 I'll update it again.

**Comment by ultrabug** [comment]
99 is good aye, cheers !

**Pull request merged**
