### PR TITLE
Allow module output to be used in commands

### PR DESCRIPTION
**Pull request by tobes**
#502 (copying module output to the clipboard) was an interesting idea.

So I've come up with a way that we can do this.  The idea is to be flexible so users can find their own uses for this.

With this PR I can now copy the output of a module to the clipboard on a left click

```
my module {
    on_click 1 = 'exec echo $OUTPUT | xclip -i'
}
```

Where `$OUTPUT` will be replaced by the output of the module.  `$OUTPUT_PART` will give part of the output if the module is a composite.  I'm quite happy to change the names for these substitutions if people can think of better ones.

In the future we could also extend this to get variables out of the module eg the output filename from screenshot module so a little thought around the naming for that might be nice too.

### CODE REVIEW

**Comment by ultrabug** [comment]
I find the idea and naming good. I only think that we're missing documentation here please ?

**Comment by tobes** [comment]
I've added some documentation.  I ended up splitting the on_click example into the sections they relate to as it made more sense.

**Comment by ultrabug** [comment]
Sorry @tobes but since you removed the `Example on_click usage on i3status.conf` section, the example displayed below the refresh and refresh_all special section is not relevant

**Comment by tobes** [comment]
Sorry my mistake I just saw something starting with r

should be fixed now

**Comment by ultrabug** [comment]
Thanks a lot !

**Pull request merged**
