### PR TITLE
volume_status: (pactl) update device

### PR DESCRIPTION
**Pull request by lasers**
For `pactl`: We update the device number now in loop (only when it is necessary) instead of `post_config_hook` using same `check_output` data. If device is assigned and is not available, we don't update the device number and will return `0%`. This should fully fixes https://github.com/ultrabug/py3status/issues/921.

### CODE REVIEW

**Comment by tobes** [comment]
@lasers could you explain this a bit more clearly.

Especially why you feel this is an improvement over the existing code.  What __specific__ issues is this fixing?

**Comment by lasers** [comment]
I don't know if it's an improvement, but it seems to be so from my side since I'm unable to use `self.py3.log()` here to test `self.device` change.

Instead of using `post_config_hook` to get a device number correctly only once, we use `0` and test it. If it didn't work, we then use the number from `check_output` data which will get us the correct device number... same as `post_config_hook`... except this is done in loop now... to ensure always a smooth sailing.

Before recent PR... `pactl` works correctly for only users with `0` device.
Recent PR... We get correct number for device on `post_config_hook`
New PR... We try `0` anyway. Get the new number in `try/except` loop if it's necessary... then smooth sailing... until the number changes, then we update the number again in `try/except`... then smooth sailing... etc.

The specific issue this fixes is that if users wanted to plug in a headphone on their laptop/computer, this might get us a new sink number... so we have `try/except` to handle that for us... and we then will work with new `self.device` number.

Here's what I get when playing with plugs...
```
$ while sleep 1; do pactl list short sinks; done
1       alsa_output.pci-0000_00_1b.0.analog-stereo      module-alsa-card.c      s16le 2ch 44100Hz       SUSPENDED
1       alsa_output.pci-0000_00_1b.0.analog-stereo      module-alsa-card.c      s16le 2ch 44100Hz       SUSPENDED
0       auto_null       module-null-sink.c      s16le 2ch 44100Hz       IDLE                                     
0       auto_null       module-null-sink.c      s16le 2ch 44100Hz       IDLE                                     
0       auto_null       module-null-sink.c      s16le 2ch 44100Hz       SUSPENDED                                
1       alsa_output.pci-0000_00_1b.0.analog-stereo      module-alsa-card.c      s16le 2ch 44100Hz       IDLE     
1       alsa_output.pci-0000_00_1b.0.analog-stereo      module-alsa-card.c      s16le 2ch 44100Hz       IDLE     
```

**Comment by tobes** [comment]
> I'm unable to use self.py3.log()

`self.parent.py3.log(...)`  I hate how this module is split out


> Here's what I get when playing with plugs...

could you explain this.  The output has no value without also knowing the actions that you have taken and also the actual output.  eg is the output always one line? what are the devices.  do you ever get any sound from them etc.

For me I only have a single sink.  Supporting multiple sinks seems useful but I want to understand how they interact.

**Comment by lasers** [comment]
>The output has no value without also knowing the actions that you have taken and also the actual output.

Not sure what the action is... It's either plugging things again... after `auto_null` and/or killing pulseaudio.

>eg is the output always one line?

One liner with `pactl list short sinks` to show `1`->`0`->`1`. We use (non-short) command in code.

>What are the devices. do you ever get any sound from them etc.

Front PC headphone jack. Dunno about sound. Although I get nothing with `auto_null`, I saw a changed volume percent (between devices) so that's good enough for me to know it worked... because `auto_null` shouldn't work. You might be able to trigger a number change with `killall pulseaudio` too.

We do this to prevent `volume_status` from throwing an bar exception due to `AttributeError: 'NoneType' object has no attribute 'groups'` (from `1`->`0`). A bit of code change to make it work always with correct number (even if it's auto_null) instead of eventually tripping in the future.

**Comment by ultrabug** [comment]
Friendly bump here, not sure where to stand

**Comment by ultrabug** [comment]
Also, plz rebase?

**Comment by ultrabug** [comment]
Sorry, adding context to my answer: I see that #921 is closed, that's why I'm not sure where to stand

**Comment by lasers** [comment]
@ultrabug Rebased. My PR #922 does it in `post_config_hook` only. This is done in loop so if for some reason, the device number changed (it did here last time I tested this ; don't remember how I did it right now), it would be updated with a new number.

Without this PR, the users could receive `volume_status: AttributeError` when they're mucking around with... (ie, pulling headphone, plugging headphone, killing pulseaudio, IDK examples). This just make make things a bit more automatically.

Things I want to point out...
1) Note that `english_env` stuffs only applies to `pactl`... Not `paxmier` or `alsa`. :-(
2) Do we want to reorder the list so pulseaudio binaries could go first since it may be more popular now and already installed by default on most Ubuntu flavors (and many other distros)? 

    The reason the users may install alsa nowadays could be because they need it for some applications and/or games.

**Comment by ultrabug** [comment]
Okay, let's keep it that way for now please.

Please rebase

**Comment by lasers** [comment]
Cannot recall the steps I made to reproduce this issue. Tried things. Rebased.

**Comment by tobes** [comment]
@lasers I'm going to close this as from what I can see this is no longer needed.  If you feel it is then reopen it and we can review.

**Comment by lasers** [comment]
IIRC. People can get this bug if their input/output device number changed due to changed sources/sinks which generally does not happen often and the users will just do `i3-msg restart` to fix it instead of filing an issue. I'm okay either way.

**Pull request closed without merging**
