### PR TITLE
Allow hiding on error, fix a ValueError exception

### PR DESCRIPTION
**Pull request by girst**
I am often not running mpd/mopidy in the background, and then all I can see is an ugly error message. This patch allows you to set a new flag, `hide_on_error`, to --well-- hide it then. 

Also, got [this in my logs](https://pastebin.com/Bxt2NjYq) whenever I reversed a playlist (with mopidy -- classic mpd might handle this differently), so I fixed that as well. (`status.get('song')` can return `None`, and then the `int()` fails. )

---
 Ceterum censeo #MCLXXV esse contexendum

### CODE REVIEW

**Comment by lasers** [comment]
Preserving the logs just in case.
```
2018-03-08 11:18:18 WARNING Instance `mpd_status`, user method `current_track` failed
    (ValueError) mpd_status.py line 155.

2018-03-08 11:18:18 INFO Traceback
ValueError: invalid literal for int() with base 10: 'None'
  File "/***/py3status/module.py", line 732, in run
    response = method()
  File "/***/py3status/modules/mpd_status.py", line 155, in current_track
    next_song = int(status.get('nextsong', 0))
```

**Comment by girst** [comment]
> I don't like all those hide_* options. 

well, they work. 

ad patch: that threw the same valueerrors again. :/

**Comment by lasers** [comment]
>that threw the same valueerrors again. :/

Any chance you were trying with a different `--include` `mpd_status` module?

**Comment by tobes** [comment]
I think we should be doing this via `py3.error()` https://py3status.readthedocs.io/en/latest/py3.html#error

That allows better error handling - expand/hide etc

**Comment by lasers** [comment]
`'None'` is a string, not NoneType. D'oh. This should work now.
```
diff --git a/py3status/modules/mpd_status.py b/py3status/modules/mpd_status.py
index 5a83be4d..58855fac 100644
--- a/py3status/modules/mpd_status.py
+++ b/py3status/modules/mpd_status.py
@@ -150,8 +150,12 @@ class Py3status:
     def current_track(self):
         try:
             status = self._get_mpd().status()
-            song = int(status.get('song', 0))
-            next_song = int(status.get('nextsong', 0))
+
+            song = status.get('song', 0)
+            song = 0 if song == 'None' else int(song)
+
+            next_song = status.get('nextsong', 0)
+            next_song = 0 if next_song == 'None' else int(next_song)
 
             state = status.get('state')
 
```

**Comment by girst** [comment]
@lasers: my approach (with except valueerror) keeps all the failure cases together, which i like. I have cleaned the error cases up a bit in e310ed4 though. 

@tobes: throwing py3.error makes it impossible to hide the module though. I thought about logging the error to py3.log, but that'll clutter the logfile (seeing "Failed to connect to mpd" every two seconds is a bit excessive, and we can't (shouldn't) overwrite the user's timeout there, in case the mpd goes online)

**Comment by ultrabug** [comment]
Sounds fair enough to me, thanks mate

**Comment by girst** [comment]
Hi, thanks for merging. Could you please take a look at #1175? It's been ready for months now.

**Pull request merged**
