### PR TITLE
add changelog 3.8

### PR DESCRIPTION
**Pull request by lasers**
`CHANGELOG 3.8`. I removed typos commits, screenshot pain commits, little correction commits, extraneous commits, feedback commits, etc. This is what I'm left with right now.. Currently at 99 lines.

### CODE REVIEW

**Comment by girst** [comment]
>implement IMAP4 IDLE in imap to use imaplib2's idle()

we don't use imaplib2 -- my idle is implemented on top of the python standard library imaplib

**Comment by lasers** [comment]
Give me a commit message to use.

**Comment by lasers** [comment]
@ultrabug You could tell me what to remove. Do we want this too?
`fix gevent patch_subprocess side effect on py2 decoding, by @Ultrabug`

**Comment by lasers** [comment]
RE: `* fix deadbeaf error, by @tobes`

This PR does not change anything. Do you want to fix this before `3.8`? 
* PR 1: Deprecate 7.0, 7.1  (easy fix) 
* PR 2: Use helper (simplifying many, many lines)

**Comment by girst** [comment]
older CHANGELOGs don't just use a commit message (and are differently formatted than your PR). So how about: 

```
imap: support for IMAP-IDLE; enabled by default, by @girst
```

**Comment by ultrabug** [comment]
Thanks a lot for your effort, I'll start from there

**Pull request merged**
