### PR TITLE
Add new module 'redshift'

### PR DESCRIPTION
**Pull request by sajran**
I wrote this module because I wasn't satisfied with "hueshift". My module allows to run and kill redshift running in continuous mode and to display some current parameters.

### CODE REVIEW

**Comment by lasers** [comment]
Thank you for this contribution. :)

My module hueshift is different in that it offer users more flexibility (i.e. static/toggleable adjustable color temperature to use). Can I ask why you (and users) should not use redshift tray applet instead which seems to be doing a same thing? Tray applet is part of redshift and does offer similar information on hovering tooltip?

**Comment by sajran** [comment]
Well, it's kinda blunder on my part because I didn't really remember it existed. I just installed redshift and then went looking for py3status module. However now that I installed it I have to say my module is more aesthetic for sure, on the other side it lacks some functionality of the tray applet (temporary suspending redshift). I will totally understand if you'll find this module redundant in such situation.

Also, sorry for all those failed tests, I'm not really experienced in these kind of things :).

**Comment by lasers** [comment]
Maybe you will like `redshift` on `i3pystatus` module.
```python
order += "i3pystatus redshift"
i3pystatus redshift {
    module = "redshift"
}
```
I opened an issue relating to `i3pystatus` module just now. You would have to checkout `68dbf44` there on `i3pystatus` to see this working. The color temperature continuously changes too.

**Comment by sajran** [comment]
Thank you, I didn't know about `i3pystatus`.

Also, what do I do now, should I close this PR?

**Comment by maximbaz** [comment]
Hey guys, I'm just curious, what if we incorporate toggling redshift into `hueshift` module? @sajran if that functionality existed, would you be using hueshift, or your custom module / i3pystatus one is still preferable?

**Comment by lasers** [comment]
>Also, what do I do now, should I close this PR?

@sajran I think so. The decision is up to you or others. I made hueshift so I do nothing here. :) 

Also, I see we can make or use existing systemd unit to enable/disable. https://wiki.archlinux.org/index.php/Redshift which could be done with `static_string` + `on_click 1 = exec ~/.bin/toggle-redshift.sh` (simple pgrep / else script?)

Not to mention that `i3pystatus redshift` does what you aim to do here (minus some placeholders). Fix `i3pystatus` module and then you can use that one. Otherwise, you can see if you do still use it in the long run versus minimal alternative options.

@maximbaz I think it would be complicated because hueshift can manage `blueshift` and `sct` too.

**Comment by sajran** [comment]
If `hueshift` would allow toggling redshift and displaying live temperature I would happily use it.

**Comment by sajran** [comment]
@lasers Thank you for all the info, I'll think what to do next about it and for now I'm closing PR

**Pull request closed without merging**
