### PR TITLE
Spotify.py module fix

### PR DESCRIPTION
**Pull request by Kuchenm0nster**
There was no get method for metadata. Metadata is a dictonary so [ ] is doing fine.

Got some problems with playback status which freezes my script.

### CODE REVIEW

**Comment by ultrabug** [comment]
Hi @Kuchenm0nster thanks for this proposal and congratulations for your first PR :)

I'm a bit surprised since the spotify module has been updated recently. Can you please tell me the spotify version you're running on your machine ?

Thanks

**Comment by Kuchenm0nster** [comment]
1.0.19.106-1



Am 15. Dezember 2015 19:05:53 MEZ, schrieb Ultrabug <notifications@github.com>:
>Hi @Kuchenm0nster thanks for this proposal and congratulations for your
>first PR :)
>
>I'm a bit surprised since the spotify module has been updated recently.
>Can you please tell me the spotify version you're running on your
>machine ?
>
>Thanks
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ultrabug/py3status/pull/149#issuecomment-164842615

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ultrabug** [comment]
ok @Kuchenm0nster this looks weird to me since this should have been fixed in #130 .

@epaaj @guilbep : any of you guys have remarks or suggestions about this please ?

Sorry @Kuchenm0nster, I'm no spotify user so it's hard for me to be more active in this.

**Comment by Kuchenm0nster** [comment]
@ultrabug my bad, looks like i made a mistake, the get method is working but "playback_status" isnt working for me. Somehow it freezes my pc 
`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'PlaybackStatus'` 
is not working as well so maybe it is just my arch having some problems, sorry.

**Comment by ultrabug** [comment]
@Kuchenm0nster it's okay mate. It's still strange that this freezes your machine :(

Meanwhile, can we close this PR ?

**Comment by guilbep** [comment]
@ultrabug I stopped using spotify a while ago. I'll have to reinstall it on my machine. I'll keep you posted

**Comment by ultrabug** [comment]
closing then, thanks guys

**Pull request closed without merging**
