### PR TITLE
i3pystatus: remove composites and keys to make dicts more comparable

### PR DESCRIPTION
**Pull request by lasers**
When `safeformat` was added to support universal/py3status options, it comes with a new bug (interval). It can create `composite` keys which can lead to unequal contents and frequent updates. I get the first (and only) dict from the composite to make it more comparable.

Even with this fix, I notice that unequal contents and frequent updates were still occurring sometimes so I looked into this. The reason for this is because of various changes... including initial `None`, and that we don't always get `name` and `instance` from the output and/or the composite. In some instances, `module_name + index number` can appear in the dict too. Also, `{"full_text": ""}` is not same as the empty full_text dict with name + instance.

I had two options: To fill the dicts with missing keys or to remove the keys. I opted for latter.

This occurs on both `output` and/or `last_content`. Initially, it will be different, then it will keep using output (and sometimes `composites` which then will be moved around, deleted, etc) before we compare this.

This basically removes `composite`, `name`, `instance` leaving us only `full_text` and `color` to ensure that dicts are more comparable so the intervals shouldn't occasionally be reset back to 1.

Unrelated: I realized that if both contents are same, we do not have to get full_text, check if it is a tuple, safe_format same content again, etc so I move all this to new content only.

### CODE REVIEW

**Comment by ultrabug** [comment]
I must admit that I never rly tested this module anyway, so I'll trust your tests.

Could have been cool to have a user input, maybe you know this module @maximbaz ?

**Comment by lasers** [comment]
@ultrabug Logs.

```python
order += "i3pystatus dpms"
i3pystatus dpms {
    interval = 30       # interval always capped at 15 or less
    module = 'dpms'
}
```
Master.
```
09:59:24 INFO ========
09:59:24 INFO method run returned
    {'full_text': '', 'instance': 'dpms', 'name': 'i3pystatus'}
                                                # interval tripped (OK)
                                              # interval back to 1
2019-04-06 09:55:07 INFO method run returned {
    'color': '#FFFFFF', 'composite': [
        {'full_text': 'DPMS: on', 'instance': 'dpms 0', 'name': 'i3pystatus', 'color': '#FFFFFF'}
    ], 'instance': 'dpms', 'name': 'i3pystatus'
}
                                                # interval tripped (OK)
                                              # interval back to 1
09:59:24 INFO method run returned {
    'full_text': 'DPMS: on', 'color': '#FFFFFF', 'instance': 'dpms', 'name': 'i3pystatus'}
09:59:25 INFO method run returned {..same..}
09:59:27 INFO method run returned {..same..}
09:59:31 INFO method run returned {..same..}
09:59:35 INFO method run returned {..same..}
09:59:44 INFO method run returned {..same..}
09:59:59 INFO method run returned {..same..}  # interval 15
                                              # interval tripped (not OK)
                                              # interval back to 1
10:00:00 INFO method run returned {..same..}
10:00:01 INFO method run returned {..same..}
10:00:03 INFO method run returned {..same..}
10:00:07 INFO method run returned {..same..}
10:00:14 INFO method run returned {..same..}
                                              # minute passed
10:00:29 INFO method run returned {..same..}  # interval 15
                                              # interval tripped (not OK)
                                              # interval back to 1
10:00:30 INFO method run returned {..same..}
10:00:31 INFO method run returned {..same..}
10:00:35 INFO method run returned {..same..}
10:00:39 INFO method run returned {..same..}
10:00:44 INFO method run returned {..same..}  # interval 15
10:00:59 INFO method run returned {..same..}
                                              # interval tripped (not OK)
                                              # interval back to 1
10:01:00 INFO method run returned {..same..}
10:01:01 INFO method run returned {..same..}
10:01:03 INFO method run returned {..same..}
10:01:11 INFO method run returned {..same..}
10:01:14 INFO method run returned {..same..}  # interval 15
                                              # minute passed
                                              # interval back to 1
10:01:29 INFO method run returned {..same..}
# interval tripped (not okay)
10:01:30 INFO method run returned {..same..}
10:01:31 INFO method run returned {..same..}
10:01:35 INFO method run returned {..same..}  # interval 15
10:01:43 INFO method run returned {..same..}
                                              # interval tripped (not OK)
10:01:44 INFO method run returned {..same..}  # interval 15
                                              # interval back to 1
10:01:59 INFO method run returned {..same..}
                                              # interval tripped (not OK)
                                              # interval back to 1
10:02:00 INFO method run returned {..same..}
```
This PR. 
```
10:04:41 INFO ========
10:04:41 INFO method run returned {
    'full_text': '', 'instance': 'dpms', 'name': 'i3pystatus'}
                                              # interval tripped (OK)
                                              # interval back to 1
10:04:41 INFO method run returned {
    'color': '#FFFFFF', 'composite': [
        {'full_text': 'DPMS: on', 'instance': 'dpms 0', 'name': 'i3pystatus', 'color': '#FFFFFF'}
    ], 'instance': 'dpms', 'name': 'i3pystatus'
}
                                              # interval tripped (OK)
                                              # interval back to 1
10:04:42 INFO method run returned {
    'full_text': 'DPMS: on', 'color': '#FFFFFF', 'instance': 'dpms', 'name': 'i3pystatus'}
10:04:43 INFO method run returned {..same..}
10:04:47 INFO method run returned {..same..}
10:04:55 INFO method run returned {..same..}
10:04:59 INFO method run returned {..same..}  # interval 15
10:05:14 INFO method run returned {..same..}
10:05:29 INFO method run returned {..same..}
                                              # minute passed
10:05:44 INFO method run returned {..same..}
10:05:59 INFO method run returned {..same..}
10:06:14 INFO method run returned {..same..}
10:06:29 INFO method run returned {..same..}
                                              # minute passed
10:06:44 INFO method run returned {..same..}
10:06:59 INFO method run returned {..same..}
10:07:14 INFO method run returned {..same..}
10:07:29 INFO method run returned {..same..}
                                              # minute passed
10:07:44 INFO method run returned {..same..}
10:07:59 INFO method run returned {..same..}
10:08:14 INFO method run returned {..same..}
10:08:29 INFO method run returned {..same..}
                                              # minute passed
10:08:44 INFO method run returned {..same..}
```

**Comment by maximbaz** [comment]
I've never used this module, so I trust your judgement 👍

**Comment by lasers** [comment]
`i3pystatus dpms` + `i3pystatus ping` works for me okay. Modules outputting tuples remains untested.

**Pull request merged**
