### PR TITLE
Add load average to sysdata module

### PR DESCRIPTION
**Pull request by guiniol**
This PR adds `{load1}`, `{load5}` and `{load15}` to sysdata.

### CODE REVIEW

**Comment by guiniol** [comment]
I built this PR on top of #449

**Comment by tobes** [comment]
@guiniol you have the zone changes in this

**Comment by guiniol** [comment]
sorry. I think I need to reorganise the PR. All three PRs need to be on top of 0ccd248. So, one PR for 0ccd248, and then one for each feature.

**Comment by tobes** [comment]
0ccd248 is the PR That is the least likely to get merged as it involves threshold changes and that it something I'm keen on getting standardized in py3status see #451 

Also really we want to allow all thresholds to work with this module so would show correct color for `{mem_used}` `{cpu_usage}` etc so that should be done at the same time

**Comment by guiniol** [comment]
Alright. I should have started there.
Do you have an example of components?
Since I have started working on this, I might as well do the job in the right way.

If I understand correctly, components allow for coloring part of the output of one module. In that case, each we should have one component for each type of value, and have the respective thresholds. It does raise a new question: how do we handle `mem_used` vs `mem_used_percent`? We could choose one value which would give the color for this component, eg. `mem_used_percent`.
If that sounds right, I'll do it tonight.

**Comment by guiniol** [comment]
Let's continue the discussion in #449. I'll add the functionnality once we agree on the base ^^

**Comment by tobes** [comment]
> Do you have an example of components?

Documentation here
https://github.com/ultrabug/py3status/blob/master/doc/README.md#composites

modules group, frame, timer and rainbow use it

> how do we handle mem_used vs mem_used_percent? 

they would colour the same way

**Comment by guiniol** [comment]
> Documentation here
https://github.com/ultrabug/py3status/blob/master/doc/README.md#composites
> modules group, frame, timer and rainbow use it

Thanks

> > how do we handle mem_used vs mem_used_percent?

> they would colour the same way

My point exactly. So, I'm for using `mem_used_percent` to decide on the color.

**Comment by guiniol** [comment]
I'm still a bit unclear on some things.
For example, let's say we keep the default
```python
format = "CPU: {cpu_usage:.2f}%, Mem: {mem_used:.2f}/{mem_total:.2f} GB ({mem_used_percent:.2f}%)"
```
This should be split in two composites:
`"CPU: {cpu_usage:.2f}%"` and `"Mem: {mem_used:.2f}/{mem_total:.2f} GB ({mem_used_percent:.2f}%)"`. What about the `, ` in between? Which color should it be?
I don't think we can know without the user telling us where to split. Which means that the user should instead give:
```python
format= ["CPU: {cpu_usage:.2f}%", "Mem: {mem_used:.2f}/{mem_total:.2f} GB ({mem_used_percent:.2f}%)"]
```
This really changes the expectation for format. Additionally, the current behaviour is completely different: The *WHOLE* format changes color depending on the *MAX* between cpu and mem.

Unless I'm missing something obvious, we have two choices:
1. We change the expectations for format and use composites. I think this is more elegant but I don't see a way to replicate the "max between mem and cpu" part.
2. We do something like I did and allow for a list of values to check to change the color. This used to be useful because we couldn't color part of the output independently. I think it is obsolete now that we can.

What do you think?

**Comment by tobes** [comment]
> {cpu_usage:.2f}

The default format uses `{cpu_usage}` etc formatting is done by the module __we should not change this__.

The format should be left as it is

What i would do is use py3.build_composite() to do the work

so we do something like

```
composites  = {
    'cpu_usage': {'full_text': <usage>, 'color': <color>},
    ...
}

composite = self.py3.build_composite(self.format, param_dict={...}, composites=composites)

return {
    'composite': composite,
    'caced_until': ...,
}
```

that way all our text is in one color and the placeholders that use thresholds have the colors

**Comment by tobes** [comment]
This is actually quite tricky to get right for the end user

**Comment by guiniol** [comment]
What would the configuration in i3status.conf look like?

Also, I don't agree that the module should do the formatting. Ideally, `cpu_usage` should be the raw value, that way, if someone wants two digits precision, they can have it, but if I want 0 digit precision, I can also have it.

**Comment by tobes** [comment]
>  i3status.conf 

```
order += sysdata
```

all the defaults should remain as they are and more importantly if I have settings in my i3config they must be respected.

> Also, I don't agree that the module should do the formatting. Ideally, cpu_usage should be the raw value, that way, if someone wants two digits precision, they can have it, but if I want 0 digit precision, I can also have it.

but if I am using them now they should still work for me just like they always did  now if you want to add {cpu_usage_full} then that would allow what you want but not ruin it for the user.

**Comment by tobes** [comment]
Add new placeholders separately to doing the composite to keep things simple

**Comment by guiniol** [comment]
I totally agree that the default shouldn't change if possible. However, with the composites, I don't see a way of replicating the color changing based on the max of cpu and mem.
For example, let's say the user wants to display:
```
"CPU: {cpu_usage}%, Mem: {mem_used_percent}%"
```
and have the text change on the max of `cpu_usage` and `mem_used_percent`. How would they specify this?

**Comment by guiniol** [comment]
> Add new placeholders separately to doing the composite to keep things simple

Something like `max_cpu_ram`? But that would only make sense for the colors, and then I have to add one placeholder per combination. If I add swap and load that's 5 values, and 120 combinations.
So, I'm guessing I don't understand what you mean. Could you give me an example?

**Comment by tobes** [comment]
Option 1

Text is not coloured

Option 2

We add some magic to the formatter but that is quite problematic and would need changes to how we do composites. 

So we have something like `[color=cpu CPU: {cpu usage}%]...`

Option 3

Something else

**Comment by guiniol** [comment]
hum, additonal options:
3. we forget about composites. People can use frames to compose what they want. Each module can then have only one color. We can decide on a name for the list of values which are used to compute the color. Each value could have a different threshold, and only the highest threshold of all values applies its color. Or we just use max on the list of values if that's too complex.
4. Use composite. Users have to specify the list of elements in the composite and for each element, they can choose which value is used for the color.


I like your option 2 but that seems to make things more complex on the formatter and composite sides.

**Comment by tobes** [comment]
Your option 3 is already available and is the simplest so that is a plus

option 4 is a bit complicated from the user perspective.

option 2 is not too hard but it would mean that safe_format could create a list rather than a string. We could work around that.  My main concern is that I'd want any format commands eg `[\?color=xxx ...]` to work in all modules.

Anyway we will have some time to decide as this will be for 3.2 which is likely a few months away (3.1 is due for release in the next day or so)
 
Regardless sysdata is in need of some love and has issues eg #401

**Comment by guiniol** [comment]
> option 2 is not too hard but it would mean that safe_format could create a list rather than a string. We could work around that. My main concern is that I'd want any format commands eg `[\?color=xxx ...]` to work in all modules.

Wouldn't that simply mean that every module must use `safe_format`?

I'll take a look at #401 (this weekend probably).

**Comment by tobes** [comment]
> Wouldn't that simply mean that every module must use safe_format?

This is part of the grand plan for 3.2 see #428 

The actually main changes are in module.py as currently response must either have `{'full_text': <string>}` or `{'composite': <list>}`  if we do the `[\?color=... ]` thing then we would get `{'full_text': <list>}`.  The code changes are pretty trivial but the documentation changes etc are quite large and it makes things more complex for the casual module writer.

**Comment by guiniol** [comment]
Ok. Is there an ETA on deciding whether to allow for `{'full_text': <list>}`? Or should I just go with option 3 until it is?

**Comment by tobes** [comment]
> Or should I just go with option 3 until it is?

If you want this now then yes.  I think decisions like `{'full_text': <list>}` might take a while as from my point of view naming conventions and the handling of deprecated config options is the current big priority.

**Comment by guiniol** [comment]
So my current PR #449 would be mostly fine as is? Maybe change the name of `threshold_values`?

**Comment by tobes** [comment]
> Maybe change the name of threshold_values?

I am opposed to the threshold_values thing as it feels a half solution.

Currently the module uses the 'correct' threshold if only cpu or mem is being displayed.  If both are being displayed it uses the most 'critical'  This is far from perfect but is better than nothing.

Really this needs a full solution.

Also that PR also messes up the the format for existing users.

**Comment by guiniol** [comment]
> Also that PR also messes up the the format for existing users.
Yep, on my TODO list.

> Currently the module uses the 'correct' threshold if only cpu or mem is being displayed. If both are being displayed it uses the most 'critical' This is far from perfect but is better than nothing.

`threshold_values` does exactly this but is more generic because you can add `cpu_temp`

**Comment by tobes** [comment]
@guiniol I've had a play at the option 2 color block stuff.  It also fixes an issue with max_length so I think I will try to push for it in 3.2  there is a rough cut at https://github.com/tobes/py3status/tree/formatter-colors if you wanted to have a play.  It needs a cleanup plus documentation.

Having thought some more I've decided that this is a really cool feature.

So the format could look something like
`format = '[\?color=cpu CPU: {cpu_usage}] [\?color=memory RAM: {mem_percent}%]'`

Anyhow this will still be some way off

**Comment by guiniol** [comment]
That's cool.
So,  `format = '[\?color=cpu CPU: {cpu_usage}] [\?color=memory RAM: {mem_percent}%]'` means color `cpu_usage` according to `threshold_cpu_*` and the value of `cpu_usage`. Does that mean `[\?color=cpu` should be `[\?color=cpu_usage`?
I'll try playing with it.

**Comment by tobes** [comment]
the color like `cpu` is either from the module or the config eg would be `self.py3.COLOR_CPU`

```
Py3status:

    method(self):
        self.color_cpu = '#FF00FF'
        return {'full_text'; self.py3.safe_format(self.format)}
```

**Comment by guiniol** [comment]
How do you integrate the thresholds then? `color_cpu_high` and `threshold_cpu_high`?

**Comment by tobes** [comment]
> How do you integrate the thresholds then? 

If it was me I'd just do (pseudo code)

```
if cpu_usage > threshold_high:
   color_cpu = COLOR_BAD
else:
   color_cpu = COLOR_GOOD
```

IMHO separate thresholds (`threshold_cpu_high` rather than `threshold_high` ) for cpu/mem would be a whole new PR and that needs thought again see #451 but basically work in the same way.

Personally I think `color_cpu_high` is unneeded and adds too much crazy

**Comment by guiniol** [comment]
I finally got around to adding formatter-colors support to the (almost) basic sysdata. I only added the option to specify the thermal zone as well as the padding and precision of values. It's in #449. What do you think?

**Pull request closed without merging**
