### PR TITLE
core: add short_text support [wip]

### PR DESCRIPTION
**Pull request by cyrinux**
Hi guys,

I started this branch few months ago, this is an @ultrabug request 😉 
I prefer open the PR before forget the tasks.
I just rebased on master, fix travis complain.

The goal is to support the short text feature which shrink text when no more space is available.

When I done the branch, this was working, but it is very simple implementation.

What we have for the moment (if i remember correctly my work):
* max_size = true , if true will auto shrink if needed to display max info.
* max_size = value will shrink all format to the value size.
* short_format per module, which define a cleaner choosen format if no space avaible.

for eg, wwan module:
```
        response = {
            'cached_until': self.py3.time_in(self.cache_timeout),
            'full_text': self.py3.safe_format(self.format, wwan_data),
            'short_text': self.py3.safe_format(self.short_format, wwan_data)
        }
```
its config:
```
wwan {
...
short_format = '[\?color=state state ]'
...
}
```

Now few questions, need help to progress.
As you see, short_text if defined in the module. 
How to implement this for all module without pass on all? I can batch the edit of all module but is it the best way to do?

To be continued...
If you have advise before i continue (or not?).
edit: sorry I have noise if files changed (search "short" ^^)

### CODE REVIEW

**Comment by tobes** [comment]
@cyrinux 

Yeah this is something that has bugged me for a long time.

This branch is a mess with lots of random commits which makes it hard to review - could you try to clean it up so that only your commits are visible.

If you get stuck I'll try to help out.

**Comment by cyrinux** [comment]
Yes will try to clean this one and continue on it. I will for sure need you help, will ask you ;)

**Comment by cyrinux** [comment]
@tobes branch cleaned ;)

**Comment by tobes** [comment]
thanks I'll try to review it soon

**Comment by cyrinux** [comment]
Ok @tobes will clean this PR to simplify it so and support short_text without magic thing for the moment.

**Comment by lasers** [comment]
Plz resolve teh conflicts. Thx, mate.

**Comment by cyrinux** [comment]
Hey, I have not only conflict but thing to remove in. I dont find time those weeks to work on.

**Comment by cyrinux** [comment]
@lasers can you come on irc?

**Comment by cyrinux** [comment]
green but not working, hands up, will rework on

**Comment by tobes** [comment]
I'd like a simpler implementation that only has `short_format`.

That keeps things much simpler as there is actually quite a lot of complication when you look at the details of possible outputs.  For such a simple feature it is remarkably tricky and that is before we start asking difficult questions about some of our modules.

This is actually one of the many features that I've implemented in the past but never made a PR

**Comment by ultrabug** [comment]
Thanks again @cyrinux but this PR is too big and contains unrelated stuff. I'm gonna close until you or someone else takes on this general short_text support

I liked this PR to the #1584 TODO

Cheers

**Pull request closed without merging**
