### PR TITLE
vnstat: use helpers, add exception, cleanup

### PR DESCRIPTION
**Pull request by lasers**
Uses `self.py3.command_output()`.

I notice that I can't use `self.py3.command_output()` outside of class Py3status. I put the function inside... since it's the only one thing that's calling that function. If it's possible to use `self.py3.command_output()` outside, please let me know... There are few other modules that are like this. Python2and3 tested OK.

Closes https://github.com/ultrabug/py3status/issues/720.

### CODE REVIEW

**Comment by tobes** [comment]
> I notice that I can't use self.py3.command_output() outside of class Py3status.

yes because py3 is 'injected' into Py3status

> I put the function inside... 

Fine, this'll take a while to review though

**Comment by tobes** [comment]
with this module we should deprecate `coloring` and use `thresholds`.

However that would add quite a bit of changes so let's do that later in another PR once this is merged.

**Comment by tobes** [comment]
@lasers can you rebase this then I'll take a look

**Comment by lasers** [comment]
@tobes Yes, sir. I added try/except to fix 572, but can't close. Ty, sir.

**Comment by tobes** [comment]
> I added try/except to fix 572,

This is not relevant to this PR so should not be here :)

**Comment by tobes** [comment]
this is really hard to review as I don't have vnstat and there has been so much churn.  It would have been better to keep the `get_stat()` external so things were readable.

Realistically I'm not going to be reviewing this.

**Comment by lasers** [comment]
```
lasers~/src/py3status/py3status/modules git:(help-vnstat) python2 vnstat.py
{'full_text': u'45.3 mb', 'cached_until': 1486650184.0}
{'full_text': u'45.3 mb', 'cached_until': 1486650185.0}

lasers~/src/py3status/py3status/modules git:(help-vnstat) python3 vnstat.py
{'cached_until': 1486650193.0, 'full_text': '45.3 mb'}
{'cached_until': 1486650194.0, 'full_text': '45.3 mb'}

lasers~/src/py3status/py3status/modules git:(master) python2 vnstat.py
{'full_text': u'45.3 mb', 'cached_until': 1486650198.0}
{'full_text': u'45.3 mb', 'cached_until': 1486650199.0}

lasers~/src/py3status/py3status/modules git:(master) python3 vnstat.py
{'cached_until': 1486650202.0, 'full_text': '45.3 mb'}
{'cached_until': 1486650203.0, 'full_text': '45.3 mb'}
```
If you still want to keep `get_stat()`, please let me know and I'll move it out. After converting to helper, add try/exception, etc. I think sometimes it will look more clean to have one less function.. so instead of returning stat, I assign it to stat (next to up/down).

It's all subjective anyway as I was trying things to optimize it better if I could.

**Comment by tobes** [comment]
It does look better as it is now - maybe I'll reconsider and slog my way through.  But it's one of these things where it is good sometimes to split things into smaller parts/PRs

**Pull request merged**
