### PR TITLE
Module update: Additional display options for pomodoro.py timer

### PR DESCRIPTION
**Pull request by schober-ch**
Added additional display features to pomodoro.py. It is now possible to display the bar and the time as well as choosing a hh:mm:ss format instead of just plain seconds.

### CODE REVIEW

**Comment by ultrabug** [comment]
Hi @schober-ch, thanks for this contribution !

Before merging it, I'd like your point of view about implementing a `format` parameter instead with a selection of all those formats instead ? So would allow for the maximal flexibility of rendering don't you think ?

We could get then get something like : `format = "{bar} {time_mmss}"`

Sounds fun ?

**Comment by schober-ch** [comment]
I think this is a good idea. This would replace the `display_bar` config option, right? 

So we could for example define as possible elements: `{bar} {time_mmss} {time_seconds}` and have `{time_seconds}` as default. This would keep the actual behaviour.

**Comment by ultrabug** [comment]
That's right, basically replace all those "one parameter per feature" by format placeholders !

**Comment by schober-ch** [comment]
Sounds like a plan. I can do these changes and submit another pull request.

**Pull request closed without merging**
