### PR TITLE
Add {mem,swap}_free, {mem,swap}_free_unit, {mem,swap}_free_percent

### PR DESCRIPTION
**Pull request by ricpelo**
Add the following placeholders in `sysdata` module:

- `mem_free`
- `mem_free_unit`
- `mem_free_percent`
- `swap_free`
- `swap_free_unit`
- `swap_free_percent`

### CODE REVIEW

**Comment by ultrabug** [comment]
Hi @ricci thanks for your contribution, please pardon by horrible latency to answer...

I'll check this out this week!

**Comment by ricpelo** [comment]
> Hi @ricci thanks for your contribution, please pardon by horrible latency to answer...
> 
> I'll check this out this week!

Great! Thank you very much. Btw, I'm @ricpelo , not @ricci :laughing: .

**Comment by ultrabug** [comment]
sorry @ricpelo (and sorry ricci)... autocompletion got ricci first ahah!

all good to me, thanks for your first contribution @ricpelo :+1:

**Comment by ricpelo** [comment]
Great, thanks to you!

**Pull request merged**
