### PR TITLE
add new module: mail

### PR DESCRIPTION
**Pull request by lasers**
Hi. I made a new module `mail`. This module ought to count number of mails.

If we want to, we can expand this to support `format_xxxx` loop too... where we can show index, partial subject, partial body message, or even senders in the bar. I know this for sure with non-`imap` mailboxes since I toyed with them right before I added `imap`... eg

> `1 Spotify, Hi from Susie, 2 Dad want to kno, 3 Dentist Appoint` (subject)
> `1 Github, 2 Google, 3 Mom, 4 Steam, 5 Github, 6 Marcus` (sender)
> `1 Hi, What are, 2 Do you want to, 3 I saw you today!` (body message)

I only tested this with `mbox`, but this should work okay with other mailboxes too.

P.S. Merry Christmas. This is my gift to you. 🎁  :-)

~~Closes~~ Targeting https://github.com/ultrabug/py3status/issues/143.
~~Closes~~ Targeting https://github.com/ultrabug/py3status/pull/215.

### CODE REVIEW

**Comment by girst** [comment]
shoehorning idle into this pr seems kind of expensive (it'll need substantial reorganization to get it working asynchronously, and that would likely interfere with the filesystem-mail stuff). 

without wanting to tread on your toes -- I'd go as far as to exclude imap from this pr entirely and "rebrand" it as local_mail.py. that'll simplify things, and would allow us to make local_mail asnyc as well, if you wanted. (tell me if you'd be interested in that)

**Comment by girst** [comment]
>make it work with any mail accounts.

*Your scientists were so preoccupied with whether or not they could, they didn’t stop to think if they should.* :P     
joking aside, i think keeping local stuff and network stuff separated makes things easier, since those two things require different handling (pretty much 90% of work for #1175 was only to make the network stuff more resilient to disconnects on flaky connections). besides, py3status already has multiple modules for package manager updates, media players, weather forecasts and what-not. 

>Last thing. If it's an issue with async, it should be possible to spin up other mail module to be a single standalone imap_idle module this time.

not sure what you mean by that, but the "problem" with async is that it requires you to completely turn your code flow (is that a word?) upside-down: instead of py3status initiating an update, a thread is listening in the background and issuing them _to_ py3status. 

i'm sorry if this sounds dismissive nor negative -- thats not my intention ;)

**Comment by cyrinux** [comment]
Hi,
Could you confirm me that for the moment, imap/mail module must read clear password from config?
If yes, is it planned to be able to pass SSHA password for example?

**Comment by lasers** [comment]
>If yes,

Yes.

> is it planned to be able to pass SSHA password for example?

Nothing is in motion right now. See https://github.com/ultrabug/py3status/issues/1211. 
>__tobes__ Really it'd be nice to have a good solution to private stuff maybe using a keyring or similar. I'll have a think on this.

**Comment by cyrinux** [comment]
Ok cool, keyring should be a good way

**Comment by lasers** [comment]
@ultrabug I assign this module to you for fast review/merge.

Please test this as it does not take much to test this module. And let me know if you want to drop `imap` support and rename module to `local_mail` (@girst's suggestions). I personally like `mail`.

Recently I added few more enhancements too.
* Explicit exceptions in case users forget to specify something instead of vague messags.
    * Old! `mail: {} accounts` (missing, invalid)
    * New! `mail: missing imap {}` (user, password, server)
    * New! `mail: missing {} path: /home/ultrabug/mail_dir` (maildir, mbox, mh, etc)
* Add example for mh, babyl, mmdf too in the `add multiple accounts` example.
* Add `criterion` config for `imap` in case users want a particular count of something
other than `UNSEEN` criterion. (Custom criterion untested, `UNSEEN` criterion tested okay).

My report:
* I tested this module with `imap`, `mbox`, and `maildir`. All okay.
* I assume other mailbox, eg, `mh, babyl`, `mddf`, will work okay.

Thank you.

P.S...
To test `maildir`, you can use this.
```
$ mkdir Example_Maildir/{cur,new,tmp} && touch Example_Maildir/new/msg_{1..4}
```
To test `mbox`, you can Google this and download a `mbox` file.
```
filetype:mbox pipermail
```
To test `imap`, you can figure this out yourself. For `imap`, `mail` will require 3 parameters `user`, `password` and `server` and will accept optional parameters `port` and `criterion`.

Thank you (again).

**Pull request merged**
