### PR TITLE
setup.py, travis.yml: add python 3.7 support

### PR DESCRIPTION
**Pull request by lasers**
This adds Python 3.7 trove classifier.

### CODE REVIEW

**Comment by tobes** [comment]
we should at least test on 3.7 if we claim we support it

**Comment by lasers** [comment]
I have been using `3.7` since.

**Comment by tobes** [comment]
https://github.com/ultrabug/py3status/blob/master/.travis.yml

**Comment by lasers** [comment]
Verbose warnings. https://travis-ci.org/ultrabug/py3status/jobs/426288924

I can add this to `tox.ini` to silence them.
```
[pytest]
addopts = -p no:warnings
```

**Comment by tobes** [comment]
> I can add this to tox.ini to silence them.

I'd rather see them and fix them at some point

**Comment by tobes** [comment]
@lasers 

* you have a conflict here

* If you have a special case __always__ have a comment explaining why it is special

but anyhow,  I'd rather have more uniformity than 3.7 being super special @ultrabug do you have a view on this?

```
matrix:
  include:
    - python: 2.7
    - python: "pypy-5.4.1"
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7   # python 3.7 needs special options
      dist: xenial
      sudo: true
```

**Comment by ultrabug** [comment]
> but anyhow, I'd rather have more uniformity than 3.7 being super special @ultrabug do you have a view on this?

I think we should support it but didn't check out why we need such special treatment here @lasers?

**Comment by lasers** [comment]
I assume it's required to get a newer dist version for Python 3.7 or we get https://travis-ci.org/pycontribs/jira/jobs/398749222. Special treatment is the solution / workaround being shared everywhere.

**Comment by ultrabug** [comment]
Ok, indeed thanks!

**Pull request merged**
