### PR TITLE
sysdata: bugfix for python2 cpu_usage

### PR DESCRIPTION
**Pull request by tobes**
Sysdata module cpu_usage was not working

* python2 broken due to unicode issues.  Fix this by using `Py3.command_output()`

* When a zone was given the output broke.  Fix by running output through the regex.  If the zone is bad we just use the default.  We can change this behaviour but it seems good to me maybe we should return '?'

* When we cannot get a temp we return '?' and allow this to propagate.

@guiniol it would be good if you could review this

### CODE REVIEW

**Comment by guiniol** [comment]
@tobes Sorry for the regression. I never think to test with python2.
This looks good to me. I didn't know about (or had forgotten) `py3.command_output`.

**Comment by tobes** [comment]
> I didn't know about (or had forgotten) py3.command_output.

It's new, I keep adding stuff ;p

**Comment by guiniol** [comment]
> It's new, I keep adding stuff ;p

Keep up the good work ^^

**Comment by ultrabug** [comment]
Thanks :)

**Pull request merged**
