### PR TITLE
fix typo cache_until with cached_until

### PR DESCRIPTION
**Pull request by lasers**
Fixing a typo. This addresses #1576.

EDIT: You can blame this person. a06882dac8602ea17fa2ea0e5f0518491ddc99ba

### CODE REVIEW

**Comment by maximbaz** [comment]
Ha, cool! Please fix other occurrences too 😉 

image

**Comment by tobes** [comment]
cool nice :)

**Comment by maximbaz** [comment]
@lasers instead of "addresses" just use "fixes" or "closes", that way when PR is merged the corresponding issue will be closed automatically 😉

**Comment by lasers** [comment]
See `#1223`. :x::hamster:

**Comment by maximbaz** [comment]
Ah this is the established approach, then sure.

**Comment by tobes** [comment]
@lasers please always make links clickable (preview is your friend)

@maximbaz sometimes we can end up closing issue in error due to misuse of this feature - but yeah if we had better practice we could do this - but also sometimes like here it is good to get the reporter to confirm the fix

Anyhow - nice work team

**Pull request merged**
