### PR TITLE
bitcoin_price: add format

### PR DESCRIPTION
**Pull request by lasers**
I added format ~~Due to json or code, I made this more customizable than before... by replacing hardcoded strings w/ options.~~ correctly.

Default: `btce: 911.30$, btcde: 871.71€`
~~Can customize/omit colon, comma, unavailable, unreachable~~

* ~~format: display format for this module (default '{bitcoin}')~~
* ~~string_separator1: first separator (default ': ')~~
* ~~string_separator2: second separator (default ', ')~~
* ~~string_unavailable: no price (default 'N/A ')~~
* ~~string_unreachable: no connection (default 'Bitcoincharts unreachable')~~
* format: display format for this module (default '{format_price}')
* format_price: display format for prices (default '{market}: {price}{symbol}')

This adds Format placeholders:
* {format_price} format for bitcoin prices

This adds format_price placeholders:
* {market} market names
* {price} bitcoin prices
* {symbol} currency symbols

Ongoing efforts to FORMAT ALL THE THINGS! (meme). #98

### CODE REVIEW

**Comment by tobes** [comment]
With this you need to be much more clever.

basically you have `format_price` which will look like `{market}: {price}{currency_symbol}` or similar and the default `format` will look like `{btceUSD}, {btcdeEUR}`

this is similar to how `clock` does stuff.

The real fun however is in building the correct defaults depending on the user settings that are deprecated.

Have fun or leave it for now but it's a good little challenge.

**Comment by lasers** [comment]
All of this will be hard mainly because bitcoincharts.com does not want people to query more often than once every 15 minutes. ;__;

It is possible that it will come out with same number of available options if I'm being much more clever with this module here. I will slowly give it a shot on different branch.
`string_separator1` --> `format_price`
`string_separator2` --> `format_separator`

**Comment by tobes** [comment]
> Maybe it's better off if the task is left up to you. 

I'm happy with that.

**Comment by lasers** [comment]
Hi. I finished `bitcoin_prices`. I removed `hide_on_error`.  Depreciation to mimic this.
```
If hide_on_error:
    STRING_ERROR = ''
```
With more self.error_strings moving outside of py3status house... becoming adults, the decision is required to figure out how to proceed with allowing people changing `STRING_ERROR`, `STRING_UNAVAILABLE`, etc with custom strings if it can't be options/docstrings.

**Comment by ultrabug** [comment]
Looks good to me, are we clear here?

**Comment by tobes** [comment]
I'd prefer another name than `bitcoin_separator` but can't think of anything better and I can't test this module though @lasers has.

I would really like to fix the format so it is `£100` rather than `100£` but I think we should do that outside of this PR and properly as the symbol location is currency specific.

So yes I'm happy for this to be merged

**Comment by tobes** [comment]
thanks @lasers

**Pull request merged**
