### PR TITLE
taskwarrior: module enhancement

### PR DESCRIPTION
**Pull request by gfeun**
This pull request intends to allow for more customization in the Taskwarrior module
The current implementation is quite limited as it only allows to specify a task filter. All tasks are then displayed which can lead to a lot of text.

For background, my Taskwarrior workflow consist in having different context (home, work ...) consisting of multiple tasks. When a context is set, only tasks passing context definition (A tag +work for example) will be displayed. The tasks are also ranked by urgency which helps me decide what to do next.

I'd want to be able to print my current defined context, the number of remaining tasks and the description of either the most urgent task or the one i am working on (started task).

The target functionalities are as follow, please add your own if you have other ideas :
- [x] Context placeholder
- [x] Number of tasks placeholder
- [ ] Only display the most urgent task
- [ ] Display a configurable number of tasks
- [ ] Display started tasks

I took inspiration from other modules for the coding styles but would gladly take comments !

### CODE REVIEW

**Comment by lasers** [comment]
>- [x] Number of tasks placeholder
>- [ ] Display a configurable number of tasks
>- [ ] Display started tasks

#1107 may already be able to do all three.
>- [x] Context placeholder
>- [ ] Only display the most urgent task

Others could be added. I'm not familiar with `task` tool as well as the `context` feature, but I wonder if `task export` have a filter you can use to only export tasks with that context. That'd be cool to find out.

* What is `nb_` in `{nb_tasks}`?
* When I tried to initialize example contexts, my task didn't complete anything and  I had to `^C` to abort task. I can't test/play with `context` stuffs at this time. Sorry.

@tobes, @ultrabug: Will you want to merge #1107 eventually?

**Comment by gfeun** [comment]
Didn't see your module rewrite ! Should have looked in the pull request ...
nb stands for number (number of tasks). It is usefull to display just the number of tasks remaining. I should make it more explicit.
Since your rewrite is far more advanced I will look at it and could implement contexts if you want.

The syntax for context is explained here https://taskwarrior.org/docs/context.html it is a new feature from v2.4.2.
Context is not exported with tasks, we have to rely on task context command to get it. 

Thanks !

**Comment by lasers** [comment]
@gferon, I recently pushed out: 
>- [x] Context placeholder
>- [ ] Only display the most urgent task

... If you can test them, that'd be great. :-)

**Comment by ultrabug** [comment]
@gfeun do you still have interest / use case for this PR please?

If so, we could merge it as-is to add the two placeholders you're proposing maybe?

**Comment by ultrabug** [comment]
For now I guess not. Feel free to reopen @gfeun ! Thanks again.

**Pull request closed without merging**
