### PR TITLE
weather_yahoo: new module from scratch

### PR DESCRIPTION
**Pull request by lasers**
yahoo-py3status-logo

Hi. I went through `weaher_yahoo` module.
* Docs updated to the standards.
* Codes updated to the standards.
* Configs updated to the standards.
* Placeholders updated to the standards.
* New configs added...
a) `thresholds` for `temp`, `high`, and `low`
b) `retry_timeout` to remove hardcoded `30 secs` retries.
c) `format_datetime` to display time + dates... for today, forecasts, and last updated.
    ```
    format_datetime placeholders:
        key: format_today (date), format_forecast (date), format (item_pubDate)
        value: % strftime characters, eg '%b %d' ----> 'Nov 12'
    ```
* New placeholders added...
    ```
    {atmosphere_humidity}   humidity, eg 96
    {atmosphere_pressure}   pressure, eg 1002.0
    {atmosphere_rising}     rising, eg 0
    {atmosphere_sunrise}    sunrise, eg 6:42 am
    {atmosphere_sunset}     sunset, eg 4:48 pm
    {atmosphere_visibility} visibility, eg 9.4
    {location_city}         location city, eg Chicago
    {location_country}      location country, eg United States
    {location_region}       location region, eg IL
    {units_distance}        unit distance, eg mi
    {units_pressure}        unit pressure, eg in
    {units_speed}           unit speed, eg mph
    {units_temperature}     unit temperature, eg F
    {wind_chill}            wind chill, eg 39
    {wind_direction}        wind direction, eg 20
    {wind_speed}            wind speed, eg 7
    {item_lat}              latitude, eg 41.881832
    {item_long}             longitude, eg -87.623177
    {item_pubDate}          last updated, eg Sun, 12 Nov 2017 10:00 AM CST
    ```
* And probably some more... Feel free to review this module. Thanks. :purple_heart:

### CODE REVIEW

**Comment by lasers** [comment]
Awaiting a review from @ultrabug. Do you like how things looks here? I think it's cool to support `%a` so it can print `Mon, Tue, Wed`, etc in the forecasts. We can change things if we don't like something, you know.

We could remove prefix too... Just one conflict. `units_speed` and `wind_speed`.

**Comment by ultrabug** [comment]
Works as expected and nice additions thanks mate!

My only concern is that you changed the default cache_timeout from 7200 to 3600, please leave it as it was thanks

**Comment by lasers** [comment]
I looked it up. Limited to 2,000 signed calls per day. That's 43.2 seconds ea. I don't see anything about unsigned calls. `cache_timeout` reverted.

**Comment by ultrabug** [comment]
Thanks a lot mate

**Pull request merged**
