### PR TITLE
WIP improve get_color_names_list()

### PR DESCRIPTION
**Pull request by tobes**
For @lasers `get_color_names_list()` see #1469

for me the issues are is this just for thresholds?

should we fix the case - all lower/UPPER and should we force the casing further through the code so that we are less error prone?

### CODE REVIEW

**Comment by lasers** [comment]
This function is about getting color placeholders that will have same names as placeholders.
```python
# loadavg.py
        for x in self.thresholds_init:
            if x in self.load_data:
                self.py3.threshold_get_color(self.load_data[x], x)
```

In the future, all color threshold names should have same name as placeholders so we don't have to figure out what `cpu` color prints... vs `cpu_used_percent` or `cpu_free_percent`.

Same for `mem` and other threshold names that is not same as the placeholders names.
```python
# sysdata.py -- current
    cache_timeout = 10
    format = "[\?color=cpu CPU: {cpu_used_percent}%], " \
             "[\?color=mem Mem: {mem_used}/{mem_total} {mem_unit} ({mem_used_percent}%)]"
```
```python
# sysdata.py -- future
    cache_timeout = 10
    format = ("[\?color=cpu_used_percent CPU: {cpu_used_percent}%], "
              "[\?color=mem_used_percent Mem: {mem_used}/{mem_total} "
              "{mem_unit} ({mem_used_percent}%)]"
```

I don't think we need to get `#HEX` or `NAMES` beause the formatter will take care of them.

**Comment by tobes** [comment]
can they all be lower case?

The user could still user upper case (we'd just convert it for them - but I'd throw errors for modules doing it wrong)

**Comment by lasers** [comment]
Probably not because I think the color names simply should be consistent with placeholders.

For most modules, we won't have this issue because we enforces lowercase placeholders which will end up enforcing the same lowercase color names too. There are and will be edge cases that requires treating placeholders as-is (periods included)... so it can be passed out to a command as-is too.

If somebody made a module with case-sensitive placeholders for their module, then I think they sohuld have to use same case-sensitive color threshold names too.

Module `sql` is an example of case-sensitive placeholders. I first thought it'd be good to lower them and did that... but later, I realize it might be better for users to specify keys and color names as-is.

**Comment by tobes** [comment]
from #1469

>    self.py3.get_color_placeholders_list might be more accurate... similar to 

colours are not placeholders 

> self.py3.get_control_placeholders_list. Maybe it's a little too long too.

I'd rather keep colours and placeholders/params separate - it is easy enough to combine the list if a module needs

but maybe we can get a better name

>    self.py3.get_placeholders_list(self.format, color_names_only=True) might be more accurate too.

as above I think this is too complicated

> self.py3.get_color_names_list optionally can have an argument to add hex codes, css color names, special color names, etc to the set too. I just have no use for those.

this code has this functionality but it is not made available to users - internally it may be useful

> requires treating placeholders as-is (periods included)..

This I want to kill because it removes functionality from the formatter that would be great to have available - but that is a fight for another day

So for here the issues are

a) function name exposed in `py3`

b) case for threshold colours - I think we should force lower case internally so these are case insensitive for the user - case-sensitive for module writers

**Comment by lasers** [comment]
Can we close this and #1469? This PR is trying too hard... and many things are not necessary.

**Pull request closed without merging**
