### PR TITLE
imap: allow_urgent on unread messages

### PR DESCRIPTION
**Pull request by lasers**
_Don't ignore your mailbox._

### CODE REVIEW

**Comment by tobes** [comment]
@ultrabug this PR adds urgent support to `imap` module.  This means for example that if it is in a group it will get shown.

There is an option to set the behaviour but the default is `True` so users will get the urgent.  Is that ok?  To me it feels like an improvement rather than a change.

Let me know if you're happy and I'll merge it if you haven't

**Comment by ultrabug** [comment]
Well that raises the question of the behaviour consistency between modules.

For example, having notifications on the github module does not pass it as 'urgent' and if I follow your logic here it should.

I'm not a big fan of urgent abuse tbh, let the user choose but don't default this to him.

**Comment by lasers** [comment]
`github` and `imap` may be the only modules that alerts the users about unread messages.

If you receive messages somewhere, it might be good idea to make them urgent by default.

`github` uses urgent feature by default, but misses an toggle option. Different PR adds it.
`imap` is missing urgency feature. This makes it default along w/ toggle option.

If you put `imap` in frame (fixme) or group, they would have to turn urgent on by default so the group could display urgent `imap` or `github` right away. Making it default is nice because it mean slightly less configuration... when used with other modules.

The `color_good`,`color_bad` is nice, but not important as messages... And we shouldn't change urgent by default behavior for those non-messages modules anyway, only for message modules.

**Comment by tobes** [comment]
With the urgent thing my thoughts are

* imap if shows urgent by default or not, I don't mind either but @ultrabug wants defaulted off.

* I would like this as a universal option that other modules could use the `allow_urgent` config option would be used.

The options as I see it are.

* Allow modules to access the `allow_urgent` param and use the value.  We would need to allow them to access it (this could be done in several ways).

* Just do it all in module.py (strip urgent from any responses if not `allow_urgent`)  The module would just set it without caring and we would police it.

I sort of prefer the second option we might have to do some magic to allow modules to set their own default but quite doable.

**Comment by lasers** [comment]
>Just do it all in module.py (strip urgent from any responses if not allow_urgent) The module would just set it without caring and we would police it.

This is for individual config sections and for `py3status` section too?

If yes, I like this too... Same as `color = #` and if any other modules are missing, we have to add missing urgents? ...Same as this `imap`, but no `+4 lines` codes in each modules.

Currently, we have few urgent in `github`, `scratchpad_async`, `pomodoro`... and maybe `imap`, but good idea to set it up universal/per-module `allow_urgent` option if it's not too much of a magic.

**Comment by ultrabug** [comment]
There's a frozen state here and the decision we're waiting for is not clear to me tbh

@lasers is doing an amazing work and I really think we should focus on finishing the overall merge of modules cleanup and nomalization before adding stuff etc at the py3status level

Do you guys think we could advance on that ?

If so, @lasers please pass the allow_urgent to False by default and create an issue so we can deal with this kind of consideration later

**Comment by lasers** [comment]
allow_urgent now False.

**Pull request merged**
