### PR TITLE
gpmdp: use helpers

### PR DESCRIPTION
**Pull request by lasers**
Uses `self.py3.format_contains()`
Uses `self.py3.command_output()`

### CODE REVIEW

**Comment by tobes** [comment]
nice,

looking at https://github.com/iandrewt/gpmdp-remote/blob/master/gpmdp-remote

we could probably remove gpmdp-remote as a dependency.  Note that the license for that project is unclear and so copying the code would not be appropriate but it seems that `~/.config/Google Play Music Desktop Player/json_store/playback.json` has all the data we need.  You'd probably want to have the app to test the changes though.

Anyhow I'm happy with this PR if you want to stop here.

**Comment by lasers** [comment]
Yes. Please. Ready to go in. Somebody else who know how to carve json pieces with python quite well can take it from here... to depreciate this small dependency.

**Comment by tobes** [comment]
I can't test this.  Can you confirm it runs under python2/3 it looks good though.

Also could you remove the `{help}` placeholder as it isn't actually available.

**Comment by lasers** [comment]
`{help}` removed... Python3 and python2 confirmed OK.

**Comment by lasers** [comment]
@tobes If you want to... for your next PR.

>we could probably remove gpmdp-remote as a dependency.

You.

>I can't test this.

Me.

Here's what `playback.json` looks like.
```
lasers~ cat .config/Google\ Play\ Music\ Desktop\ Player/json_store/playback.json
{
    "playing": false,
    "song": {
        "title": null,
        "artist": null,
        "album": null,
        "albumArt": null
    },
    "rating": {
        "liked": false,
        "disliked": false
    },
    "time": {
        "current": 0,
        "total": 0
    },
    "songLyrics": null,
    "shuffle": "NO_SHUFFLE",
    "repeat": "NO_REPEAT",
    "volume": 50
}
```
```
{
    "playing": true,
    "song": {
        "title": "Coming Up (feat. MDMA)",
        "artist": "Lupe Fiasco",
        "album": "Lasers",
        "albumArt": "https://lh3.googleusercontent.com/0XD48RSFqkxZdmbtgLGCNbOIi6vZ95c8YrnJnGKGDwvpKTcAXiUauDkZE-EywInxFR7KwG6ncQ"
    },
    "rating": {
        "liked": false,
        "disliked": false
    },
    "time": {
        "current": 7819,
        "total": 238000
    },
    "songLyrics": "If you're feeling good let me hear you say \"Alright, alright!\"\nWhat up?  Alright!\nPooh Bear!  I'm feeling good so I'mma say it myself, alright, alright\nClaudia, alright, gonna do this\n\nThis one goes out to the baby girls\nIn a rush growing up in this crazy world\nYeah your brother on the row, he ain't ever home\nI know you're feeling kinda sad now that daddy gone\nYou can't let it get you down, gotta carry on\nWe only lose things because it make us strong\nYou always have my love, and now you got a song\nFrom the biggest biggest fan that you've ever known\nI know you want me little girls, not for very long\nAnd you ain't gotta have a man if you ain't ever want\n'Cause I'mma make sure you got two of everything\nThat you ever want, every tone make your very own\nNot to make you hard to respect\nJust really, really, really, really hard to impress\nThere's a whole wide world for you to get your hands on\nUntil then, just come and get your dance on now\n\nI see you coming up\nI'mma give you the low down, down, down\nYou ain't never gotta worry about nothing\nJust as long as I'm around, round, round, round\n\nThis for everybody feeling good\nYou know who you are, or you misunderstood\nNever had money, or you living good\nIf you from the burbs, if you in the hood\nRecognise where we come from\nIn my day man I did a little something something\nThey like \"how come you don't rap that?\"\n'Cause that's a back track and I ain't trying to back back\nI'm only moving forward, homie, that's that\nDirection, a lot of shoulders lack that\nI'm just trying to give it to 'em like sat nav\nNow I know a money maker like a fat rat\nThat's cool, as long as he don't trap crack\nGraduate from school and still let his pants sag\nNever catch a case, know how to let his cash stack\nWelcome to the map of dough, any way trap that now\n\nI see you coming up\nI'mma give you the low down, down, down\nYou ain't never gotta worry about nothing\nJust as long as I'm around, round, round, round\n\nPooh Bear!\n\nAnd if the roof falls down, I'mma be there to carry you\nAnd if you want that star, I'll go get it out the sky for you\nIf you gotta shed a tear, I'mma dry your eyes\nJust to let you know it'll be alright\n\nI know there's like a whole lot going on\nThings going right, things going wrong\nMaybe baby on the way, in you for so long\nKnow that in this world you're never really on your own\nGod got a number, get Him on the phone\nHe'll never put you in places where you don't belong\nPut you through the pain to put you on the throne\nAnd I know that from the bottom of my corazon\nAnd if they looking at you sideways\nYou just wave right back and tell them \"Hi\", \"hey\"\nMan you ain't hanging with 'em in the driveway\nNaw, we gonna keep 'em moving to the highway\nStrong as puttin on\nWicked all over like Friday Chilli\nShout to King David for bringing them to Philly\nAnd I'mma put an independent rhythm in the building, let's go\n\nI see you coming up\nI'mma give you the low down, down, down (all the way down)\nYou ain't never gotta worry about nothing\nJust as long as I'm around, round, round, round\n\nI see you coming up\nI'mma give you the low down, down, down (all the way down)\nYou ain't never gotta worry about nothing\nJust as long as I'm around, round, round, round",
    "shuffle": "NO_SHUFFLE",
    "repeat": "NO_REPEAT",
    "volume": 100
}%
```

P.S. I added helpers for `nvidia_temp` already.

**Pull request merged**
