### PR TITLE
Bugfix group widths when items not ready.

### PR DESCRIPTION
**Pull request by tobes**
@ultrabug fix for the click issue.

basically if the items weren't initialized we crashed :(

### CODE REVIEW

**Comment by tobes** [comment]
I wasn't seeing the error as my group had a clock in it so it refreshed after a second which fixed the issue.  Anyhow I think it'll be all good now.

**Comment by ultrabug** [comment]
Thanks for your quick reply @tobes but it doesn't seem to fix the problem.

log : `on_click failed with ('NoneType' object has no attribute 'click_event') for event ({u'y': 14, u'instance': u'disks', u'button': 1, u'name': u'group', u'x': 5233})`

config : 
```
order += "group disks"

group disks {
	fixed_width = False
	format = "{output}"

	disk "/home" {
		format = "~ %free"
		on_click 1 = "exec thunar ~"
	}

	disk "/" {
		format = "/ %free"
		on_click 1 = "exec thunar /"
	}
}
```

**Comment by tobes** [comment]
I see.  The module.on_click() is covered but not the config based ones.  I should be able to fix this shortly.

**Comment by tobes** [comment]
Ok, this should fix the issue for click events defined in the config.

I am assuming that if an on_click is defined in the config that it over-rules the on_click() of the module

**Comment by ultrabug** [comment]
> I am assuming that if an on_click is defined in the config that it over-rules the on_click() of the module

stupid question: can't they be executed both ? (meta meta meta) ;)

**Comment by ultrabug** [comment]
I can confirm this fixes the click issue, :+1:

**Comment by tobes** [comment]
> stupid question: can't they be executed both ? (meta meta meta) ;)

they can and they now do - why is another question but it's doable.

I also found another issue around initially displaying slow updating py3status modules.  The fix for that is here too.

**Comment by ultrabug** [comment]
Cool thanks, the why is just that it would seem consistent and possibly a cool feature :)

Almost there !
`on_click failed with ('NoneType' object has no attribute 'click_event') for event ({u'y': 7, u'instance': u'disks', u'button': 1, u'name': u'group', u'x': 5195})`

```
group disks {
	fixed_width = False
	format = "{output}"

	on_click 1 = "exec thunar /tmp"

	disk "/home" {
		format = "~ %free"
		on_click 1 = "exec thunar ~"
	}

	disk "/" {
		format = "/ %free"
		on_click 1 = "exec thunar /"
	}
}
```

**Comment by tobes** [comment]
This is now done. It would be nice to unpick the events a bit at some point but this now works as you have commanded

**Comment by ultrabug** [comment]
Oh I don't command anything mate, I was merely asking thank you !

**Pull request merged**
