### PR TITLE
add new module: xrandr_tweaks

### PR DESCRIPTION
**Pull request by lasers**
2017-12-30__xrandr_lmao

Hi. I made a new module `xrandr_lmao`. I don't know what to name this one... lmao. This module is basically a  `xrandr_rotate` module on steroids as it can do more than `rotate`. We support the following tricks:
* `brightness` <-- to dim or not to dim.
* `delta` <-- not part of xrandr, it's an adjustable delta value via scrolling.
* `gamma_red` <-- nice redshift alternative.
* `gamma_green` <-- nice greenshift alternative if we had one.
* `gamma_blue` <-- nice blueshift alternative if we had one.
* `reflect` <-- flip it all over the place.
* `rotate` <-- rotate it all over the place -- also, a `xrandr_rotate` alternative
* `scale` <-- make things smaller or bigger

This module, I feel, is not perfect as there are some things that could still be worked on... and to work on some things I think may be poorly implemented... and to improve/optimize `xrandr_lmao`  more all over the place...such as do we want to add supporting setting an option for `rotate` so it can only rotate `normal, left` versus full options? However, I'm not sure if that's worth implementing as it's only four values... and that the users will not always use this option too (if implemented). I think everybody will find this more of a fun toy  so I added a `random` button for fun too... :fire_engine: :fire:

Quick manual: 
* Right-click on the value to reset a value.
* Right-click on the name to reset all values.
* Middle-click on the value to randomize a value.
* Middle-click on the name to randomize all values.
* Scroll on the value to increase/decrease the value.

Ty for reading.

### CODE REVIEW

**Comment by tobes** [comment]
> Middle-click on the name to randomize all values.

This I like :+1:

**Comment by ultrabug** [comment]
two questions

1. can we have rounded values (let's say 2 digits max) instead of those nasty ones killing bar space ?
2. looks like right click on the name reset works well while on the value works but not when scrolling just after reseting

**Comment by lasers** [comment]
1) I could hardcode them. I'm not sure how to do that with `composite` stuffs. That's one of the question to ask you or @tobes about.
2) I'll look at this module again. Which placeholder?
* * We have different outputs... so maybe what works for me does not work for you.

Your `xrandr` is broken for me... for long time.

**Comment by ultrabug** [comment]
> Which placeholder?

default brightness one

>  could hardcode them

:.2f is fine enough at display

> Your xrandr is broken for me... for long time.

oh yeah ? works well for everyone around me

**Comment by lasers** [comment]
Can you expand 2) more? I can't reproduce this. Maybe you scrolled in dead area (separator) just right after resetting? I don't know. I will put out short `:.2f` solution.

**Comment by lasers** [comment]
I'm thinking about defaulting this for users... More fun for users out of the box.
* `format_output = '{name} {brightness} {gamma_red} {gamma_green} {gamma_blue}'`

If users like it, they might just use the old default `format` instead.
* `format_output = '{name} {brightness}`

**Comment by lasers** [comment]
Hi @ultrabug, I made multiple changes in this module.
* Improve readability in `post_config_hook` and `on_click`
* Cleaned up the examples. Added some more too.
* Added new config `outputs` to allow users to filter a list of active `outputs`.
* `rotate` to rotate clockwise of documentation `normal, inverted, left, right`.
* Hardcoded `.2f` to preserve bar space. :-) 
* Plenty of comments everywhere. This will help tremulously.
* Consolidate scrolling, randomizing, and resetting functions for `float` + `list` values.

>**ultrabug** looks like right click on the name reset works well while on the value works but not when scrolling just after reseting

I can't reproduce this. I guess I need more information. This is ready for a review. I don't think users would like this very much if I were to add a `formats` dict too to permit adjusting of `.2f`, `colors`, strings, etc so they should suck up with hardcoded settings. :-)  Anyhow, have a good day.

**Comment by lasers** [comment]
Users can change `colors`, `.2f`, etc via `format_output_options` dict and users can also specify rotation, reflection too to only rotate `normal`, `left` instead of all values. This also comes with `ignore` and `skip` option (not sure on names).
* `ignore` --> Don't reset/randomize values.
* `skip` --> Don't update live. Requires users to click. Behave similar to `xrandr`, `xrandr_rotate`.

**Comment by ultrabug** [comment]
I didn't check it out mate, but I really want us to be able to have one xrandr module

I think your lmao one is a good start and that we could find a way to change the operating mode to switch from brightness to extension of screens or cloning etc

**Comment by ultrabug** [comment]
something like `DP1 [+|=|☀] eDP1`

where the middle container allows you to switch mode from + extension, = clone, ☀ brightness? see what I mean?

**Comment by lasers** [comment]
I don't know if it is possible to consolidate this with `xrandr` because it does not refresh, only on scrolling (very effective ; and to avoid #580). I also used up buttons (`up`, `down`, `run`, `reset`, `random`)... and could have an issue of scrolling on names to change output layouts instead of output options. Maybe we can... with more time.

I think it may be more possible to depreciate `xrandr_rotate` via using ~~`xrandr_lmao`~~ `xrandr_controls` and user-defined config...
* To use `normal`, `left`, instead of all values. (now possible)
* To display `H`, `V` instead of `normal`, `left`. (now possible)
* To skip live updates. (now possible)

`xrandr_rotate` uses `--output {output} --rotate {rotation}`. This uses much more than that.. so it will be  just different and behave differently too for users.

I think your example `DP1 [+|=|☀] eDP1` would change `brightness` for all outputs. This changes per-output brightness (and is currently not possible to change `brightness` for all outputs... Maybe with more time).

**Comment by lasers** [comment]
Closest thing to `xrandr_rotate`. I am not confident with this module as the config parser (atm) is meh when it comes to lists (using list itself as a value versus using list for all outputs).
```python
xrandr_controls {
    format_output = '{name} {rotate}'
    output_options = {
        'rotate': ['normal', 'left'],   # default output
        'rotation': ['normal', 'left'], # rotate only normal, left
        'skip': ['rotate'],               # do not update
    }
    format_output_option_rotate = '\?color=lime '
    format_output_option_rotate += '[\?if=value=normal&show N]'
    format_output_option_rotate += '[\?if=value=left&show L]'
}
```
See `rotate` in `output_options` to change the default layout.

**Comment by ultrabug** [comment]
I'm gonna use it for a while, I think it is very powerful

Two remarks

- how do you refresh this module?
- I think `format_output = '{name} {brightness}'` would be a more sane default

About my example, I think it's doable to keep the current per output control and add a middle special container to handle cloning / extending / left / right

**Comment by lasers** [comment]
* No click events, no refresh.
* That was the old `format`. I think having this `format` would lead to more user adaptions via  using/playing with the module versus the suggested format. I do love your suggested format (and have it in `start with few possibilities` example. Like you said, it's very powerful... so it's more fun to have all four placeholders out of the box versus one.

**Comment by lasers** [comment]
Thoughts on the name `xrandr_controls`? I'm eh-eh on this as I just tried `xrandr_control` (similar to `player_control`). I think picking a different name like `xrandr_tweaks` could be more favorable.
* xrandr_tweaks
* xrandr_cogs
* xrandr `# lol fuck`
* xrandr_cli  `# eh not loving this one`
* xrandr_lmao  `# ;-)`

Maybe `xrandr_tweaks` if we don't have a better name in mind. Got any name suggestions?

**Comment by lasers** [comment]
@ultrabug So far, I added three mutually exclusive: `--auto`, `--preferred` and `--off`.

`--off` will not work well without `pos`, `right-of`, `left-of`, `above`, `below`, `same-as`, etc... so they ought to be added too. Meantime, you can try toggling `on/off` for fun. That's all folks. Thx. 
```
xrandr_tweaks {
    format_output = '\?show {name}: {rotate} {off}'
    per_option_output_skip_update = ['rotate', 'off']
}
```

**Comment by lasers** [comment]
@ultrabug I'm thinking about removing several commits and have this merge this as-is.

I hadn't worked anything new in this and its purpose already exceeds user's expectations.

The code is realized later to be not ideal when we keep adding more and more things to `xrandr_tweaks`. Since it is using `CACHE_FOREVER`, it's not going to be a problem.

Remove commits.
* `add noprimary option`
* `add mode option`
* `add pos option`
* `add rate option`
* `add current option`
* `add display, screen, nograb options`
* `quick sed on the docs, examples untested`
* `add dpi option`
* `add crtc option`
* `update docs`
* `add (custom) debug option`
* `remove empty default placeholders`
* `add preferred option (because we could)`
* `add off option (messy)`

**Comment by ultrabug** [comment]
I want to merge xrandr and this one in the future. I don't want another module so I'd like to close this PR and when the time is right we'll get inspiration from this.

**Pull request closed without merging**
