### PR TITLE
backlight module: rounding float output (for use with the light package)

### PR DESCRIPTION
**Pull request by nwg-piotr**
As we agreed in #1802

### CODE REVIEW

**Comment by lasers** [comment]
Erm. I was trying to push `backlight module: black formatting` commit on top of this.

**Comment by nwg-piotr** [comment]
Does it mean I should make another PR?

**Comment by lasers** [comment]
Yes please. Get your contribution in there. :-)

**Comment by lasers** [comment]
I think if you push it to `master`, you can "Reopen and comment"

**Comment by nwg-piotr** [comment]
I don't see a button to reopen. :)

**Comment by lasers** [comment]
https://github.com/nwg-piotr/py3status (master) shows this.

>Pull request Compare This branch is even with ultrabug:master.

**Comment by lasers** [comment]
You need to fix code formatting. Two choices.
1) Install `black` and run `black backlight.py` 
2) Apply this diff.
```diff
diff --git a/py3status/modules/backlight.py b/py3status/modules/backlight.py
index e602ff1..6d33998 100644
--- a/py3status/modules/backlight.py
+++ b/py3status/modules/backlight.py
@@ -109,8 +109,9 @@ class Py3status:
             else:
                 raise Exception(STRING_NOT_AVAILABLE)
 
-
-        self.format = self.py3.update_placeholder_formats(self.format, {"level": ":.0f"})
+        self.format = self.py3.update_placeholder_formats(
+            self.format, {"level": ":.0f"}
+        )
         # check for an error code and an output
         self.command_available = False
         try:

```

**Comment by nwg-piotr** [comment]
Does it look better now?

**Comment by lasers** [comment]
Definitely. Thank you for fixing this. :+1:

**Comment by nwg-piotr** [comment]
Thanks for fixing my Sway and some lessons in git. :)

**Pull request merged**
