### PR TITLE
sql: add new module, add support for multiple rows

### PR DESCRIPTION
**Pull request by lasers**
Hi. This is a new module made by **@Cereal2nd** in #1303. I added support for multiple rows.

### CODE REVIEW

**Comment by ultrabug** [comment]
First of all, thanks for your amazing work @Cereal2nd 

@lasers my problem with this PR is that it should come from @Cereal2nd so he gets both authorship and contribution tributes

Maybe you close #1303 and open a fresh PR like this one @Cereal2nd ?

**Comment by lasers** [comment]
@ultrabug I squashed his commits here. Fine with me. Please merge his work and I'll fix up this PR.

I also wonder if we should rename `query` to `queries` and have it support a list of `queries`... but this is not something I use myself... so I need this question answered... Do some database allow multiple executions like that?

**Comment by Cereal2nd** [comment]
For me personally it doesn't matter to me.
i just needed this functionality and that's why i started coding :)

multiple queries can result in different columns (keys) for the thresholds,
so not sure how it will work

**Comment by Cereal2nd** [comment]
can we please get this one merged?
it would be really handy if we could use this in the released version

**Comment by lasers** [comment]
@Cereal2nd Hello. I just made this work with python2... and threshold gold efficiency because database (like yours) could contain more than 50+ placeholders  and if we want to colorize something, we will colorize only the ones specified in the `format`, `format_row` instead of all placeholders.

Please test this quickly on your side (it looks good on mine), then we'll pester @ultrabug one more time.  Thx.

**Pull request merged**
