### PR TITLE
sysdata module: try to use default intel/amd sensors first

### PR DESCRIPTION
**Pull request by Compunctus**
also changed regex to support modern desktop intel/amd cpus

This should also make `zone` somewhat obsolete.

### CODE REVIEW

**Comment by ultrabug** [comment]
Thanks for your proposal @Compunctus !

@ricpelo would you be interested in trying out this proposal?

Since I'm no sysdata user, it's hard for me to detect how this would affect other users of the module so your input would be appreciated!

**Comment by lasers** [comment]
@ultrabug (Imo) It shouldn't change anything. This finds the CPU sensor, then get the much smaller output from `sensors coretemp-isa-0000` instead of `sensors`, then regex it to get the value.

(Suggestion) Do it once in `post_config_hook` instead and we could skip json too. https://github.com/lasers/py3status/commit/1c8d641b5b47a896237e48f9c2c041eaebcf4315

**Comment by ultrabug** [comment]
@Compunctus would you care to move the logic to `post_config_hook` as @lasers suggested please?

**Comment by Compunctus** [comment]
@ultrabug I moved the logic to post_config_hook, also removed json usage (as per lasers commit).

**Comment by ultrabug** [comment]
Thanks a lot @Compunctus !

**Pull request merged**
