### PR TITLE
docs: add profiling section

### PR DESCRIPTION
**Pull request by lasers**
Closes https://github.com/ultrabug/py3status/issues/1038.

### CODE REVIEW

**Comment by ultrabug** [comment]
docs PRs are precious, thanks!

**Comment by tobes** [comment]
> Closes #1038.

@lasers, please don't add this to your PRs as github uses as a trigger and it is not always the correct behaviour

**Comment by lasers** [comment]
@tobes Okay. Will do. You want to close them manually?

**Comment by tobes** [comment]
> You want to close them manually?

I'd rather that than accidentally close one

**Pull request merged**
