### PR TITLE
[external_script] don't show external_script if zero output present

### PR DESCRIPTION
**Pull request by sodd**
Don't show external_script if there is no content to show

### CODE REVIEW

**Comment by lasers** [comment]
Does this work?
```
external_script {
    format = '[Output: {output}]'
}
```

**Comment by tobes** [comment]
What is the problem you are trying to solve here?

The module should do this by default.

**Comment by lasers** [comment]
Actually, you might want this one instead.
```
external_script {
    format = '[\?not_zero Output: {output}]'
}
```

**Comment by sodd** [comment]
@tobes actually it doesn't work for me :( if I run program which return empty string ill get red text "external_script name" and thats annoying 
@lasers my apology but didn't know there is any statement logic witch a can use

**Comment by lasers** [comment]
What command? What output? Looks like it gave back error code to `external_script`.

**Comment by sodd** [comment]
forexample: ```external_script test {
    script_path = "exit"
}```
have resoult ``` external_script test: list index out of range```

I dont know what you mean `gave back error code to external_script`? If i run `exit 1` and `exit 0` in script_path it will be different output?

**Comment by lasers** [comment]
Are you really using `exit` in `script_path`? I guess your command or script does not give back anything and that's the issue you were trying to solve... What command/script is this?

Run your `command/script` in the terminal followed with `echo $?` -- It'll give you an error code. If it's `0`, no error. If it's `1` or any other number, you got error codes. We might need to find out if you're receiving an error code from your `command/script` or from `IndexError: list index out of range`.

We could fix `IndexError` with this.
```
 diff --git a/py3status/modules/external_script.py b/py3status/modules/external_script.py                          
 index 2f6faf40..cbdbde41 100644
 --- a/py3status/modules/external_script.py
 +++ b/py3status/modules/external_script.py
 @@ -74,8 +74,10 @@ class Py3status:
              output = e.output or e.error
              output_lines = output.splitlines()
              response['color'] = self.py3.COLOR_BAD
 -
 -        output_text = output_lines[0]
 +        try:
 +            output_text = output_lines[0]
 +        except IndexError:
 +            output_text = ''
  
          if self.strip_output:
              output_text = output_text.strip()
```

**Comment by sodd** [comment]
ok,  what i'm trying to achieve is if i run my script and this script will return me error or zero output length, then i don't want to show this module at all.

**Comment by lasers** [comment]
Did you try the `format = '[\?not_zero Output: {output}]'` example? When you get error `external_script`, does it say `external_script test: list index out of range` with your script or something else?

**Comment by sodd** [comment]
```Did you try the format = '[\?not_zero Output: {output}]' example? ```
when i started this PR i didn't know there is any statement logic behind this (is here any documentation for this?)

```When you get error external_script, does it say external_script test: list index out of range with your script or something else?```
No i'm using `exit` as a build-in bash function for exit the whole process. I'm using it only for testing the behavior of the external_script module 
And your code had non effect to output string :( output string is "list index out of range"

BTW: thx for your patience with me :]

**Comment by lasers** [comment]
>(is here any documentation for this?)

Meh. We need to write them first. Formatter stuffs are kinda new / early in its stage, I think.

>And your code had non effect to output string :( output string is "list index out of range"

Not sure why you're getting `list index out of range` still.

The code... and the `format` example. Both works together should give you what you want, I think... Not sure why you're getting that error tho. Different line? Maybe you can log? 
```
# in i3 config
bar {
    status_command py3status (your stuffs here) -l /tmp/py3status-top.log
}
```
I think this is better as we don't have to try/except. 
```
diff --git a/py3status/modules/external_script.py b/py3status/modules/external_script.py
index 2f6faf40..d892117a 100644
--- a/py3status/modules/external_script.py
+++ b/py3status/modules/external_script.py
@@ -63,6 +63,7 @@ class Py3status:
 
         response = {}
         response['cached_until'] = self.py3.time_in(self.cache_timeout)
+        output_text = None
         try:
             output = self.py3.command_output(self.script_path, shell=True)
             output_lines = output.splitlines()
@@ -75,10 +76,10 @@ class Py3status:
             output_lines = output.splitlines()
             response['color'] = self.py3.COLOR_BAD
 
-        output_text = output_lines[0]
-
-        if self.strip_output:
-            output_text = output_text.strip()
+        if output_lines:
+            output_text = output_lines[0]
+            if self.strip_output:
+                output_text = output_text.strip()
 
         response['full_text'] = self.py3.safe_format(self.format, {'output': output_text})
         return response
```

**Comment by tobes** [comment]
I prefer this

```diff
diff --git a/py3status/modules/external_script.py b/py3status/modules/external_script.py
index 2f6faf40..e5f0a214 100644
--- a/py3status/modules/external_script.py
+++ b/py3status/modules/external_script.py
@@ -75,7 +75,10 @@ class Py3status:
             output_lines = output.splitlines()
             response['color'] = self.py3.COLOR_BAD
 
-        output_text = output_lines[0]
+        if output_lines:
+            output_text = output_lines[0]
+        else:
+            output_text = ''
 
         if self.strip_output:
             output_text = output_text.strip()
```

**Comment by tobes** [comment]
closed via  #1243 @sodd thanks for reporting this issue, sorry it has taken so long to resolve

**Pull request closed without merging**
