### PR TITLE
Customiziable pomodoro strings

### PR DESCRIPTION
**Pull request by ricci**
Make the status bar strings for the pomodoro module more customizable

### CODE REVIEW

**Comment by ultrabug** [comment]
Thanks a lot @ricci it's clean & simple !

**Comment by lasers** [comment]
I think this should be reverted (imho). I have a branch that deals with this correctly. Some of the new `format` does not go through the `safe_format` too. It would be hard to deprecate all those new `format_*` now.

**Comment by ultrabug** [comment]
Well @ricci did some good work, if you want to enhance it feel free to do so before 3.8 but start from his contribution please

**Comment by lasers** [comment]
A comment to make a reference. #98 Many thanks for your contribution! @ricci :-)

**Comment by ricci** [comment]
Thanks, and I look forward to @lasers improvements!

**Comment by lasers** [comment]
@ricci You don't have to wait... I added new `Long Break` string too. :-) https://github.com/lasers/py3status/tree/mergeformat-pomodoro-one-pr). There might be some things I need to add back in... though... as it was long time ago when we had annoying exception bars.

**Pull request merged**
