### PR TITLE
exchange_rates: use new feed

### PR DESCRIPTION
**Pull request by tobes**
New feed as Yahoo api no longer available see #1174

Also makes `update_placeholder_formats()` available to modules

precission has been lowered due to the data being old and so less accurate so this seems appropriate

### CODE REVIEW

**Comment by ultrabug** [comment]
Please update the py3 documentation since you add a new user facing functionality of py3

**Comment by tobes** [comment]
> Please update the py3 documentation

But it is auto documented ;p  Just merge this and it'll be in the docs

**Comment by ultrabug** [comment]
/me wishes the formatter documented itself as well

**Comment by tobes** [comment]
> /me wishes the formatter documented itself as well

haha

**Pull request merged**
