### PR TITLE
volume_status: add pactl support

### PR DESCRIPTION
**Pull request by tobes**
I've added a new 'backend' for volume_status to use `pactl`

My main reason for this is pulseaudio allows a volume greater than 100% useful for quiet youtube videos etc.

I've added a `max_volume` parameter to control this.  @guiniol how does pamixer deal with setting volumes above 100%?  maybe you could add max_volume support for it.

### CODE REVIEW

**Comment by guiniol** [comment]
I'll have to check. Pretty new to pulseaudio, I didn't know I could do that ^^

**Comment by ultrabug** [comment]
Thanks @tobes , what if we're not using pulseaudio ? wouldn't 100 be a better and safer default ?

**Comment by guiniol** [comment]
@tobes I checked pamixer, but while there's a way to allow going past 100%, I can't use the increase/decrease and have to set the volume explicitely (so I also need to get it). I don't think I'll add support for that on this backend. However, it might be good to rename the backend from `PulseaudioBackend` to `PamixerBackend`.

@ultrabug It has to be used by backends explicitely, so it's ignored by the alsa one. No problem there.

**Comment by ultrabug** [comment]
@guiniol thanks for clarifying, okay

**Comment by tobes** [comment]
> However, it might be good to rename the backend from PulseaudioBackend to PamixerBackend.

done

**Pull request merged**
