### PR TITLE
replace pygame with pyglet

### PR DESCRIPTION
**Pull request by beetleman**
It is easer to install pyglet(pip) than pygame(sources or packages).

### CODE REVIEW

**Comment by ultrabug** [comment]
Hi @beetleman, thanks for this proposal.

In order to not force current users to switch, would you please rather implement pygame as a fallback from pyglet ? This would allow new users to choose pyglet over pygame while keeping maximum compatibility.

**Comment by beetleman** [comment]
Ok. I'll do it after work.

**Comment by beetleman** [comment]
II have some problem with install pygame. Can You test it with pygame?

**Comment by ultrabug** [comment]
@beetleman unfortunately I don't run pygame either, I'll have a look at how you implemented this, if it looks safe enough, I'll merge ;)

**Comment by ultrabug** [comment]
@beetleman thanks for your patience, I tested it with both and it works great ! There's a little typo on method names which I'll correct after merging.

Cheers !

**Comment by ultrabug** [comment]
All good, thx again !

**Pull request merged**
