### PR TITLE
py3: print full command in the error logs

### PR DESCRIPTION
**Pull request by lasers**
https://github.com/ultrabug/py3status/pull/1089 leaves the `command` string untouched if `shell` is `True`. When a `retcode` error occurs, it prints the first char (of the string) instead of the first element (of the list) in the log. Minor bugfix.

```
self.py3.command_output('mocp --info', shell=True)

# Expected `mocp`, got `m`.
CommandError: Command `m` returned non-zero exit status -6 (State: PLAY )
```

### CODE REVIEW

**Comment by tobes** [comment]
Maybe we should take the opposite approach and actually show the whole command instead of just the first part

```python
                if isinstance(command, list):
                    command = ' '.join(command)
                 msg = msg.format(cmd=command, ...
```

Does that make more sense?

**Comment by lasers** [comment]
Yes. Let's try that. It'd be easier to know which command triggers this instead of having to parse the line number it reported on. Minor concern about stretching a line, but not a dealbreaker. Got a diff you'd like to use?

**Comment by tobes** [comment]
> Got a diff you'd like to use?

No I just typed it here so it'd want testing etc but If you update this PR that'd be great a comment on what we're doing is always nice too :)

**Comment by lasers** [comment]
No comment. Tested.

`Usual`.
```
2017-11-01 06:32:06 WARNING Instance `moc`, user method `moc` failed (CommandError) py3.py line 906.
2017-11-01 06:32:06 INFO Traceback
CommandError: Command `['mocp', '--info']` returned non-zero exit status -6 (State: PLAY )
  File "/home/chris/src/py3status/py3status/module.py", line 729, in run
    response = method()
  File "/home/chris/src/py3status/py3status/modules/moc.py", line 108, in moc
    is_started, moc_data = self._get_moc_data()
  File "/home/chris/src/py3status/py3status/modules/moc.py", line 96, in _get_moc_data
    data = self.py3.command_output(['mocp', '--info'])
  File "/home/chris/src/py3status/py3status/py3.py", line 906, in command_output
    msg, error_code=retcode, error=error, output=output
```
`Shell=True`.
```
2017-11-01 06:32:42 WARNING Instance `moc`, user method `moc` failed (CommandError) py3.py line 906.
2017-11-01 06:32:42 INFO Traceback
CommandError: Command `mocp --info` returned non-zero exit status -6 (State: PLAY )
  File "/home/chris/src/py3status/py3status/module.py", line 729, in run
    response = method()
  File "/home/chris/src/py3status/py3status/modules/moc.py", line 108, in moc
    is_started, moc_data = self._get_moc_data()
  File "/home/chris/src/py3status/py3status/modules/moc.py", line 96, in _get_moc_data
    data = self.py3.command_output('mocp --info', shell=True)
  File "/home/chris/src/py3status/py3status/py3.py", line 906, in command_output
    msg, error_code=retcode, error=error, output=output
```

**Comment by tobes** [comment]
> ``['mocp', '--info']``

I think we should show this as `mocp --info` because that is what we actually run.
maybe also log the `['mocp', '--info']` if we are a list to help debugging when we convert it to the string.

If I have a bad command in the logs I want to be able to just copy it from the logs and run in a terminal to help debug the problem

**Comment by lasers** [comment]
Tested three things here. String, list, string with shell.... I think it was `['mocp', '--info']` here... If you looked at `moc` cleanup PR, I'm already trying to turn the `list` into the `string`.

**Comment by tobes** [comment]
This has gone weird.

from my point of view when we notify the user etc we should use the 'sensible' form.  ie what we would run in a terminal. so for `moc` it'd be `moc --info` anything else is meaningless to a user.  we can also log the actual command used for debugging purposes eg `['mocp', '--info']` but this is the least important bit as it is meaningless to anyone but a developer.

**Comment by lasers** [comment]
```
2017-11-01 15:33:13 WARNING Instance `moc`, user method `moc` failed (CommandError) py3.py line 915.
2017-11-01 15:33:13 INFO Traceback
CommandError: Command `mocp --info` returned non-zero exit status -6 (State: PLAY )
  File "/home/chris/src/py3status/py3status/module.py", line 729, in run
    response = method()
  File "/home/chris/src/py3status/py3status/modules/moc.py", line 108, in moc
    is_started, moc_data = self._get_moc_data()
  File "/home/chris/src/py3status/py3status/modules/moc.py", line 96, in _get_moc_data
    data = self.py3.command_output(['mocp', '--info'])
  File "/home/chris/src/py3status/py3status/py3.py", line 915, in command_output
    msg, error_code=retcode, error=error, output=output
```

**Comment by ultrabug** [comment]
Thanks @lasers :)

**Pull request merged**
