### PR TITLE
sysdata: rename temp_unit to cpu_unit

### PR DESCRIPTION
**Pull request by lasers**
Second pull request. I rename `temp_unit` to `cpu_unit` as this config is more of an argument for  `sensors` command than a `sysdata` placeholder. If you want to be nitpick, `cpu_temp_unit` would be better. The best would be to just remove this and make a dedicated module instead because this placeholder is hardcoded to only the first `CPU`... and there are other sensor readings too.

Another reason for making a dedicated module... is that the more placeholders we add, the more likely the other placeholders or methods won't be used much... as users can be content with default `format`... Also, the various placeholders are just stuck with one `cache_timeout`.

This basically prints `°C`, `°F`, or `K` and if users do not want `°`, then they have to customize the `format` instead... which technically would be the correct way to do, but is stupid to accept `F`, `°F`, `C`, `°C`, `K`.... ~~and why not putting in `C`, `F`, `K` in the `format` too~~ FIXED: and why not just deprecating the placeholder? Anyhow, this is not what I'm doing here. I'm just renaming this for now. Let me know if you want `cpu_temp_unit`, `cpu_temperature_unit` instead... to make room for `cpu_clockrate_unit` or whatever could happen.

### CODE REVIEW

**Comment by lasers** [comment]
Also, consider whenever we want to use full names instead of abbreviations...
* `{cpu_temp}` to `{cpu_temperature}`
* `{cpu_temp_unit}` to `{cpu_temperature_unit}`
* `{mem_total}` to `{memory_total}`
* `{mem_unit}` to `{memory_unit}`
* `{mem_used}` to `{memory_used}`
* `{mem_used_percent}` to `{memory_used_percent}`

I assume we stopped doing abbreviations before I get involved as I only know to avoid fake abbreviations (eg, temp... and not gpu or hdd).

**Comment by lasers** [comment]
Let me know the decision first before merging... I think I should be nitpick and either rename this to `cpu_temperature_unit` or remove this in favor of new module in near future.

**Comment by tobes** [comment]
First we should get lm_sensors merged

I'm also tempted to leave this here for now and just kill the module at some point but maybe that is just a dream

**Comment by lasers** [comment]
That's fine with me. We can rename the placeholders last thing last.

>maybe that is just a dream

I'm not sure what to do with `cpu`, `mem`, but I think with `psutil` implementation, then it could stay as-is... or we replace `sysdata` with `psutil`. Dunno.

**Comment by lasers** [comment]
@tobes I want to know what to do here. Otherwise, I keep going and improve `cpu_temp` too... possibly for the naught.

**Comment by ultrabug** [comment]
discussed with you

**Pull request closed without merging**
