### PR TITLE
new py3 helper flatten_dict()

### PR DESCRIPTION
**Pull request by tobes**
`getjson` module has a dict flattening method.

```
{
    'fish_facts': {
        'shark': 'Most will drown if they stop moving',
        'skates': 'More than 200 species',
    }
    'fruits': ['apple', 'peach', 'watermelon'],
    'number': 52
}

# becomes

{
    'fish_facts-sharks': 'Most will drown if they stop moving',
    'fish_facts-skates': 'More than 200 species',
    'fruits-0': 'apple',
    'fruits-1': 'peach',
    'fruits-2': 'watermelon',
    'number': 52
}
```

make this available to other modules

### CODE REVIEW

**Comment by lasers** [comment]
Neat. I have this in pending `gpmdp` PR using different `flatten_dict`. https://github.com/ultrabug/py3status/pull/878/files -- Can you look into that too and decide which `flatten_dict` is more efficient / better? I got mine off somewhere on Internet.

**Comment by tobes** [comment]
yeah I saw your code which is one of the reasons to do this PR.

From what I can see your code does not flatten lists ie it breaks `getjson` maybe we make improvements to my code.  I'd like to hide `parent_key`.

I can change the default deliminator to `_`.  The reason we have `-` is due to json like 
```
{  'my_list': [1, 2, 3] }
```

**Comment by tobes** [comment]
@laser thanks to your comments I ended up writing a bunch of tests for this function and have improved a slight bug my code had with list intermediates.

I've left the default deliminator as '-' because to me that sort of feels right give JSON's JavaScript history and the fact that `_` is valid in names whereas `-` is not in both python and Javascript.  I know that this is not the case in JSON names but it will be if people are sensible.

We can set the delimiter easily if we need it different.

@ultrabug I ended up cleaning getjson a little more that I possibly should have.

**Comment by ultrabug** [comment]
I think it's great as is, @lasers are you okay to merge ?

**Comment by lasers** [comment]
@ultrabug Yes. I'm okay with that. This works superb. I already went ahead and switch to this one as I find that it's the the best `flatten_dict` brand for my pending `gpmdp` PR. Please go ahead and merge this in. Many thanks. 👍

**Pull request merged**
