### PR TITLE
new module from scratch: bluetooth2

### LINKED ISSUE #1862: Add option to format bluetooth module output if there's no adapter detected
I currently see no way of configuring the icon/text when using bluetooth module. If there is something wrong with the adapter, the text just says: "bluetooth". It would be nice if a user can define that for instance a greyed out bluetooth icon is shown instead.

### PR DESCRIPTION
**Pull request by lasers**
This adds more placeholders, colors, formats, etc. Made this long time ago. Still working fine today.

Closes #1862.

### CODE REVIEW

**Comment by ultrabug** [comment]
Could you make the defaults to be backward compatible for current users?

**Comment by lasers** [comment]
Probably not because I forget things. At a glance, it looks like the (default) parity will be mostly same, but not existing config. Also, because there is an existing / old backward compatible code already in there. This one just takes everything off.

I wonder if I should keep the names green (connected) or just leave it blank (default color). Probably OK either way. I have included a legacy format in EXAMPLES should users want to add prefix BT.

This gets rid of pydbus too.

**Comment by ultrabug** [comment]
Now I'm always reluctant to modules rewrite not being backwards compatible tbh

Since it's a rewrite, please align license with BSD, also I'd rather let people choose their colors

**Comment by lasers** [comment]
@ultrabug Is there anything else I have to do here?

**Comment by anarcat** [comment]
i'm not a maintainer here but i would suspect that a backwards-incompatible change would at least warrant a warning in the CHANGELOG. alternatively, it should be made backwards-compatible, or maybe just renamed (bluetooth2?)?

**Comment by ultrabug** [comment]
I agree with @anarcat ; I can't get around the idea of breaking current users' modules

So, let's rename it to bluetooth2 and add a deprecation warning on the other + CHANGELOG notice; then in a version or two, we'll do the switch.

**Comment by lasers** [comment]
As request, I renamed this to `bluetooth2.py`. You can take over for deprecation warning + CHANGELOG notice since I am unsure how to proceed from here as we already did some deprecation warnings in the past. Cheers.

**Pull request merged**
