### PR TITLE
whatismyip: support multiple criterias for expected config

### LINKED ISSUE #1922: Python Dict for expected in whatismyip means only one city (or other criteria) at a time?
Hai guise! Hope I'm not being too much of a pest. :smile: Just logging some annoyances here until maybe I get enough annoyed to dust off my Python and think about submitting a PR. :smile: 

Until I can get [VPN](https://github.com/ultrabug/py3status/issues/1918) working reliably for me, I have been looking for workarounds, which led me to `whatismyip` module. So far I set it up to display the city of my VPN, and turn green when it's on that city (i.e., when VPN is using that exit node).

But sometimes I use different exit nodes. And according to [Python docs](https://docs.python.org/3/tutorial/datastructures.html#dictionaries) (emphasis mine):
> It is best to think of a dictionary as a set of key: value pairs, with the requirement that *the keys are unique* (within one dictionary)

If I am understanding this correctly, then that means we can only have one "city" (or other criteria) at a time for the `expected` dict? Is that right?

### PR DESCRIPTION
**Pull request by lasers**
This support multiple criterias. Semi-tested. Not sure how strict it ought to be.

/cc potential tester @TRSx80 and others. EDIT: Please test this thoroughly. Thx.

Closes https://github.com/ultrabug/py3status/issues/1922

### CODE REVIEW

**Comment by TRSx80** [comment]
Sweet, man! Much appreciated!

I'll kick the tires and let you know how it works out.

**Comment by TRSx80** [comment]
I'm getting some weirdness...

Let's just say (for example's sake) my correct external IP address is `1.1.1.1` and the correct city is `CorrectCity`.  I am intermittently getting variations of the following:
```
1.1.1.1 CorrectCity      (i.e., everything correct)
1.1.1.1 {city}           (yes literal brackets in the output)
{ip} {city}              (again yes literal brackets)
```
I don't know if I "installed" it correctly or not. I simply copied the whole file down from your repository and replaced the original file (on my Debian machine, originally installed via `pip3 --user` that would be `~/.local/lib/python3.8/site-packages/py3status/modules/whatismyip.py`. First I renamed the original as `whatismyip.py.orig` but when I started having issues I thought I dunno, maybe it's cached or something? So I moved the original to a whole another directory (`~/tmp/`). Then I reloaded / restarted i3 a few times, and even logged back out and back in... I kept thinking I dunno, maybe something was cached. But none of that helped.

Now this is weird. All of a sudden it has been steadily reporting the correct info during the entire time (several minutes) that I was composing this message. :/ Now I am not sure what's going on...

I will keep an eye on it and report back in another day or two I guess.

**Comment by lasers** [comment]
py3status can read user-define module paths. You can try this in one of the default paths instead and of course, you can use different name to ensure / compare this against the original `whatismyip`.  
```bash
wget https://raw.githubusercontent.com/lasers/py3status/whatismyip-fnmatch/py3status/modules/whatismyip.py -O ~/.config/py3status/modules/whatismyip.py
```

About your weirdness... I think literal brackets may be that the requests went through successfully, but came back with different datas from the site (e.g. empty, semi, full). Unconfirmed. I can look into this.

**Comment by TRSx80** [comment]
Thanks for the tip. Python is so great and versatile.

I think you are on the right track. Kind of keeping an eye on it here the last hour while doing other things I noticed it seems to maybe kind of follow a pattern: start out correct, then flake out with brackets (upon periodic update, presumably), and then finally eventually stabilize with the correct info, and then stay that way for a good long while. Change VPN exit and the cycle repeats.

**Comment by TRSx80** [comment]
Oh no, I spoke too soon.  :smile:

No sooner did I navigate to some other tab after posting my last message than I started getting brackets again. And this without touching anything.

**Comment by lasers** [comment]
`whatismyip-log.py` -- Not wanting to log everything from py3status. This module write request datas to `/tmp/py3status-whatismyip.log` so you can tell us if it's really missing some fields.

You can wget this and use `tail -f /tmp/py3status-whatismyip.log`.

**Comment by ultrabug** [comment]
@TRSx80 hi mate, still want this in? plz update us!

Thanks

**Comment by TRSx80** [comment]
Sorry guys!  Got very busy with other stuff, shifting priorities, you know how it goes...

I feel bad that I could not at least contribute to testing, especially after requesting for a feature...

Is it getting in anyway?  Or do I need to help out with more testing first?  In the latter case, I will make an effort to make it a priority.  I feel it's the least I can do, what being the one who opened the issue in the first place.  :smile: 

I really do appreciate how responsive you guys have been!

**Comment by ultrabug** [comment]
@TRSx80 well yes please, either test & confirm that it's working as you expected or tell us if we can close this because I won't get this in without a real user report :)

**Comment by TRSx80** [comment]
Maybe I am missing something here, but...

If I use [`whatismyip-log`](https://github.com/lasers/py3status/blob/whatismyip-log/py3status/modules/whatismyip.py), I get logging but there is no support for multiple locations (expected: [...] This should be a dict eg {'country': 'France'}).

If, on the other hand, I use [lasers' `whatismyip-fnmatch` branch](https://raw.githubusercontent.com/lasers/py3status/whatismyip-fnmatch/py3status/modules/whatismyip.py), I get multiple criteria (expected: [...] This should be a list of dicts eg [{'country': 'France'}]) but then no logging?

**Comment by ultrabug** [comment]
I think you can get the expected behavior by using multiple instances of the same module and then using a group to select the one you are interested in without the need to add complexity to the current module

So I'll close this PR and related issue unless you feel it's absolutely unfair; thanks

**Pull request closed without merging**
