### PR TITLE
timewarrior: fix potential exceptions

### PR DESCRIPTION
**Pull request by lasers**
This module contain `self.py3.command_output`, but not under `try/except`.

May have to be tweaked again to deal with possible new i3bar `post_config_hook` exception for bits and pieces... such as `isn't installed`.

### CODE REVIEW

**Comment by tobes** [comment]
#781 allows us a new way to show errors. 

`self.py3.error(msg, timeout)`

`msg` message to be displayed explaining the error

`timeout` how long before we should retry.  For permanent errors`py3.CACHE_FOREVER` should be returned.  If not supplied then the
modules `cache_timeout` will be used.

do want to switch this PR to use that helper?

**Comment by lasers** [comment]
I'm on IRC if you want to have a chat about this issue.

**Comment by tobes** [comment]
Thanks very clean PR

**Comment by lasers** [comment]
Lol. This is `taskwarrior`, not `timewarrior`. :-\

P.S. I'm planning on closing all PRs to make life easier for `py3status` collaborators.

**Comment by tobes** [comment]
> P.S. I'm planning on closing all PRs to make life easier for py3status collaborators.

I'd rather we do a review of them and decide a way forward for each some might die but some get merged or we decide on a good solution. You have some good ideas in many and I'd not want to lose those

**Comment by lasers** [comment]
I was thinking about moving them to `unstable` branch and make changes freely... This way, I can stay out of issues and pull requests... Users can try them knowing it might break some thing... And I want to go ahead and do the `mergeformat` for all of them in `unstable` branch too.

We should be able to cherry-pick things over to `stable` py3status. Do you agree with this approach? This would drop pull requests down to `16` and could help alleviate some frustrations for all involved. I also could try some new things after fixing all the little things.

**Pull request merged**
