### PR TITLE
[BUGFIX] module imap: fix output formatting issue

### PR DESCRIPTION
**Pull request by girst**
Essentially, whenever I booted into i3, for a short time (until the network was available), 'mail: None' was displayed. This fixes both the fact that it should be 'mail: N/A' and also delays displaying it when using IDLE (so the behaviour is the same compared to polling mode)

### CODE REVIEW

**Comment by lasers** [comment]
Actually, `N/A` should be deprecated in favor of `None` to allow users to specify in the format what ought to happen (eg stay hidden or show format as-is, or show something else).

The real issue I see is that if the current format `format = 'Mail: {unseen}'` prints `Mail: None` instead of `''` with data `{'unseen': None}` then the code is wrong in `imap` module.

Other issue is that to clean this up easily, we need to kill some unsavory configs such as `allow_urgent` (in favor of global `allow_urgent`) and `hide_if_zero` (in favor of formatting). Maybe some other configs too such as  `debug` config (not for users).... to put everything in a single response.

**Comment by lasers** [comment]
Refactoring is how we fix the real bug. This PR simply changes the outcome so it would print something else and not printing anything on startup (ie `-1`). The bug is still going to be there.

The real bug is that there is a several if statements to dictate the response dict for `full_text`, `color`, `urgent`, `hide_if_zero`, etc. This just add more. All of that should be done in the `format` instead.

Refactoring requires new config `thresholds`, killing `allow_urgent` and `hide_if_zero` configs, and adding `\?color=unseen` to the `format`. I'd hide `debug` config too. I'm just saying this out loud. ;-)

**Comment by tobes** [comment]
@girst Thanks for this bug fix.  I need to sort the travis issues and then I'll look at merging this.  Maybe combine the two tests that produce the `''` output.

@lasers let's try to stay focused.  Yep this module could be better, but messing with it and adding new config settings is taking us in the wrong direction.  We need to be simplifying stuff not complicating it.  And really that is not about the modules themselves.

**Comment by girst** [comment]
Great to hear! I kept them separate, since these are two different modes that just incidentally share the same output, but I could change it tomorrow, if you want.

**Comment by girst** [comment]
so, I was just merging the two `''` outputs together, and I think this does more harm than good. IMO it makes the code less readable / more obfuscated:

            elif self.mail_count == NO_DATA_YET or (self.mail_count == 0 and self.hide_if_zero):

does not look very neat and makes `mail_count == 0` kinda disappear in the noise. 

            elif (self.mail_count == NO_DATA_YET or
                 (self.mail_count == 0 and self.hide_if_zero)):

splitting it across two lines would be an option, but a) requires two pairs of parenthesis (instead of 0) and b) makes you take a second look on how the comparisons are combined (`or` <-> `and`)

if its OK with you, I'd like to keep it as-is.

**Comment by tobes** [comment]
```python
        elif (
            self.mail_count == NO_DATA_YET or
            (self.mail_count == 0 and self.hide_if_zero)
        ):
```
?

**Comment by girst** [comment]
how's that better/different than my second example?

**Comment by tobes** [comment]
Quite a lot, imho it is much more readable.

It is a bit what you are used to, and I don't really care here.

**Comment by ultrabug** [comment]
@girst could you rebase please? seems like I can't (no button)

**Comment by ultrabug** [comment]
Thanks mate

**Pull request merged**
